import { useCallback, useMemo, useState } from "react";
import { ActivityIndicator, Alert, Modal, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router, useFocusEffect, useLocalSearchParams } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import { Card, ScreenTitle, baseStyles as b } from "../../components/ui";
import { supabase } from "../../lib/supabase";
import { buildMobileClassificationPayload, buildMobileTransactionReviewRow, MOBILE_COST_CODES, type MobileCostCode, type MobileTransactionReviewRow } from "../../lib/transaction-cost-review";

const money=(n:number,c="NGN")=>new Intl.NumberFormat("en-NG",{style:"currency",currency:c,maximumFractionDigits:0}).format(n);
export default function ProjectCostClassify(){const {id}=useLocalSearchParams<{id:string}>();const enabled=process.env.EXPO_PUBLIC_PROJECT_COST_BRIDGE_ENABLED==="true";const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [name,setName]=useState("Project");const [currency,setCurrency]=useState("NGN");const [rows,setRows]=useState<MobileTransactionReviewRow[]>([]);const [selected,setSelected]=useState<Record<string,MobileCostCode|"">>({});const [editing,setEditing]=useState<string|null>(null);const [message,setMessage]=useState<string|null>(null);
const load=useCallback(async()=>{if(!id)return;setLoading(true);const {data:p}=await supabase.from("projects").select("id,name").eq("id",id).maybeSingle();if(p?.name)setName(p.name);if(!enabled){setMessage("Project-cost bridge is not activated yet. Money transactions remain unchanged.");setLoading(false);return;}const [{data:budget,error:be},{data:tx,error:te}]=await Promise.all([supabase.from("project_cost_budgets").select("id,currency_code").eq("project_id",id).eq("status","approved").maybeSingle(),supabase.from("transactions").select("id,amount,transaction_date,title,description,cost_code").eq("project_id",id).eq("kind","expense").eq("status","posted").is("cost_code",null).order("transaction_date",{ascending:false}).limit(500)]);if(be||!budget){setMessage("Approved Budget Baseline is required before cost-code review.");setLoading(false);return;}if(te){setMessage("Could not read the complete unclassified expense set. Nothing was changed.");setLoading(false);return;}setCurrency(budget.currency_code||"NGN");setRows((tx??[]).map((r:any)=>buildMobileTransactionReviewRow({transactionId:r.id,amount:Number(r.amount),transactionDate:r.transaction_date,title:r.title,description:r.description})));setMessage(null);setLoading(false)},[id,enabled]);useFocusEffect(useCallback(()=>{load()},[load]));
const chosen=useMemo(()=>Object.values(selected).filter(Boolean).length,[selected]);const high=rows.filter(r=>r.readyForBulkConfirm&&r.suggestedCostCode).length;
function useHigh(){setSelected(current=>{const next={...current};for(const row of rows)if(row.readyForBulkConfirm&&row.suggestedCostCode)next[row.transactionId]=row.suggestedCostCode;return next;});}
async function save(){if(!id||saving)return;let payload;try{payload=buildMobileClassificationPayload(id,selected);}catch(e){Alert.alert("Nothing to confirm",e instanceof Error?e.message:"Select an expense.");return;}setSaving(true);const {error}=await supabase.rpc("classify_project_expense_costs_v1",payload as any);setSaving(false);if(error){Alert.alert("Classification failed",error.message);return;}Alert.alert("Cost codes confirmed",`${chosen} expense${chosen===1?"":"s"} classified. Budget vs Actual will refresh.`);setSelected({});await load();}
if(loading)return <SafeAreaView style={b.screen}><View style={s.center}><ActivityIndicator size="large" color="#073f65"/></View></SafeAreaView>;
return <SafeAreaView style={b.screen} edges={["top"]}><ScrollView contentContainerStyle={b.content}><View style={s.backRow}><Pressable onPress={()=>router.back()}><Text style={s.back}>← Budget vs Actual</Text></Pressable><Text style={s.status}>REVIEW</Text></View><ScreenTitle eyebrow="ACTUAL COST CLASSIFICATION" title={name} subtitle="Charismak can suggest a construction cost group, but only your confirmed choices change Money classification."/>{message&&<Card><Text style={s.message}>{message}</Text></Card>}{enabled&&!message&&<><View style={s.actions}><Pressable disabled={!high||saving} onPress={useHigh} style={[s.secondary,(!high||saving)&&s.disabled]}><Text style={s.secondaryText}>Use {high} high-confidence</Text></Pressable><Pressable disabled={!chosen||saving} onPress={save} style={[s.primary,(!chosen||saving)&&s.disabled]}><Text style={s.primaryText}>{saving?"Confirming…":`Confirm selected (${chosen})`}</Text></Pressable></View>{!rows.length&&<Card><Text style={s.cardTitle}>All posted expenses are classified.</Text></Card>}{rows.map(row=><Card key={row.transactionId}><View style={s.txTop}><View style={{flex:1}}><Text style={s.date}>{row.transactionDate}</Text><Text style={s.cardTitle}>{row.title}</Text>{row.description&&<Text style={s.cardText}>{row.description}</Text>}</View><Text style={s.amount}>{money(row.amount,currency)}</Text></View><View style={s.suggestion}><Text style={s.conf}>{row.confidence.toUpperCase()} CONFIDENCE</Text><Text style={s.suggested}>{row.suggestedCostCode?`${row.suggestedCostCode} · ${row.suggestedCostName}`:"No automatic suggestion"}</Text><Text style={s.cardText}>{row.reasons.join(" ")}</Text></View><View style={s.rowActions}>{row.suggestedCostCode&&<Pressable onPress={()=>setSelected(x=>({...x,[row.transactionId]:row.suggestedCostCode!}))} style={s.secondary}><Text style={s.secondaryText}>Use suggestion</Text></Pressable>}<Pressable onPress={()=>setEditing(row.transactionId)} style={s.secondary}><Text style={s.secondaryText}>{selected[row.transactionId]?`${selected[row.transactionId]} selected`:"Choose code"}</Text></Pressable></View></Card>)}</>}
</ScrollView><Modal visible={!!editing} transparent animationType="slide" onRequestClose={()=>setEditing(null)}><View style={s.modalBack}><View style={s.modal}><View style={s.modalHead}><Text style={s.modalTitle}>Choose construction cost code</Text><Pressable onPress={()=>setEditing(null)}><Text style={s.close}>×</Text></Pressable></View><ScrollView>{MOBILE_COST_CODES.map(option=><Pressable key={option.code} onPress={()=>{if(editing)setSelected(x=>({...x,[editing]:option.code}));setEditing(null)}} style={s.codeRow}><Text style={s.code}>{option.code}</Text><Text style={s.codeName}>{option.name}</Text></Pressable>)}</ScrollView></View></View></Modal></SafeAreaView>}
const s=StyleSheet.create({center:{flex:1,alignItems:"center",justifyContent:"center"},backRow:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},back:{fontSize:11,fontWeight:"800",color:"#0b5c8b"},status:{fontSize:8,fontWeight:"900",color:"#16825c"},message:{fontSize:10,lineHeight:15,color:"#6b7e8d"},actions:{flexDirection:"row",gap:8,flexWrap:"wrap"},primary:{backgroundColor:"#0b668f",borderRadius:9,paddingVertical:10,paddingHorizontal:12},primaryText:{fontSize:9,fontWeight:"900",color:"#fff"},secondary:{borderWidth:1,borderColor:"#9fc3d7",backgroundColor:"#fff",borderRadius:9,paddingVertical:8,paddingHorizontal:10},secondaryText:{fontSize:8,fontWeight:"900",color:"#0b668f"},disabled:{opacity:.45},txTop:{flexDirection:"row",gap:10,alignItems:"flex-start"},date:{fontSize:7,color:"#87939c"},cardTitle:{fontSize:11,fontWeight:"900",color:"#173f5a",marginTop:2},cardText:{fontSize:8,lineHeight:13,color:"#718391",marginTop:3},amount:{fontSize:11,fontWeight:"900",color:"#173f5a"},suggestion:{backgroundColor:"#f5f9fb",borderRadius:9,padding:8,marginTop:8},conf:{fontSize:7,fontWeight:"900",color:"#16825c"},suggested:{fontSize:9,fontWeight:"900",color:"#0b668f",marginTop:3},rowActions:{flexDirection:"row",gap:7,flexWrap:"wrap",marginTop:8},modalBack:{flex:1,backgroundColor:"rgba(4,24,38,.48)",justifyContent:"flex-end"},modal:{maxHeight:"82%",backgroundColor:"#fff",borderTopLeftRadius:22,borderTopRightRadius:22,overflow:"hidden"},modalHead:{backgroundColor:"#073f65",padding:15,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},modalTitle:{fontSize:14,fontWeight:"900",color:"#fff"},close:{fontSize:26,color:"#fff"},codeRow:{padding:14,borderBottomWidth:1,borderBottomColor:"#edf1f4",flexDirection:"row",gap:12,alignItems:"center"},code:{fontSize:11,fontWeight:"900",color:"#0b668f",width:28},codeName:{fontSize:10,fontWeight:"800",color:"#29475c",flex:1}});
