"use client";

import { useMemo, useState, useTransition } from "react";
import type { StagedProjectWorkspace } from "../../../../lib/estimate/staged-project-workspace";
import { validateAppProjectApproval, type ProjectApprovalDetails } from "../../../../lib/project-cost/app-project-approval";
import { approveDraftProjectAction } from "./actions";

export default function ApprovalClient({ draft }: { draft: StagedProjectWorkspace }) {
  const [location,setLocation]=useState("");const [projectCode,setProjectCode]=useState("");const [clientName,setClientName]=useState("");const [projectType,setProjectType]=useState("");const [startDate,setStartDate]=useState("");const [expectedEndDate,setExpectedEndDate]=useState("");const [description,setDescription]=useState("");const [message,setMessage]=useState<{tone:"good"|"warn";text:string}|null>(null);const [pending,startTransition]=useTransition();
  const details=useMemo<ProjectApprovalDetails>(()=>({location,projectCode,clientName,projectType,startDate,expectedEndDate,description}),[location,projectCode,clientName,projectType,startDate,expectedEndDate,description]);
  const issues=useMemo(()=>validateAppProjectApproval(draft,details),[draft,details]);
  function approve(){setMessage(null);startTransition(async()=>{const result=await approveDraftProjectAction({workspace:draft,details});if(result.ok){setMessage({tone:"good",text:`Live project created with approved budget baseline. Project ${result.result.project_id}; budget ${result.result.budget_id}. No Money transaction was created.`});}else setMessage({tone:"warn",text:result.message});});}
  return <section className="compact-card" style={{display:"grid",gap:11}}><div><small style={eye}>LIVE PROJECT APPROVAL</small><h2 style={title}>Approve this reviewed draft into Projects</h2><p style={copy}>This is an MD approval gate. It creates only the live project and approved Budget Baseline through one atomic RPC. Expenses, funding, commitments and Money transactions are not created.</p></div><div style={grid}><Field label="Location *" value={location} onChange={setLocation} placeholder="e.g. Jahi, Abuja"/><Field label="Project code" value={projectCode} onChange={setProjectCode} placeholder="Optional"/><Field label="Client" value={clientName} onChange={setClientName} placeholder="Optional"/><Field label="Project type" value={projectType} onChange={setProjectType} placeholder="Optional"/><Field label="Start date" value={startDate} onChange={setStartDate} placeholder="YYYY-MM-DD"/><Field label="Expected end" value={expectedEndDate} onChange={setExpectedEndDate} placeholder="YYYY-MM-DD"/></div><label style={{display:"grid",gap:4}}><span style={label}>DESCRIPTION</span><textarea value={description} onChange={e=>setDescription(e.target.value)} rows={3} placeholder="Optional project note" style={{...input,resize:"vertical"}}/></label>{issues.length>0&&<div style={warn}><b>Approval package still needs:</b><ul style={{margin:"5px 0 0",paddingLeft:18}}>{issues.slice(0,8).map(item=><li key={item}>{item}</li>)}</ul></div>}{issues.length===0&&<div style={good}><b>Approval package is internally consistent.</b> The same reviewed cost codes, budget lines, allowances and material schedule will be fingerprinted before any live write.</div>}{message&&<div style={message.tone==="good"?good:warn}>{message.text}</div>}<div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"center",flexWrap:"wrap",borderTop:"1px solid #e5ecef",paddingTop:10}}><small style={copy}>The live bridge remains feature-gated. If the reviewed database migration is not enabled, the server will stop here safely rather than creating a partial project.</small><button type="button" onClick={approve} disabled={pending||issues.length>0} style={{...button,opacity:pending||issues.length>0?.45:1}}>{pending?"Checking approval…":"Approve live project"}</button></div></section>;
}
function Field({label:fieldLabel,value,onChange,placeholder}:{label:string;value:string;onChange:(value:string)=>void;placeholder:string}){return <label style={{display:"grid",gap:4}}><span style={label}>{fieldLabel.toUpperCase()}</span><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} style={input}/></label>}
const eye:React.CSSProperties={fontSize:8,fontWeight:900,letterSpacing:".1em",color:"#16825c"};const title:React.CSSProperties={fontSize:15,color:"#173f5a",margin:"5px 0"};const copy:React.CSSProperties={fontSize:9,lineHeight:1.5,color:"#718391",margin:0,maxWidth:760};const grid:React.CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:8};const label:React.CSSProperties={fontSize:7,fontWeight:900,letterSpacing:".08em",color:"#6c7f8d"};const input:React.CSSProperties={border:"1px solid #cbd8e0",borderRadius:9,padding:"9px 10px",fontSize:10,color:"#173f5a",background:"#fff",boxSizing:"border-box",width:"100%"};const warn:React.CSSProperties={background:"#fff4ce",borderRadius:10,padding:10,fontSize:9,lineHeight:1.5,color:"#775c18"};const good:React.CSSProperties={background:"#e7f6ef",borderRadius:10,padding:10,fontSize:9,lineHeight:1.5,color:"#176247"};const button:React.CSSProperties={border:0,borderRadius:9,padding:"10px 13px",background:"#0b668f",color:"#fff",fontSize:9,fontWeight:900,cursor:"pointer"};
