import { useCallback, useMemo, useState } from "react";
import { ActivityIndicator, Alert, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useFocusEffect } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import { supabase } from "../lib/supabase";
import { loadWorkspace } from "../lib/workspace";
import { Card, ScreenTitle, SectionHead, baseStyles as b } from "../components/ui";

const roles=[{code:"MD_OWNER",label:"MD / Owner"},{code:"CFO",label:"Accountant / CFO"},{code:"PROJECT_DIRECTOR",label:"Project Director"},{code:"PROJECT_MANAGER",label:"Project / Construction Manager"}];

export default function Access(){
  const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [companyId,setCompanyId]=useState("");const [roster,setRoster]=useState<any>({members:[],projects:[],positions:[],role_emails:[]});const [emails,setEmails]=useState<Record<string,string>>({});const [busy,setBusy]=useState("");const [selectedMember,setSelectedMember]=useState("");const [selectedProject,setSelectedProject]=useState("");
  const load=useCallback(async()=>{const w=await loadWorkspace();if(!w.membership.is_owner)throw new Error("MD / Owner access required");setCompanyId(w.membership.company_id);const {data,error}=await supabase.rpc("company_access_roster",{target_company:w.membership.company_id});if(error)throw error;const r:any=data||{members:[],projects:[],positions:[],role_emails:[]};setRoster(r);const m:Record<string,string>={};for(const x of r.role_emails||[])m[x.position_code]=x.email||"";setEmails(m);setLoading(false);setRefreshing(false)},[]);useFocusEffect(useCallback(()=>{load().catch(e=>{setLoading(false);Alert.alert("Could not load access",e instanceof Error?e.message:"Try again")})},[load]));
  const members=(roster.members||[]) as any[];const projects=(roster.projects||[]) as any[];const positions=(roster.positions||[]) as any[];const nonOwners=members.filter(m=>!m.is_owner);
  async function saveRole(code:string,label:string){const email=String(emails[code]||"").trim().toLowerCase();if(!email)return Alert.alert("Email required");setBusy(`role-${code}`);const {error}=await supabase.rpc("owner_save_role_email",{target_company:companyId,target_position_code:code,target_email:email,target_label:label});setBusy("");if(error)return Alert.alert("Could not save",error.message);Alert.alert("Saved",`${label} email is ready.`);load()}
  async function setPosition(memberId:string,code:string){setBusy(`pos-${memberId}`);const {error}=await supabase.rpc("owner_set_member_position",{target_company:companyId,target_membership:memberId,target_position_code:code});setBusy("");if(error)return Alert.alert("Could not update position",error.message);load()}
  async function assign(){if(!selectedMember||!selectedProject)return Alert.alert("Choose a member and project");setBusy("assign");const {error}=await supabase.rpc("owner_assign_project_access",{target_company:companyId,target_membership:selectedMember,target_project:selectedProject,target_role:"Assigned project team",view_cost:true,can_request:true,can_approve:false});setBusy("");if(error)return Alert.alert("Could not assign project",error.message);setSelectedMember("");setSelectedProject("");load()}
  async function remove(assignmentId:string){setBusy(`remove-${assignmentId}`);const {error}=await supabase.rpc("owner_remove_project_access",{target_company:companyId,target_assignment:assignmentId});setBusy("");if(error)return Alert.alert("Could not remove access",error.message);load()}
  if(loading)return <SafeAreaView style={b.screen}><View style={s.center}><ActivityIndicator size="large" color="#073f65"/></View></SafeAreaView>;
  return <SafeAreaView style={b.screen} edges={["top"]}><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);load()}}/>} contentContainerStyle={b.content}><ScreenTitle eyebrow="PEOPLE & ACCESS" title="Who can do what" subtitle="Set position emails, assign roles and control which projects each person can work on. MD / Owner retains company-wide access."/>
    <SectionHead title="Position emails"/>{roles.map(r=><Card key={r.code} style={s.roleCard}><Text style={s.role}>{r.label}</Text><TextInput value={emails[r.code]||""} onChangeText={v=>setEmails(x=>({...x,[r.code]:v}))} autoCapitalize="none" keyboardType="email-address" placeholder={`${r.code.toLowerCase()}@company.com`} style={s.input}/><Pressable disabled={!!busy} onPress={()=>saveRole(r.code,r.label)} style={s.smallButton}><Text style={s.smallButtonText}>{busy===`role-${r.code}`?"Saving…":"Save email"}</Text></Pressable></Card>)}

    <SectionHead title="Members & positions"/>{members.map(m=>{const primary=(m.positions||[]).find((p:any)=>p.is_primary)||(m.positions||[])[0];return <Card key={m.membership_id} style={s.member}><View style={b.row}><View style={{flex:1}}><Text style={s.memberEmail}>{m.email}</Text><Text style={s.memberNote}>{m.is_owner?"Owner · company-wide":primary?.name||"No primary position"}</Text></View><Text style={s.status}>{m.status}</Text></View>{!m.is_owner&&<View style={s.choiceWrap}>{positions.map((p:any)=><Pressable disabled={!!busy} key={p.code} onPress={()=>setPosition(m.membership_id,p.code)} style={[s.choice,primary?.code===p.code&&s.choiceActive]}><Text style={[s.choiceText,primary?.code===p.code&&s.choiceTextActive]}>{p.name}</Text></Pressable>)}</View>}<View style={s.tags}>{(m.projects||[]).map((a:any)=><View key={a.assignment_id} style={s.tag}><Text style={s.tagText}>{a.project_code} · {a.assignment_role||"Assigned"}</Text>{!m.is_owner&&<Pressable onPress={()=>remove(a.assignment_id)}><Text style={s.remove}>×</Text></Pressable>}</View>)}{!(m.projects||[]).length&&<Text style={s.memberNote}>{m.is_owner?"Owner sees all company projects.":"No project-specific access yet."}</Text>}</View></Card>})}

    {!!nonOwners.length&&<><SectionHead title="Assign project access"/><Card><Text style={s.label}>Member</Text><View style={s.choiceWrap}>{nonOwners.map(m=><Pressable key={m.membership_id} onPress={()=>setSelectedMember(m.membership_id)} style={[s.choice,selectedMember===m.membership_id&&s.choiceActive]}><Text style={[s.choiceText,selectedMember===m.membership_id&&s.choiceTextActive]}>{m.email}</Text></Pressable>)}</View><Text style={s.label}>Project</Text><View style={s.projectList}>{projects.map(p=><Pressable key={p.id} onPress={()=>setSelectedProject(p.id)} style={[s.project,selectedProject===p.id&&s.projectActive]}><Text style={[s.projectCode,selectedProject===p.id&&s.activeText]}>{p.project_code}</Text><Text style={[s.projectName,selectedProject===p.id&&s.activeText]}>{p.name}</Text></Pressable>)}</View><Pressable disabled={!!busy} onPress={assign} style={[b.button,!!busy&&{opacity:.5}]}><Text style={b.buttonText}>{busy==="assign"?"Assigning…":"Assign project"}</Text></Pressable></Card></>}
  </ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({center:{flex:1,alignItems:"center",justifyContent:"center"},roleCard:{gap:8},role:{fontSize:12,fontWeight:"900",color:"#173b54"},input:{height:42,borderWidth:1,borderColor:"#d7e1e8",borderRadius:11,paddingHorizontal:10,fontSize:11,color:"#173b54",backgroundColor:"#fff"},smallButton:{height:38,borderRadius:10,backgroundColor:"#073f65",alignItems:"center",justifyContent:"center"},smallButtonText:{fontSize:9,fontWeight:"900",color:"#fff"},member:{gap:10},memberEmail:{fontSize:11,fontWeight:"900",color:"#173b54"},memberNote:{fontSize:8,color:"#7b8c98",marginTop:2},status:{fontSize:8,fontWeight:"900",color:"#16805d",textTransform:"uppercase"},choiceWrap:{flexDirection:"row",flexWrap:"wrap",gap:6},choice:{borderWidth:1,borderColor:"#dce5eb",borderRadius:10,paddingVertical:7,paddingHorizontal:8,backgroundColor:"#fff"},choiceActive:{backgroundColor:"#073f65",borderColor:"#073f65"},choiceText:{fontSize:8,fontWeight:"800",color:"#3d5a6e"},choiceTextActive:{color:"#fff"},tags:{flexDirection:"row",flexWrap:"wrap",gap:6},tag:{flexDirection:"row",alignItems:"center",gap:6,backgroundColor:"#edf4f8",borderRadius:9,paddingVertical:5,paddingHorizontal:7},tagText:{fontSize:7.5,fontWeight:"800",color:"#31536a"},remove:{fontSize:15,color:"#a44a43"},label:{fontSize:8,fontWeight:"900",color:"#687d8c",marginTop:4},projectList:{gap:6},project:{borderWidth:1,borderColor:"#dde5eb",borderRadius:11,padding:9},projectActive:{backgroundColor:"#e5f4ed",borderColor:"#55a988"},projectCode:{fontSize:7,fontWeight:"900",color:"#1874a8"},projectName:{fontSize:9.5,fontWeight:"800",color:"#294a60",marginTop:2},activeText:{color:"#086048"}});
