import { useEffect, useState } from "react";
import { Alert, Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import * as DocumentPicker from "expo-document-picker";
import { router } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import { supabase } from "../lib/supabase";
import { loadWorkspace } from "../lib/workspace";
import { ScreenTitle, baseStyles as b } from "../components/ui";

type Branding = { display_name:string;legal_name:string;rc_number:string;tax_number:string;address:string;phone:string;email:string;website:string;primary_color:string;secondary_color:string;report_footer:string;logo_path:string|null;letterhead_header_path:string|null;letterhead_footer_path:string|null };
const empty:Branding={display_name:"",legal_name:"",rc_number:"",tax_number:"",address:"",phone:"",email:"",website:"",primary_color:"#073F65",secondary_color:"#0B8B64",report_footer:"",logo_path:null,letterhead_header_path:null,letterhead_footer_path:null};

export default function CompanyBrandingScreen(){
  const [companyId,setCompanyId]=useState("");const [form,setForm]=useState<Branding>(empty);const [previews,setPreviews]=useState<Record<string,string>>({});const [busy,setBusy]=useState(false);
  useEffect(()=>{(async()=>{try{const workspace=await loadWorkspace();if(!workspace.membership.is_owner){router.back();return}setCompanyId(workspace.membership.company_id);const {data}=await supabase.from("company_branding").select("*").eq("company_id",workspace.membership.company_id).maybeSingle();const next={...empty,display_name:workspace.companyName,...(data??{})};setForm(next);const entries=[["logo",next.logo_path],["header",next.letterhead_header_path],["footer",next.letterhead_footer_path]].filter(([,path])=>path) as [string,string][];const signed=await Promise.all(entries.map(async([key,path])=>{const {data:url}=await supabase.storage.from("company-branding").createSignedUrl(path,3600);return[key,url?.signedUrl??""]}));setPreviews(Object.fromEntries(signed));}catch(e){Alert.alert("Could not load branding",e instanceof Error?e.message:"Try again")}})()},[]);
  function field(key:keyof Branding,value:string){setForm(current=>({...current,[key]:value}))}
  async function choose(kind:"logo"|"header"|"footer"){
    if(!companyId)return;const result=await DocumentPicker.getDocumentAsync({type:["image/png","image/jpeg","image/webp","image/svg+xml"],copyToCacheDirectory:true});if(result.canceled)return;const asset=result.assets[0];if(asset.size&&asset.size>5*1024*1024){Alert.alert("File too large","Choose an image no larger than 5 MB.");return}
    try{setBusy(true);const body=await (await fetch(asset.uri)).arrayBuffer();const safe=(asset.name||`${kind}.png`).toLowerCase().replace(/[^a-z0-9._-]+/g,"-");const path=`${companyId}/${kind}/${Date.now()}-${safe}`;const {error}=await supabase.storage.from("company-branding").upload(path,body,{contentType:asset.mimeType||"image/png",upsert:false});if(error)throw error;const key=kind==="logo"?"logo_path":kind==="header"?"letterhead_header_path":"letterhead_footer_path";field(key,path);setPreviews(current=>({...current,[kind]:asset.uri}));}catch(e){Alert.alert("Upload failed",e instanceof Error?e.message:"Try again")}finally{setBusy(false)}
  }
  async function save(){if(!companyId||!form.display_name.trim())return;setBusy(true);try{const {data:{user}}=await supabase.auth.getUser();const {error}=await supabase.from("company_branding").upsert({...form,company_id:companyId,onboarding_complete:true,updated_by:user?.id,updated_at:new Date().toISOString()},{onConflict:"company_id"});if(error)throw error;Alert.alert("Branding saved","New reports will carry your company identity.")}catch(e){Alert.alert("Could not save",e instanceof Error?e.message:"Try again")}finally{setBusy(false)}}
  return <SafeAreaView style={b.screen} edges={["top"]}><ScrollView contentContainerStyle={b.content}><View style={s.top}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹ Back</Text></Pressable></View><ScreenTitle eyebrow="COMPANY SETTINGS" title="Your report brand" subtitle="Upload your logo and letterhead once. Reports will carry your company identity, not the accounting app brand."/>
    <View style={s.card}><Text style={s.section}>COMPANY IDENTITY</Text><Field label="Display name" value={form.display_name} onChange={v=>field("display_name",v)}/><Field label="Registered / legal name" value={form.legal_name} onChange={v=>field("legal_name",v)}/><View style={s.row}><Field half label="RC number" value={form.rc_number} onChange={v=>field("rc_number",v)}/><Field half label="Tax number" value={form.tax_number} onChange={v=>field("tax_number",v)}/></View><Field label="Office address" value={form.address} onChange={v=>field("address",v)} multiline/><View style={s.row}><Field half label="Phone" value={form.phone} onChange={v=>field("phone",v)}/><Field half label="Email" value={form.email} onChange={v=>field("email",v)}/></View><Field label="Website" value={form.website} onChange={v=>field("website",v)}/></View>
    <View style={s.card}><Text style={s.section}>LOGO & LETTERHEAD</Text><Asset label="Company logo" preview={previews.logo} onPress={()=>choose("logo")}/><Asset label="Letterhead header" preview={previews.header} wide onPress={()=>choose("header")}/><Asset label="Letterhead footer" preview={previews.footer} wide onPress={()=>choose("footer")}/></View>
    <View style={s.card}><Text style={s.section}>REPORT STYLE</Text><View style={s.row}><Field half label="Primary colour" value={form.primary_color} onChange={v=>field("primary_color",v)}/><Field half label="Secondary colour" value={form.secondary_color} onChange={v=>field("secondary_color",v)}/></View><Field label="Report footer note" value={form.report_footer} onChange={v=>field("report_footer",v)} multiline/></View>
    <Pressable disabled={busy} onPress={save} style={[b.button,busy&&{opacity:.55}]}><Text style={b.buttonText}>{busy?"Saving…":"Save company branding"}</Text></Pressable>
  </ScrollView></SafeAreaView>
}
function Field({label,value,onChange,multiline,half}:{label:string;value:string;onChange:(value:string)=>void;multiline?:boolean;half?:boolean}){return <View style={half?s.half:undefined}><Text style={s.label}>{label}</Text><TextInput style={[s.input,multiline&&s.multiline]} value={value??""} onChangeText={onChange} multiline={multiline} placeholderTextColor="#9aa8b2"/></View>}
function Asset({label,preview,wide,onPress}:{label:string;preview?:string;wide?:boolean;onPress:()=>void}){return <Pressable style={s.asset} onPress={onPress}>{preview?<Image source={{uri:preview}} resizeMode="contain" style={[s.assetImage,wide&&s.assetWide]}/>:<View style={[s.assetImage,s.placeholder,wide&&s.assetWide]}><Text style={s.placeholderText}>{wide?"LETTERHEAD":"LOGO"}</Text></View>}<View style={{flex:1}}><Text style={s.assetLabel}>{label}</Text><Text style={s.assetNote}>Tap to choose image · max 5 MB</Text></View><Text style={s.chev}>›</Text></Pressable>}
const s=StyleSheet.create({top:{height:28,justifyContent:"center"},back:{fontSize:12,fontWeight:"900",color:"#0b5f91"},card:{backgroundColor:"white",borderWidth:1,borderColor:"#dfe7ed",borderRadius:18,padding:14,gap:11},section:{fontSize:8,fontWeight:"900",letterSpacing:1.3,color:"#0b8b64"},row:{flexDirection:"row",gap:9},half:{flex:1},label:{fontSize:9,fontWeight:"800",color:"#587080",marginBottom:5},input:{minHeight:42,borderWidth:1,borderColor:"#d7e2e9",borderRadius:11,paddingHorizontal:11,color:"#15394f",fontSize:12,backgroundColor:"#fbfcfd"},multiline:{minHeight:76,paddingTop:10,textAlignVertical:"top"},asset:{flexDirection:"row",alignItems:"center",gap:10,borderBottomWidth:1,borderBottomColor:"#edf1f3",paddingBottom:10},assetImage:{width:58,height:58,borderRadius:8,backgroundColor:"#f0f4f6"},assetWide:{width:100,height:58},placeholder:{alignItems:"center",justifyContent:"center"},placeholderText:{fontSize:7,letterSpacing:1,color:"#91a1ab",fontWeight:"900"},assetLabel:{fontSize:11,fontWeight:"900",color:"#183c54"},assetNote:{fontSize:8,color:"#82929d",marginTop:3},chev:{fontSize:22,color:"#7c929f"}});
