import { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import { loadEstimateReviewSession } from "../lib/estimate-review-session";
import { buildBoqWorkingSummary } from "../lib/boq-working-summary";
import type { MobileEstimateReviewSession } from "../lib/estimate-types";

const money=(value:number,code="NGN")=>new Intl.NumberFormat("en-NG",{style:"currency",currency:code,maximumFractionDigits:0}).format(value||0);

export default function EstimateSummary(){
  const [session,setSession]=useState<MobileEstimateReviewSession|null>(null);
  const [loading,setLoading]=useState(true);
  useEffect(()=>{loadEstimateReviewSession().then(setSession).finally(()=>setLoading(false));},[]);
  const summary=useMemo(()=>session?buildBoqWorkingSummary({boq:session.boq,rates:session.rates,rateSources:session.rateSources,preliminariesPricing:session.preliminariesPricing}):null,[session]);

  if(loading)return <SafeAreaView style={s.safe}><View style={s.center}><ActivityIndicator size="large" color="#073f65"/></View></SafeAreaView>;
  if(!session||!summary)return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><View style={s.hero}><Text style={s.eye}>ESTIMATE</Text><Text style={s.title}>No BOQ loaded</Text><Text style={s.sub}>Upload a BOQ first. Charismak will preserve the source bill before any later analysis.</Text></View><Pressable style={s.primary} onPress={()=>router.replace("/upload-boq")}><Text style={s.primaryText}>Upload BOQ</Text></Pressable></ScrollView></SafeAreaView>;

  return <SafeAreaView style={s.safe} edges={["top"]}><ScrollView contentContainerStyle={s.page}>
    <View style={s.top}><Pressable onPress={()=>router.back()}><Text style={s.back}>← Estimate</Text></Pressable><Text style={s.brand}>CHARISMAK APP</Text></View>
    <View style={s.hero}><Text style={s.eye}>BOQ SUMMARY</Text><Text style={s.title}>{session.boq.name}</Text><Text style={s.sub}>Measured work uses quantity and rate. Preliminaries keep fixed and time-related planning costs separate. This is not yet an accounting record or final contract value.</Text></View>

    <View style={s.grid}><Metric label="Sections" value={String(session.boq.sections.length)}/><Metric label="Primary items" value={String(summary.lines.length)}/><Metric label="Preliminaries" value={String(summary.preliminaryItems)}/><Metric label="Unpriced" value={String(summary.unpricedItems)} warn={summary.unpricedItems>0}/></View>

    <View style={s.totalCard}><View><Text style={s.totalLabel}>PRICED / PLANNING TOTAL</Text><Text style={s.total}>{money(summary.pricedTotal,summary.currency)}</Text></View><View style={s.divider}/><View><Text style={s.totalLabel}>WORKING TOTAL</Text><Text style={s.total}>{money(summary.workingTotal,summary.currency)}</Text></View>{summary.derivedPreliminaryTotals>0&&<Text style={s.note}>{summary.derivedPreliminaryTotals} preliminary total{summary.derivedPreliminaryTotals===1?" is":"s are"} derived from Fixed + Time-Related charges for budgeting while preserving both components.</Text>}</View>

    {(summary.unpricedItems>0||summary.arithmeticMismatchItems>0)&&<View style={s.warn}><Text style={s.warnTitle}>The BOQ can still be used.</Text><Text style={s.warnCopy}>{summary.unpricedItems?`${summary.unpricedItems} genuinely unpriced item${summary.unpricedItems===1?" remains":"s remain"}. `:""}{summary.arithmeticMismatchItems?`${summary.arithmeticMismatchItems} measured-work arithmetic mismatch${summary.arithmeticMismatchItems===1?" remains":"es remain"}. `:""}Fixed-only and time-related-only preliminary items are valid priced planning items.</Text></View>}

    <Text style={s.sectionHead}>Sections</Text>
    {session.boq.sections.map(section=>{const lines=summary.lines.filter(line=>line.sectionId===section.id);const sectionTotal=lines.reduce((sum,line)=>sum+(line.amount??0),0);const prelims=lines.filter(line=>line.kind==="preliminary").length;const issues=lines.filter(line=>line.amount==null||line.sourceArithmeticMismatch).length;return <View key={section.id} style={s.section}><View style={{flex:1}}><Text style={s.sectionTitle}>{section.title}</Text><Text style={s.sectionMeta}>{lines.length} item{lines.length===1?"":"s"}{prelims?` · ${prelims} preliminar${prelims===1?"y":"ies"}`:""}{issues?` · ${issues} exception${issues===1?"":"s"}`:""}</Text></View><Text style={s.sectionAmount}>{money(sectionTotal,summary.currency)}</Text></View>})}

    <View style={s.rule}><Text style={s.ruleTitle}>What happens next?</Text><Text style={s.ruleCopy}>If this BOQ belongs to a live job, create or open the Project and upload it from inside that Project. Materials, procurement and Money stay separate so planning assumptions do not become actual costs by accident.</Text></View>
    <View style={s.actions}><Pressable style={s.primary} onPress={()=>router.replace("/upload-boq")}><Text style={s.primaryText}>Upload another BOQ</Text></Pressable><Pressable style={s.secondary} onPress={()=>router.push("/new-project")}><Text style={s.secondaryText}>Create project</Text></Pressable></View>
  </ScrollView></SafeAreaView>;
}

function Metric({label,value,warn}:{label:string;value:string;warn?:boolean}){return <View style={s.metric}><Text style={s.metricLabel}>{label}</Text><Text style={[s.metricValue,warn&&s.metricWarn]}>{value}</Text></View>}

const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#f3f7fa"},page:{padding:16,paddingBottom:70,gap:14},center:{flex:1,alignItems:"center",justifyContent:"center"},top:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},back:{fontSize:14,fontWeight:"800",color:"#0b5f91",fontFamily:"sans-serif"},brand:{fontSize:11,fontWeight:"900",letterSpacing:1,color:"#748795",fontFamily:"sans-serif"},hero:{backgroundColor:"#082945",borderRadius:20,padding:19,gap:7},eye:{fontSize:11,fontWeight:"900",letterSpacing:1.2,color:"#9ec5df",fontFamily:"sans-serif"},title:{fontSize:26,fontWeight:"900",color:"#fff",fontFamily:"sans-serif"},sub:{fontSize:14,lineHeight:21,color:"#d7e5ef",fontFamily:"sans-serif"},grid:{flexDirection:"row",flexWrap:"wrap",gap:8},metric:{width:"48.5%",backgroundColor:"#fff",borderWidth:1,borderColor:"#dce6ec",borderRadius:14,padding:13},metricLabel:{fontSize:12,color:"#738693",fontFamily:"sans-serif"},metricValue:{fontSize:22,fontWeight:"900",color:"#173f5a",marginTop:4,fontFamily:"sans-serif"},metricWarn:{color:"#9a6200"},totalCard:{backgroundColor:"#fff",borderWidth:1,borderColor:"#dce6ec",borderRadius:17,padding:15,gap:12},totalLabel:{fontSize:11,fontWeight:"900",letterSpacing:.7,color:"#748795",fontFamily:"sans-serif"},total:{fontSize:23,fontWeight:"900",color:"#0a4f76",marginTop:4,fontFamily:"sans-serif"},divider:{height:1,backgroundColor:"#e5ecef"},note:{fontSize:12,lineHeight:18,color:"#657b89",fontFamily:"sans-serif"},warn:{backgroundColor:"#fff4ce",borderRadius:14,padding:14},warnTitle:{fontSize:15,fontWeight:"900",color:"#79560f",fontFamily:"sans-serif"},warnCopy:{fontSize:13,lineHeight:20,color:"#775f25",marginTop:4,fontFamily:"sans-serif"},sectionHead:{fontSize:20,fontWeight:"900",color:"#173f5a",fontFamily:"sans-serif"},section:{backgroundColor:"#fff",borderWidth:1,borderColor:"#dce6ec",borderRadius:14,padding:14,flexDirection:"row",gap:12,alignItems:"center"},sectionTitle:{fontSize:15,fontWeight:"900",color:"#24485f",fontFamily:"sans-serif"},sectionMeta:{fontSize:12,lineHeight:18,color:"#748795",marginTop:4,fontFamily:"sans-serif"},sectionAmount:{fontSize:15,fontWeight:"900",color:"#0a5a83",fontFamily:"sans-serif"},rule:{backgroundColor:"#eef6fa",borderRadius:15,padding:14},ruleTitle:{fontSize:15,fontWeight:"900",color:"#173f5a",fontFamily:"sans-serif"},ruleCopy:{fontSize:13,lineHeight:20,color:"#617787",marginTop:4,fontFamily:"sans-serif"},actions:{flexDirection:"row",gap:9},primary:{flex:1,minHeight:52,backgroundColor:"#073f65",borderRadius:13,alignItems:"center",justifyContent:"center",paddingHorizontal:10},primaryText:{fontSize:14,fontWeight:"900",color:"#fff",fontFamily:"sans-serif"},secondary:{flex:1,minHeight:52,borderWidth:1,borderColor:"#cbdbe5",backgroundColor:"#fff",borderRadius:13,alignItems:"center",justifyContent:"center",paddingHorizontal:10},secondaryText:{fontSize:14,fontWeight:"900",color:"#0b5f91",fontFamily:"sans-serif"}});