import { useState } from "react";
import { Alert, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import { supabase } from "../lib/supabase";

export default function Login(){
  const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [busy,setBusy]=useState(false);
  async function signIn(){setBusy(true);const {error}=await supabase.auth.signInWithPassword({email:email.trim(),password});setBusy(false);if(error)return Alert.alert("Sign in failed",error.message);router.replace("/(tabs)")}
  return <SafeAreaView style={s.safe}><KeyboardAvoidingView behavior={Platform.OS==="ios"?"padding":undefined} style={s.wrap}><View style={s.logo}><View style={s.mark}><Text style={s.markText}>A</Text></View><View><Text style={s.brand}>Charismak Accounting</Text><Text style={s.tag}>Track the truth. Every movement. Every project.</Text></View></View><View style={s.card}><Text style={s.title}>Welcome back</Text><Text style={s.copy}>Sign in to your company workspace.</Text><Text style={s.label}>Email</Text><TextInput style={s.input} autoCapitalize="none" keyboardType="email-address" value={email} onChangeText={setEmail}/><Text style={s.label}>Password</Text><TextInput style={s.input} secureTextEntry value={password} onChangeText={setPassword}/><Pressable disabled={busy||!email||!password} style={[s.button,(busy||!email||!password)&&s.disabled]} onPress={signIn}><Text style={s.buttonText}>{busy?"Signing in…":"Sign in"}</Text></Pressable></View></KeyboardAvoidingView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#f2f6fa"},wrap:{flex:1,justifyContent:"center",padding:22,gap:18},logo:{flexDirection:"row",alignItems:"center",gap:10},mark:{width:46,height:46,borderRadius:16,backgroundColor:"#073f65",alignItems:"center",justifyContent:"center"},markText:{color:"white",fontWeight:"900",fontSize:20},brand:{fontSize:20,fontWeight:"800",color:"#0d2f49"},tag:{fontSize:11,color:"#708192",marginTop:2},card:{backgroundColor:"white",borderRadius:22,padding:18,gap:8,shadowColor:"#17384f",shadowOpacity:.08,shadowRadius:20,elevation:3},title:{fontSize:26,fontWeight:"800",color:"#0c2e47"},copy:{fontSize:13,color:"#768695",marginBottom:8},label:{fontSize:11,fontWeight:"700",color:"#486174",marginTop:4},input:{height:48,borderWidth:1,borderColor:"#d5e0e8",borderRadius:13,paddingHorizontal:13,fontSize:15,backgroundColor:"#fff"},button:{height:50,borderRadius:14,backgroundColor:"#073f65",alignItems:"center",justifyContent:"center",marginTop:10},buttonText:{color:"white",fontWeight:"900"},disabled:{opacity:.45}});
