import { useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import { supabase } from "../lib/supabase";
import { loadWorkspace } from "../lib/workspace";
import { baseStyles as b, Card, ScreenTitle, palette } from "../components/ui";
import { readableError } from "../lib/mobile-error";
const uniqueKeywords=(values:string[])=>Array.from(new Set(values.map(v=>v.trim()).filter(Boolean)));
export default function NewProject(){
  const[name,setName]=useState(""),[location,setLocation]=useState(""),[code,setCode]=useState(""),[client,setClient]=useState(""),[contract,setContract]=useState(""),[busy,setBusy]=useState(false);
  async function create(){
    if(!name.trim()||!location.trim())return Alert.alert("Project details","Project name and location are required.");
    const contractValue=contract.trim()?Number(contract.replace(/,/g,"")):null;if(contractValue!==null&&(!Number.isFinite(contractValue)||contractValue<0))return Alert.alert("Contract value","Enter a valid amount or leave it blank.");
    setBusy(true);try{const w=await loadWorkspace();const role=String(w.membership.role||"").toLowerCase();if(role!=="md"&&role!=="owner")throw new Error("Only the MD can create a live project right now.");const projectName=name.trim(),projectCode=code.trim().toUpperCase()||null,clientName=client.trim()||null,projectLocation=location.trim();const{data:p,error}=await supabase.from("projects").insert({company_id:w.membership.company_id,project_code:projectCode,name:projectName,location:projectLocation,status:"active",reported_progress:0,contract_value:contractValue,created_by:w.user.id,client_name:clientName,import_keywords:uniqueKeywords([projectName,projectCode||"",clientName||""])}).select("id").single();if(error)throw error;router.replace({pathname:"/project/[id]",params:{id:p.id}})}catch(e){Alert.alert("Could not create project",readableError(e))}finally{setBusy(false)}
  }
  return <SafeAreaView style={b.screen} edges={["top"]}><ScrollView contentContainerStyle={b.content} keyboardShouldPersistTaps="handled"><Pressable onPress={()=>router.back()}><Text style={s.back}>← Back</Text></Pressable><ScreenTitle eyebrow="NEW PROJECT" title="Create the job" subtitle="Start with the facts needed for job-cost accounting. You can leave contract value blank until it is known."/><Card style={s.form}><Field label="Project name" value={name} onChange={setName} placeholder="e.g. Jahi Residence"/><Field label="Location" value={location} onChange={setLocation} placeholder="e.g. Jahi, Abuja"/><Field label="Project code (optional)" value={code} onChange={setCode} placeholder="e.g. JAHI-01" caps/><Field label="Client (optional)" value={client} onChange={setClient} placeholder="Client or employer"/><Field label="Contract value (optional)" value={contract} onChange={setContract} placeholder="0" keyboard="decimal-pad"/><View style={s.note}><Text style={s.noteTitle}>Do not invent a contract value.</Text><Text style={s.noteCopy}>If it is not confirmed yet, leave it blank. Money received and money spent can still be recorded accurately.</Text></View><Pressable disabled={busy} onPress={create} style={[s.button,busy&&{opacity:.5}]}><Text style={s.buttonText}>{busy?"Creating…":"Create project"}</Text></Pressable></Card></ScrollView></SafeAreaView>}
function Field({label,value,onChange,placeholder,caps,keyboard="default"}:{label:string;value:string;onChange:(v:string)=>void;placeholder:string;caps?:boolean;keyboard?:"default"|"decimal-pad"}){return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={onChange} placeholder={placeholder} autoCapitalize={caps?"characters":"words"} keyboardType={keyboard} style={s.input}/></View>}
const s=StyleSheet.create({back:{fontSize:15,fontWeight:"800",color:palette.navy,fontFamily:"sans-serif"},form:{gap:15},field:{gap:7},label:{fontSize:14,fontWeight:"800",color:"#3e5a6d",fontFamily:"sans-serif"},input:{minHeight:56,borderWidth:1,borderColor:"#cfdae2",borderRadius:14,paddingHorizontal:14,fontSize:17,color:palette.ink,backgroundColor:"#fff",fontFamily:"sans-serif"},note:{backgroundColor:"#f1f7fa",borderRadius:14,padding:14},noteTitle:{fontSize:15,fontWeight:"900",color:palette.ink,fontFamily:"sans-serif"},noteCopy:{fontSize:13,lineHeight:20,color:palette.muted,marginTop:4,fontFamily:"sans-serif"},button:{minHeight:56,borderRadius:14,backgroundColor:palette.navy,alignItems:"center",justifyContent:"center"},buttonText:{fontSize:16,fontWeight:"900",color:"#fff",fontFamily:"sans-serif"}});