import { useCallback, useMemo, useState } from "react";
import { ActivityIndicator, Alert, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useFocusEffect } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import { supabase } from "../lib/supabase";
import { loadWorkspace } from "../lib/workspace";
import { baseStyles as b, Card, ScreenTitle, SectionHead } from "../components/ui";

const roles=[
  {code:"MD_OWNER",label:"MD / Owner"},
  {code:"CFO",label:"Accountant / CFO"},
  {code:"PROJECT_DIRECTOR",label:"Project Director"},
  {code:"PROJECT_MANAGER",label:"Project / Construction Manager"},
] as const;

export default function PeopleAccess(){
  const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [workspace,setWorkspace]=useState<any>(null);const [roster,setRoster]=useState<any>({role_emails:[],members:[],projects:[],positions:[]});const [drafts,setDrafts]=useState<Record<string,string>>({});const [busy,setBusy]=useState("");
  const load=useCallback(async()=>{const w=await loadWorkspace();setWorkspace(w);if(!w.membership.is_owner){setLoading(false);setRefreshing(false);return}const {data,error}=await supabase.rpc("company_access_roster",{target_company:w.membership.company_id});if(error)throw error;const r=data??{role_emails:[],members:[],projects:[],positions:[]};setRoster(r);const map:Record<string,string>={};for(const role of roles){const found=(r.role_emails??[]).find((x:any)=>x.position_code===role.code);map[role.code]=found?.email??(role.code==="MD_OWNER"?w.user.email:"")}setDrafts(map);setLoading(false);setRefreshing(false)},[]);
  useFocusEffect(useCallback(()=>{load().catch(e=>{Alert.alert("Could not load access",e instanceof Error?e.message:"Try again");setLoading(false)})},[load]));
  const positionCodes=useMemo(()=>new Map((roster.positions??[]).map((p:any)=>[p.code,p])),[roster.positions]);
  async function saveAlias(code:string,label:string){if(!workspace||!drafts[code])return;setBusy(`alias-${code}`);const {error}=await supabase.rpc("owner_save_role_email",{target_company:workspace.membership.company_id,target_position_code:code,target_email:drafts[code].trim().toLowerCase(),target_label:label});setBusy("");if(error)return Alert.alert("Could not save",error.message);await load()}
  async function setPosition(membershipId:string,positionCode:string){if(!workspace)return;setBusy(`pos-${membershipId}`);const {error}=await supabase.rpc("owner_set_member_position",{target_company:workspace.membership.company_id,target_membership:membershipId,target_position_code:positionCode});setBusy("");if(error)return Alert.alert("Could not change position",error.message);await load()}
  async function toggleProject(member:any,project:any){if(!workspace)return;const assignment=(member.projects??[]).find((p:any)=>p.project_id===project.id);setBusy(`project-${member.membership_id}-${project.id}`);const result=assignment?await supabase.rpc("owner_remove_project_access",{target_company:workspace.membership.company_id,target_assignment:assignment.assignment_id}):await supabase.rpc("owner_assign_project_access",{target_company:workspace.membership.company_id,target_membership:member.membership_id,target_project:project.id,target_role:"Assigned project team",view_cost:true,can_request:true,can_approve:false});setBusy("");if(result.error)return Alert.alert("Could not update project access",result.error.message);await load()}
  if(loading)return <SafeAreaView style={b.screen}><View style={s.center}><ActivityIndicator size="large" color="#073f65"/></View></SafeAreaView>;
  if(!workspace?.membership?.is_owner)return <SafeAreaView style={b.screen}><ScrollView contentContainerStyle={b.content}><ScreenTitle eyebrow="PEOPLE" title="People & Access" subtitle="Only the MD / Owner can administer company positions and project access."/><Card><Text style={b.muted}>Owner access required.</Text></Card></ScrollView></SafeAreaView>;
  return <SafeAreaView style={b.screen} edges={["top"]}><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);load()}}/>} contentContainerStyle={b.content} keyboardShouldPersistTaps="handled"><ScreenTitle eyebrow="MD CONTROL" title="People & Access" subtitle="Set role aliases, assign positions and control which projects each person can work on. MD remains company-wide."/>
    <SectionHead title="Position emails"/>{roles.map(role=><Card key={role.code}><Text style={s.label}>{role.label}</Text><TextInput editable={role.code!=="MD_OWNER"} autoCapitalize="none" keyboardType="email-address" value={drafts[role.code]??""} onChangeText={v=>setDrafts(x=>({...x,[role.code]:v}))} placeholder="role@company.com" style={[s.input,role.code==="MD_OWNER"&&s.disabled]}/><Pressable disabled={busy===`alias-${role.code}`||role.code==="MD_OWNER"} style={[s.smallButton,(busy===`alias-${role.code}`||role.code==="MD_OWNER")&&{opacity:.45}]} onPress={()=>saveAlias(role.code,role.label)}><Text style={s.smallButtonText}>{role.code==="MD_OWNER"?"Owner account":"Save alias"}</Text></Pressable></Card>)}
    <SectionHead title="Members & access"/>{(roster.members??[]).map((member:any)=>{const primary=(member.positions??[]).find((p:any)=>p.is_primary)??(member.positions??[])[0];return <Card key={member.membership_id}><View style={b.row}><View style={{flex:1}}><Text style={s.member}>{member.email}</Text><Text style={s.note}>{member.is_owner?"Owner · all projects":primary?.name??"No position"}</Text></View><Text style={s.status}>{member.status}</Text></View>{!member.is_owner&&<><Text style={s.subhead}>POSITION</Text><View style={s.chips}>{roles.filter(r=>r.code!=="MD_OWNER").map(r=><Pressable key={r.code} disabled={busy===`pos-${member.membership_id}`} onPress={()=>setPosition(member.membership_id,r.code)} style={[s.chip,primary?.code===r.code&&s.chipActive]}><Text style={[s.chipText,primary?.code===r.code&&s.chipTextActive]}>{r.label}</Text></Pressable>)}</View><Text style={s.subhead}>PROJECT ACCESS</Text><View style={s.chips}>{(roster.projects??[]).map((p:any)=>{const assigned=(member.projects??[]).some((x:any)=>x.project_id===p.id);return <Pressable key={p.id} disabled={busy===`project-${member.membership_id}-${p.id}`} onPress={()=>toggleProject(member,p)} style={[s.chip,assigned&&s.projectActive]}><Text style={[s.chipText,assigned&&s.chipTextActive]}>{assigned?"✓ ":""}{p.project_code}</Text></Pressable>})}</View></>}</Card>})}
  </ScrollView></SafeAreaView>
}
const s=StyleSheet.create({center:{flex:1,alignItems:"center",justifyContent:"center"},label:{fontSize:12,fontWeight:"900",color:"#173a53"},input:{height:44,borderWidth:1,borderColor:"#d9e4eb",borderRadius:12,paddingHorizontal:11,fontSize:11,color:"#173a53",marginTop:9},disabled:{backgroundColor:"#f1f5f7",color:"#7e8d97"},smallButton:{height:38,borderRadius:11,backgroundColor:"#073f65",alignItems:"center",justifyContent:"center",marginTop:8},smallButtonText:{fontSize:10,fontWeight:"900",color:"white"},member:{fontSize:12,fontWeight:"900",color:"#173a53"},note:{fontSize:9,color:"#7a8b98",marginTop:3},status:{fontSize:8,fontWeight:"900",textTransform:"uppercase",color:"#11815e"},subhead:{fontSize:8,fontWeight:"900",letterSpacing:1,color:"#7c8d99",marginTop:13,marginBottom:7},chips:{flexDirection:"row",flexWrap:"wrap",gap:6},chip:{borderWidth:1,borderColor:"#d7e2e9",borderRadius:999,paddingHorizontal:10,paddingVertical:7,backgroundColor:"#fff"},chipActive:{backgroundColor:"#073f65",borderColor:"#073f65"},projectActive:{backgroundColor:"#16825c",borderColor:"#16825c"},chipText:{fontSize:8,fontWeight:"800",color:"#405b6d"},chipTextActive:{color:"white"}});
