import { useCallback, useState } from "react";
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from "react-native";
import { router, useFocusEffect } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import { supabase } from "../lib/supabase";
import { loadWorkspace } from "../lib/workspace";
import { Card, ScreenTitle, SectionHead, baseStyles as b } from "../components/ui";

type Decision={id:string;kind:"statement"|"document"|"intake";title:string;note:string;count?:number;projectId?:string;statementId?:string};

export default function Review(){
  const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [rows,setRows]=useState<Decision[]>([]);
  const load=useCallback(async()=>{const w=await loadWorkspace();const [{data:statements},{data:docs},{data:intake}]=await Promise.all([
    supabase.from("statement_imports").select("id,detected_institution_name,detected_account_name,rows_pending_review,status,created_at").eq("company_id",w.membership.company_id).gt("rows_pending_review",0).order("created_at",{ascending:false}).limit(50),
    supabase.from("project_document_intelligence").select("id,document_id,project_id,detected_subtype,confidence,title,created_at,project:projects(name,project_code),document:source_documents(file_name)").eq("company_id",w.membership.company_id).eq("review_status","pending").order("created_at",{ascending:false}).limit(100),
    supabase.from("intake_items").select("id,document_id,detected_type,detected_project_id,confidence,status,message,created_at,document:source_documents(file_name),project:projects(name,project_code)").eq("company_id",w.membership.company_id).in("status",["needs_review","failed"]).order("created_at",{ascending:false}).limit(100),
  ]);const docIds=new Set((docs??[]).map((d:any)=>d.document_id));const out:Decision[]=[];for(const s of statements??[])out.push({id:`s-${s.id}`,kind:"statement",title:s.detected_institution_name||"Bank statement",note:`${s.detected_account_name||"Account"} · ${s.rows_pending_review||0} movement(s) need a decision`,count:Number(s.rows_pending_review||0),statementId:s.id});for(const d of docs??[]){const p:any=Array.isArray(d.project)?d.project[0]:d.project;const f:any=Array.isArray(d.document)?d.document[0]:d.document;out.push({id:`d-${d.id}`,kind:"document",title:d.title||f?.file_name||"Project document",note:`${p?`${p.project_code} · ${p.name} · `:""}${String(d.detected_subtype||"document").replaceAll("_"," ")} · ${Math.round(Number(d.confidence||0))}% confidence`,projectId:d.project_id})}for(const r of intake??[]){if(docIds.has(r.document_id))continue;const p:any=Array.isArray(r.project)?r.project[0]:r.project;const f:any=Array.isArray(r.document)?r.document[0]:r.document;out.push({id:`i-${r.id}`,kind:"intake",title:f?.file_name||String(r.detected_type||"Uploaded record").replaceAll("_"," "),note:`${p?`${p.project_code} · ${p.name} · `:""}${r.message||"Needs one confirmation"}`,projectId:r.detected_project_id||undefined})}setRows(out);setLoading(false);setRefreshing(false)},[]);useFocusEffect(useCallback(()=>{load().catch(()=>setLoading(false))},[load]));
  if(loading)return <SafeAreaView style={b.screen}><View style={s.center}><ActivityIndicator size="large" color="#073f65"/></View></SafeAreaView>;
  function open(r:Decision){if(r.statementId)router.push({pathname:"/statement/[id]",params:{id:r.statementId}});else if(r.projectId)router.push({pathname:"/project/[id]",params:{id:r.projectId}});else router.push("/(tabs)/add")}
  return <SafeAreaView style={b.screen} edges={["top"]}><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);load()}}/>} contentContainerStyle={b.content}><ScreenTitle eyebrow="REVIEW" title={rows.length?`${rows.length} item${rows.length===1?"":"s"} need your decision`:"Nothing needs your help"} subtitle="Confident records are handled automatically. Only exceptions appear here."/>{!rows.length&&<Card><Text style={s.clear}>You're clear.</Text><Text style={s.note}>New statements, project documents or uploaded records that need your input will appear here.</Text></Card>}{rows.length>0&&<SectionHead title="Needs your decision"/>}{rows.map(r=><Pressable key={r.id} onPress={()=>open(r)}><Card style={s.card}><View style={s.kind}><Text style={s.kindText}>{r.kind==="statement"?"MONEY":r.kind==="document"?"PROJECT":"RECORD"}</Text></View><View style={{flex:1}}><Text style={s.title}>{r.title}</Text><Text style={s.note}>{r.note}</Text></View><Text style={s.chev}>›</Text></Card></Pressable>)}</ScrollView></SafeAreaView>
}
const s=StyleSheet.create({center:{flex:1,alignItems:"center",justifyContent:"center"},card:{flexDirection:"row",alignItems:"center",gap:11},kind:{minWidth:48,height:30,borderRadius:10,backgroundColor:"#eaf2f7",alignItems:"center",justifyContent:"center",paddingHorizontal:7},kindText:{fontSize:7,fontWeight:"900",color:"#0a527d"},title:{fontSize:12,fontWeight:"900",color:"#173b55"},note:{fontSize:9,color:"#788a97",marginTop:3,lineHeight:13},chev:{fontSize:23,color:"#8296a4"},clear:{fontSize:16,fontWeight:"900",color:"#127a59"}});
