import { useCallback, useState } from "react";
import { ActivityIndicator, Alert, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useFocusEffect } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import { supabase } from "../lib/supabase";
import { loadWorkspace } from "../lib/workspace";
import { Card, ScreenTitle, SectionHead, baseStyles as b, money } from "../components/ui";

export default function Treasury(){
  const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [accounts,setAccounts]=useState<any[]>([]);const [projects,setProjects]=useState<any[]>([]);const [transfers,setTransfers]=useState<any[]>([]);const [amount,setAmount]=useState("");const [fromAccount,setFromAccount]=useState("");const [toAccount,setToAccount]=useState("");const [fromProject,setFromProject]=useState("");const [toProject,setToProject]=useState("");const [note,setNote]=useState("");const [busy,setBusy]=useState(false);const [companyId,setCompanyId]=useState("");
  const load=useCallback(async()=>{const w=await loadWorkspace();setCompanyId(w.membership.company_id);const [{data:a},{data:p},{data:t}]=await Promise.all([
    supabase.from("financial_accounts").select("id,institution_name,account_name,account_type,current_balance,balance_as_of").eq("company_id",w.membership.company_id).eq("is_active",true).order("institution_name"),
    supabase.from("projects").select("id,project_code,name").eq("company_id",w.membership.company_id).neq("status","archived").order("name"),
    supabase.from("transfer_pairs").select("id,transfer_date,amount,status,creates_due_to_from,from_project:projects!transfer_pairs_from_project_id_fkey(project_code,name),to_project:projects!transfer_pairs_to_project_id_fkey(project_code,name),from_account:financial_accounts!transfer_pairs_from_account_id_fkey(account_name,institution_name),to_account:financial_accounts!transfer_pairs_to_account_id_fkey(account_name,institution_name)").eq("company_id",w.membership.company_id).order("transfer_date",{ascending:false}).limit(30),
  ]);setAccounts(a??[]);setProjects(p??[]);setTransfers(t??[]);setLoading(false);setRefreshing(false)},[]);useFocusEffect(useCallback(()=>{load().catch(()=>setLoading(false))},[load]));
  async function transfer(){const value=Number(amount);if(!Number.isFinite(value)||value<=0)return Alert.alert("Enter an amount");if(!fromAccount&&!toAccount)return Alert.alert("Choose at least one account");setBusy(true);try{const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Sign in again");const createsDue=Boolean(fromProject&&toProject&&fromProject!==toProject);const {data:t,error}=await supabase.from("transfer_pairs").insert({company_id:companyId,transfer_date:new Date().toISOString().slice(0,10),amount:value,from_account_id:fromAccount||null,to_account_id:toAccount||null,from_project_id:fromProject||null,to_project_id:toProject||null,status:"confirmed",creates_due_to_from:createsDue,confirmed_by:user.id,confirmed_at:new Date().toISOString()}).select("id").single();if(error)throw error;if(createsDue&&t){const {error:oe}=await supabase.from("inter_project_obligations").insert({company_id:companyId,creditor_project_id:fromProject,debtor_project_id:toProject,amount:value,source_transfer_id:t.id,description:note||"Internal transfer",status:"open"});if(oe)throw oe}setAmount("");setFromAccount("");setToAccount("");setFromProject("");setToProject("");setNote("");await load()}catch(e){Alert.alert("Could not record transfer",e instanceof Error?e.message:"Try again")}finally{setBusy(false)}}
  if(loading)return <SafeAreaView style={b.screen}><View style={s.center}><ActivityIndicator size="large" color="#073f65"/></View></SafeAreaView>;
  const total=accounts.reduce((a,r)=>a+Number(r.current_balance||0),0);
  return <SafeAreaView style={b.screen} edges={["top"]}><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);load()}}/>} contentContainerStyle={b.content}><ScreenTitle eyebrow="MONEY" title="Treasury" subtitle="See where company money sits and record internal movements without turning transfers into revenue or expense."/><Card style={s.total}><Text style={s.totalLabel}>Recorded bank / wallet cash</Text><Text style={s.totalValue}>{money(total)}</Text><Text style={s.totalNote}>{accounts.length} active account(s)</Text></Card><SectionHead title="Cash by bank / wallet"/>{accounts.map(a=><Card key={a.id} style={s.account}><View><Text style={s.accountName}>{a.institution_name||a.account_name}</Text><Text style={s.note}>{a.account_name} · {String(a.account_type).replaceAll("_"," ")}</Text></View><View style={{alignItems:"flex-end"}}><Text style={s.accountValue}>{a.current_balance==null?"Balance pending":money(a.current_balance)}</Text>{a.balance_as_of&&<Text style={s.note}>as at {a.balance_as_of}</Text>}</View></Card>)}
    <SectionHead title="Record internal transfer"/><Card style={{gap:9}}><Text style={s.label}>Amount</Text><TextInput value={amount} onChangeText={setAmount} keyboardType="decimal-pad" placeholder="0.00" style={s.input}/><Text style={s.label}>From account</Text><ChoiceList rows={accounts} selected={fromAccount} onChange={setFromAccount} render={(r:any)=>r.institution_name||r.account_name}/><Text style={s.label}>To account</Text><ChoiceList rows={accounts} selected={toAccount} onChange={setToAccount} render={(r:any)=>r.institution_name||r.account_name}/><Text style={s.label}>From project <Text style={s.optional}>(optional)</Text></Text><ChoiceList rows={projects} selected={fromProject} onChange={setFromProject} render={(r:any)=>`${r.project_code} · ${r.name}`}/><Text style={s.label}>To project <Text style={s.optional}>(optional)</Text></Text><ChoiceList rows={projects} selected={toProject} onChange={setToProject} render={(r:any)=>`${r.project_code} · ${r.name}`}/><Text style={s.label}>Why was it moved? <Text style={s.optional}>(optional)</Text></Text><TextInput value={note} onChangeText={setNote} placeholder="Loan to project, cash movement…" style={s.input}/><Pressable disabled={busy} onPress={transfer} style={[b.button,busy&&{opacity:.5}]}><Text style={b.buttonText}>{busy?"Recording…":"Record transfer"}</Text></Pressable></Card>
    <SectionHead title="Recent internal movements"/>{transfers.map(t=>{const fa:any=Array.isArray(t.from_account)?t.from_account[0]:t.from_account;const ta:any=Array.isArray(t.to_account)?t.to_account[0]:t.to_account;const fp:any=Array.isArray(t.from_project)?t.from_project[0]:t.from_project;const tp:any=Array.isArray(t.to_project)?t.to_project[0]:t.to_project;return <Card key={t.id} style={s.account}><View style={{flex:1}}><Text style={s.accountName}>{fa?.institution_name||fa?.account_name||fp?.name||"Source"} → {ta?.institution_name||ta?.account_name||tp?.name||"Destination"}</Text><Text style={s.note}>{t.transfer_date} · {t.status}{t.creates_due_to_from?" · creates project obligation":""}</Text></View><Text style={s.accountValue}>{money(t.amount)}</Text></Card>})}</ScrollView></SafeAreaView>;
}
function ChoiceList({rows,selected,onChange,render}:{rows:any[];selected:string;onChange:(v:string)=>void;render:(r:any)=>string}){return <View style={s.choices}><Pressable onPress={()=>onChange("")} style={[s.choice,!selected&&s.choiceActive]}><Text style={[s.choiceText,!selected&&s.choiceActiveText]}>None</Text></Pressable>{rows.map(r=><Pressable key={r.id} onPress={()=>onChange(r.id)} style={[s.choice,selected===r.id&&s.choiceActive]}><Text style={[s.choiceText,selected===r.id&&s.choiceActiveText]}>{render(r)}</Text></Pressable>)}</View>}
const s=StyleSheet.create({center:{flex:1,alignItems:"center",justifyContent:"center"},total:{backgroundColor:"#0d8a63"},totalLabel:{fontSize:9,color:"#ccecdf"},totalValue:{fontSize:26,fontWeight:"900",color:"#fff",marginTop:4},totalNote:{fontSize:9,color:"#d7eee6",marginTop:4},account:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:10},accountName:{fontSize:11,fontWeight:"900",color:"#173b54"},accountValue:{fontSize:12,fontWeight:"900",color:"#0a527d"},note:{fontSize:8,color:"#7c8d98",marginTop:2},label:{fontSize:8,fontWeight:"900",color:"#657b8a"},optional:{fontWeight:"500",color:"#96a2ab"},input:{height:43,borderWidth:1,borderColor:"#d8e1e7",borderRadius:11,paddingHorizontal:10,fontSize:11,color:"#173b54",backgroundColor:"#fff"},choices:{flexDirection:"row",flexWrap:"wrap",gap:6},choice:{borderWidth:1,borderColor:"#dce5eb",borderRadius:10,paddingVertical:7,paddingHorizontal:8},choiceActive:{backgroundColor:"#073f65",borderColor:"#073f65"},choiceText:{fontSize:8,fontWeight:"800",color:"#3e5a6d"},choiceActiveText:{color:"#fff"}});
