"use client";

import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { COST_CODE_GROUPS } from "../../../../../lib/project-cost/cost-codes";
import { buildCommitmentForecastPosition, type ReviewedCommitment } from "../../../../../lib/project-cost/commitment-forecast-review";
import { approveCostToCompleteAction, saveCommitmentAction } from "./actions";

type ForecastLine = { costCode: string; amount: number; note?: string | null };

export default function CommitmentForecastReviewClient({ projectId, currency, initialCommitments, initialForecastLines, initialReviewedAt }:{
  projectId:string; currency:string; initialCommitments:ReviewedCommitment[]; initialForecastLines:ForecastLine[]; initialReviewedAt:string|null;
}){
  const router=useRouter();const [pending,startTransition]=useTransition();const [message,setMessage]=useState<string|null>(null);
  const [commitments,setCommitments]=useState(initialCommitments);
  const [description,setDescription]=useState("");const [costCode,setCostCode]=useState("04");const [committed,setCommitted]=useState("");const [paid,setPaid]=useState("0");const [status,setStatus]=useState<"open"|"closed"|"cancelled">("open");const [dueDate,setDueDate]=useState("");
  const [reviewedAt,setReviewedAt]=useState(initialReviewedAt?initialReviewedAt.slice(0,10):new Date().toISOString().slice(0,10));
  const [ctc,setCtc]=useState<Record<string,string>>(Object.fromEntries(initialForecastLines.map(line=>[line.costCode,String(line.amount)])));
  const snapshot=useMemo(()=>({projectId,reviewedAt:reviewedAt?`${reviewedAt}T12:00:00Z`:"",lines:COST_CODE_GROUPS.map(g=>({costCode:g.code,amount:Number(ctc[g.code]||0)}))}),[projectId,reviewedAt,ctc]);
  const position=useMemo(()=>buildCommitmentForecastPosition({projectId,commitments,snapshot}),[projectId,commitments,snapshot]);
  const money=(v:number)=>new Intl.NumberFormat("en-NG",{style:"currency",currency,maximumFractionDigits:0}).format(v);

  function addCommitment(){const committedAmount=Number(committed.replace(/,/g,""));const paidAmount=Number(paid.replace(/,/g,""));setMessage(null);startTransition(async()=>{const result=await saveCommitmentAction({projectId,costCode,description,committedAmount,paidAmount,status,dueDate:dueDate||null});if(!result.ok){setMessage(result.message);return;}setCommitments(rows=>[...rows,{id:result.id,projectId,description,costCode:costCode as any,committedAmount,paidAmount,status,dueDate:dueDate||null}]);setDescription("");setCommitted("");setPaid("0");setDueDate("");setMessage("Commitment saved. Future exposure uses only the unpaid balance.");router.refresh();});}
  function approveForecast(){setMessage(null);startTransition(async()=>{const result=await approveCostToCompleteAction({projectId,reviewedAt:reviewedAt?`${reviewedAt}T12:00:00Z`:"",lines:COST_CODE_GROUPS.map(g=>({costCode:g.code,amount:Number(ctc[g.code]||0)}))});if(!result.ok){setMessage(result.message);return;}setMessage("Cost-to-Complete review approved. Forecast Final Cost can now use Actual Spend + reviewed future cost without adding commitments twice.");router.refresh();});}

  return <div style={{display:"grid",gap:14}}>
    {message&&<section style={{background:message.includes("approved")||message.includes("saved")?"#e7f6ef":"#fff4ce",color:message.includes("approved")||message.includes("saved")?"#176247":"#775c18",borderRadius:10,padding:11,fontSize:10}}>{message}</section>}
    <section className="compact-card" style={{display:"grid",gap:10}}><small style={eye}>NEW COMMITMENT</small><h2 style={title}>Record agreed cost before it becomes a payment</h2><div style={grid}><Field label="Description" value={description} set={setDescription}/><Select label="Cost code" value={costCode} set={setCostCode} options={COST_CODE_GROUPS.map(g=>({value:g.code,label:`${g.code} · ${g.name}`}))}/><Field label="Committed amount" value={committed} set={setCommitted}/><Field label="Paid against commitment" value={paid} set={setPaid}/><Select label="Status" value={status} set={(v)=>setStatus(v as any)} options={[{value:"open",label:"Open"},{value:"closed",label:"Closed"},{value:"cancelled",label:"Cancelled"}]}/><Field label="Due date" value={dueDate} set={setDueDate} placeholder="YYYY-MM-DD"/></div><p style={copy}>Paid amount means the portion already represented in actual Money records. Only the unpaid balance is future exposure.</p><div><button type="button" disabled={pending||!description.trim()||!committed.trim()} onClick={addCommitment} style={{...primary,opacity:pending||!description.trim()||!committed.trim()?0.45:1}}>Save commitment</button></div></section>

    <section style={metrics}><Metric label="Committed" value={money(position.commitmentTotal)}/><Metric label="Already paid" value={money(position.paidAgainstCommitments)}/><Metric label="Still unpaid" value={money(position.unpaidCommitmentTotal)}/><Metric label="Draft future cost" value={position.costToCompleteTotal==null?"—":money(position.costToCompleteTotal)}/></section>

    <section className="compact-card"><small style={eye}>OPEN COMMITMENTS</small><h2 style={title}>{commitments.filter(c=>c.status!=="cancelled").length} reviewed commitment{commitments.filter(c=>c.status!=="cancelled").length===1?"":"s"}</h2>{position.commitments.length?position.commitments.map(row=><div key={row.id} style={rowStyle}><span><b>{row.costCode} · {row.description}</b><small style={sub}>{row.status} · committed {money(row.committedAmount)} · paid {money(row.paidAmount)}</small></span><strong>{money(row.unpaidAmount)} unpaid</strong></div>):<p style={copy}>No reviewed commitments yet.</p>}</section>

    <section className="compact-card" style={{display:"grid",gap:10}}><small style={eye}>COST-TO-COMPLETE REVIEW</small><h2 style={title}>What do we still expect to spend from this review date?</h2><p style={copy}>Enter the full expected future cost for each trade. This figure already includes unpaid commitments. Charismak will block a forecast that is below a known unpaid commitment balance.</p><label style={{display:"grid",gap:4,maxWidth:220}}><span style={label}>REVIEW DATE</span><input type="date" value={reviewedAt} onChange={e=>setReviewedAt(e.target.value)} style={input}/></label><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:10}}><thead><tr><th style={th}>Cost group</th><th style={{...th,textAlign:"right"}}>Unpaid commitments</th><th style={{...th,textAlign:"right"}}>Forecast CTC</th><th style={{...th,textAlign:"right"}}>Beyond commitments</th></tr></thead><tbody>{position.costToCompleteByCode.filter(r=>r.unpaidCommitments>0||Number(ctc[r.costCode]||0)>0).map(r=><tr key={r.costCode} style={{borderTop:"1px solid #e5ecef"}}><td style={td}><b>{r.costCode} · {r.name}</b></td><td style={{...td,textAlign:"right"}}>{money(r.unpaidCommitments)}</td><td style={{...td,textAlign:"right"}}><input value={ctc[r.costCode]??""} onChange={e=>setCtc(v=>({...v,[r.costCode]:e.target.value}))} inputMode="decimal" style={{...input,width:130,textAlign:"right"}}/></td><td style={{...td,textAlign:"right",color:r.status==="below_commitments"?"#a74335":"#35566b"}}>{r.headroomAfterCommitments==null?"—":money(r.headroomAfterCommitments)}</td></tr>)}</tbody></table></div>{position.issues.length>0&&<div style={warn}><b>Review needed:</b><ul style={{margin:"5px 0 0",paddingLeft:18}}>{position.issues.map(i=><li key={i}>{i}</li>)}</ul></div>}<div><button type="button" onClick={approveForecast} disabled={pending||!position.readyForForecast} style={{...primary,opacity:pending||!position.readyForForecast?0.45:1}}>Approve Cost-to-Complete</button></div></section>
  </div>;
}
function Field({label:lbl,value,set,placeholder}:{label:string;value:string;set:(v:string)=>void;placeholder?:string}){return <label style={{display:"grid",gap:4}}><span style={label}>{lbl.toUpperCase()}</span><input value={value} onChange={e=>set(e.target.value)} placeholder={placeholder} style={input}/></label>}
function Select({label:lbl,value,set,options}:{label:string;value:string;set:(v:string)=>void;options:Array<{value:string;label:string}>}){return <label style={{display:"grid",gap:4}}><span style={label}>{lbl.toUpperCase()}</span><select value={value} onChange={e=>set(e.target.value)} style={input}>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>}
function Metric({label:lbl,value}:{label:string;value:string}){return <div style={{border:"1px solid #dce6ec",borderRadius:11,padding:11,background:"#fff"}}><small style={{fontSize:7,color:"#718391"}}>{lbl.toUpperCase()}</small><b style={{display:"block",fontSize:13,color:"#173f5a",marginTop:3}}>{value}</b></div>}
const eye:React.CSSProperties={fontSize:8,fontWeight:900,letterSpacing:".1em",color:"#0b668f"};const title:React.CSSProperties={fontSize:15,color:"#173f5a",margin:"5px 0 4px"};const copy:React.CSSProperties={fontSize:9,lineHeight:1.5,color:"#718391",margin:0};const label:React.CSSProperties={fontSize:7,fontWeight:900,letterSpacing:".08em",color:"#6c7f8d"};const input:React.CSSProperties={border:"1px solid #cbd8e0",borderRadius:9,padding:"9px 10px",fontSize:10,color:"#173f5a",background:"#fff",boxSizing:"border-box"};const primary:React.CSSProperties={border:0,borderRadius:9,padding:"10px 13px",background:"#0b668f",color:"#fff",fontSize:9,fontWeight:900,cursor:"pointer"};const grid:React.CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:8};const metrics:React.CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(160px,1fr))",gap:8};const rowStyle:React.CSSProperties={display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",borderTop:"1px solid #e5ecef",padding:"9px 0",fontSize:10,color:"#35566b"};const sub:React.CSSProperties={display:"block",fontSize:8,fontWeight:400,color:"#7a8b97",marginTop:2};const warn:React.CSSProperties={background:"#fff4ce",borderRadius:10,padding:10,fontSize:9,lineHeight:1.5,color:"#775c18"};const th:React.CSSProperties={textAlign:"left",padding:"7px 6px",fontSize:8,color:"#6d7f8c"};const td:React.CSSProperties={padding:"8px 6px",color:"#35566b"};
