import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { buildCreateAppProjectFromEstimateRpcArgs, fingerprintAppProjectApproval, validateAppProjectApproval } from "../lib/project-cost/app-project-approval.ts";

const workspace={schemaVersion:1,workspaceId:"estimate:e1",sourceEstimateId:"e1",sourceSystem:"charismak_app_estimate",status:"reviewed_draft",reviewed:true,stagedAt:"2026-09-02T00:00:00Z",project:{name:"House",currency:"NGN",internalCostBudget:1050000,contractValue:1500000},commercialSnapshot:{directCost:1200000,contingency:60000,overhead:0,profit:240000,discount:0,subtotalBeforeTax:1500000,tax:0,grandTotal:1500000},internalDirectCost:1000000,clientSuppliedExcludedValue:200000,budgetLines:[{sourceLineId:"i1",itemNo:"4.1",description:"225mm blockwork",unit:"m2",quantity:100,rate:10000,amount:1000000,costCode:"04",supplyResponsibility:"contractor"}],budgetAllowances:[{sourceAllowanceId:"e1-contingency",kind:"contingency",description:"Reviewed internal contingency (5%)",amount:50000}],materials:[{material:"225mm hollow blocks",unit:"pcs",quantity:1050,sourceItems:[{sectionId:"section-04",itemId:"i1",description:"225mm blockwork",quantity:1050}]}],costGroups:[{costCode:"04",name:"Blockwork & Masonry",amount:1000000,lineCount:1}],forecastProfit:450000,budgetBaseline:{lineTotal:1000000,allowanceTotal:50000,internalBudget:1050000,reconciliationDifference:0},moneyConnection:{status:"not_linked",confirmedSpend:null,commitments:null,note:"Not linked"}};
const details={location:"Jahi, Abuja",projectCode:"JAH-01",clientName:"Client",projectType:"Residential",startDate:"2026-09-10",expectedEndDate:"2027-03-10",description:"Reviewed project"};

test("approval requires location and a reconciled reviewed workspace",()=>{assert.match(validateAppProjectApproval(workspace,{...details,location:""}).join(" "),/location/i);assert.equal(validateAppProjectApproval(workspace,details).length,0);const broken={...workspace,budgetBaseline:{...workspace.budgetBaseline,reconciliationDifference:100}};assert.match(validateAppProjectApproval(broken,details).join(" "),/reconcile/i);});

test("client or unknown responsibility cannot enter contractor budget baseline",()=>{const client={...workspace,budgetLines:[{...workspace.budgetLines[0],supplyResponsibility:"client"}]};assert.match(validateAppProjectApproval(client,details).join(" "),/contractor-side/i);const unknown={...workspace,budgetLines:[{...workspace.budgetLines[0],supplyResponsibility:"unknown"}]};assert.match(validateAppProjectApproval(unknown,details).join(" "),/contractor-side/i);});

test("builds deterministic live approval args without Money records",async()=>{const args=await buildCreateAppProjectFromEstimateRpcArgs({companyId:"11111111-1111-1111-1111-111111111111",workspace,details});assert.equal(args.project_location,"Jahi, Abuja");assert.equal(args.budget_direct_cost,1000000);assert.equal(args.budget_internal_cost,1050000);assert.equal(args.budget_lines[0].cost_code,"04");assert.equal(args.budget_materials[0].material,"225mm hollow blocks");assert.equal(args.budget_materials[0].material_key,"225mm hollow blocks::pcs");assert.deepEqual(args.budget_materials[0].sources,workspace.materials[0].sourceItems);assert.equal(args.source_fingerprint.length,64);});

test("fingerprint is stable and changes when reviewed approval content changes",async()=>{const first=await fingerprintAppProjectApproval(workspace,details);const second=await fingerprintAppProjectApproval(workspace,details);const changed=await fingerprintAppProjectApproval(workspace,{...details,location:"Maitama, Abuja"});assert.equal(first,second);assert.notEqual(first,changed);});

test("approval SQL cannot post financial activity",()=>{const sql=readFileSync(new URL("../supabase/drafts/app_project_approval_rpc_v1.sql",import.meta.url),"utf8");assert.match(sql,/charismak_app_estimate/);assert.match(sql,/project_cost_budget_materials/);assert.doesNotMatch(sql,/insert\s+into\s+public\.transactions/i);assert.doesNotMatch(sql,/update\s+public\.transactions/i);assert.doesNotMatch(sql,/insert\s+into\s+public\.journal/i);assert.doesNotMatch(sql,/insert\s+into\s+public\.project_commitments/i);});
