import test from "node:test";
import assert from "node:assert/strict";
import { parseBoqWorkbookSheets } from "../supabase/functions/_shared/boq-workbook-parser.ts";

test("parses S/N Description Qty Unit Rate Amount and preserves section headings",()=>{const result=parseBoqWorkbookSheets([{name:"Bill 1",rows:[["PROJECT BOQ"],["S/N","Description","Qty","Unit","Rate","Amount"],["","SUBSTRUCTURE","","","",""],["1","Excavate foundation trenches","85","m3","2500","212,500"],["2","Plain concrete blinding","12.5","m3","145000","1,812,500"],["","SUBTOTAL","","","","2,025,000"],["","BLOCKWORK","","","",""],["3","225mm hollow block wall","1820","m2","18500","33,670,000"]]}],"Jahi BOQ.xlsx");assert.equal(result.itemCount,3);assert.deepEqual(result.recognizedSheets,["Bill 1"]);assert.equal(result.boq.sections.length,2);assert.equal(result.boq.sections[0].title,"SUBSTRUCTURE");assert.equal(result.boq.sections[1].title,"BLOCKWORK");assert.equal(result.boq.sections[0].items[0].quantity,85);assert.equal(result.boq.sections[0].items[0].amount,212500);assert.equal(result.boq.sections[1].items[0].itemNo,"3");assert.equal(result.boq.sections[1].items[0].materialBreakdown.status,"needs_review");});

test("real hospitality BOQ keeps measured total descriptions, context and clean section headings",()=>{const result=parseBoqWorkbookSheets([{name:"Bill of Quantities",rows:[["ELEMENT NO. 1 - SCREEDS AND FLOOR PREPARATION"],["INFORMATION"],["Screed rates include cement, sand, admix and placing"],["M10: SAND CEMENT SCREEDS/TOPPINGS"],["Mortar cement and sand beds and backings"],["No","Item Description","Qty","Unit","Rate (₦)","Amount (₦)"],["A","10mm levelling screed to floors",35,"m2",3550,124250],["ELEMENT NO. 2 - MARBLE FLOOR FINISHES (LAYING ONLY)"],["INFORMATION"],["All marble tiles supplied by the Employer; items are LAYING ONLY"],["M40: STONE/MARBLE TILING"],["Marble tiles supplied by the Employer; laying only on cement/sand bed"],["No","Item Description","Qty","Unit","Rate (₦)","Amount (₦)"],["B","Verdi Alpi marble field tiling to Main Floor",78,"m2",13500,1053000],["ELEMENT NO. 9 - CEILING FINISHES"],["CF01: GYPSUM BOARD"],["gypsum board fixed using aluminum profiles; rate includes materials, joint tape, labour and transport"],["No","Item Description","Qty","Unit","Rate (₦)","Amount (₦)"],["C","indoor flat surface area to be covered",373,"m2",13500,5035500],["CF04: PAINTING"],["allow budget for screeding and painting; apply primer and two coats after preparation"],["No","Item Description","Qty","Unit","Rate (₦)","Amount (₦)"],["R","total paint area:",414,"m2",6500,2691000],["PAINT — CARRIED TO SUMMARY","","","","",2691000],["GRAND TOTAL — BILL NR. 1 + BILL NR. 9","","","","",22214355]]}],"Sora Restaurant BOQ.xlsx");assert.equal(result.itemCount,4);assert.deepEqual(result.boq.sections.map(section=>section.title),["M10: SAND CEMENT SCREEDS/TOPPINGS","M40: STONE/MARBLE TILING","CF01: GYPSUM BOARD","CF04: PAINTING"]);const marble=result.boq.sections[1];assert.ok(marble.context.some(value=>/LAYING ONLY/i.test(value)));assert.ok(marble.context.some(value=>/supplied by the Employer/i.test(value)));const gypsum=result.boq.sections[2];assert.ok(gypsum.context.some(value=>/rate includes materials/i.test(value)));const paint=result.boq.sections[3].items[0];assert.equal(paint.itemNo,"R");assert.equal(paint.description,"total paint area:");assert.equal(paint.quantity,414);assert.equal(paint.amount,2691000);assert.ok(result.boq.sections.every(section=>!/gypsum board fixed using/i.test(section.title)));assert.ok(result.boq.sections.every(section=>!/allow budget for screeding/i.test(section.title)));});

test("accepts reordered alternate headings and unpriced BOQ",()=>{const result=parseBoqWorkbookSheets([{name:"Roofing",rows:[["Particulars","UOM","Item No.","Measured Quantity"],["Supply and install longspan aluminium roofing","m²","R1","560"],["Ridge cap","m","R2","42"]]}],"Unpriced works.xlsx");assert.equal(result.itemCount,2);assert.equal(result.boq.sections[0].title,"Roofing");assert.equal(result.boq.sections[0].items[0].itemNo,"R1");assert.equal(result.boq.sections[0].items[0].quantity,560);assert.equal(result.boq.sections[0].items[0].rate,null);assert.equal(result.boq.sections[0].items[0].amount,null);});

test("uses worksheet names as sections and ignores non-BOQ sheets",()=>{const result=parseBoqWorkbookSheets([{name:"Preliminaries",rows:[["Ref","Description of Work","Unit","Quantity","Unit Price","Total Amount"],["P1","Mobilisation to site","LS","1","2500000","2500000"]]},{name:"Electrical",rows:[["No","Scope of Work","Qty","UOM","Rate","Value"],["E1","20mm PVC conduit","1200","m","650","780000"]]},{name:"Cover",rows:[["CHARISMAK PROJECT"],["BILL OF QUANTITIES"]]}],"Project.xlsx");assert.equal(result.itemCount,2);assert.deepEqual(result.recognizedSheets,["Preliminaries","Electrical"]);assert.deepEqual(result.supportSheets,["Cover"]);assert.deepEqual(result.skippedSheets,["Cover"]);assert.deepEqual(result.boq.sections.map(s=>s.title),["Preliminaries","Electrical"]);});

test("flags lump-sum or incomplete quantities for review instead of dropping the line",()=>{const result=parseBoqWorkbookSheets([{name:"Preliminaries",rows:[["S/N","Description","Unit","Rate","Amount"],["1","Contractor mobilisation","LS","1500000","1500000"],["2","Temporary site office","","800000","800000"]]}],"Prelims.xlsx");assert.equal(result.itemCount,2);assert.equal(result.boq.sections[0].items[0].quantity,1);assert.equal(result.boq.sections[0].items[1].unit,"item");assert.ok(result.warnings.some(w=>/quantity 1/i.test(w.message)));assert.ok(result.warnings.some(w=>/unit is shown as “item”/i.test(w.message)));});

test("wide Gate House-style bills use explicit Section and Specification columns instead of flattening or dropping scope",()=>{const result=parseBoqWorkbookSheets([{name:"BOQ",rows:[["DETAILED BILL OF QUANTITIES / QUOTATION"],["Section","Item No.","Description","Specification / Scope","Unit","Qty","Rate","Amount","Remarks","Drawing Ref.","Check"],["A. Preliminaries","A1","Mobilisation and site establishment","Transport tools and supervision","Item",1,250000,250000,"","General","OK"],["A. Preliminaries","A2","Setting out and verification","Confirm site dimensions","Item",1,100000,100000,"","Plan","OK"],["C. Substructure/Floor","C1","Excavation/trimming and preparation","Prepare footprint","m²",7.5,6000,45000,"","Plan","OK"],["C. Substructure/Floor","C2","Floor screed","Cement/sand screed","m²",7.5,7500,56250,"","Floor","OK"]]}],"Gate House.xlsx");assert.equal(result.itemCount,4);assert.deepEqual(result.boq.sections.map(section=>section.title),["A. Preliminaries","C. Substructure/Floor"]);assert.equal(result.boq.sections[0].items[0].itemNo,"A1");assert.match(result.boq.sections[0].items[0].description,/Transport tools and supervision/);assert.match(result.boq.sections[1].items[1].description,/Cement\/sand screed/);assert.equal(result.boq.sections[1].items[1].amount,56250);});

test("support tabs are skipped so BOQ totals are not double imported",()=>{const result=parseBoqWorkbookSheets([{name:"BOQ",rows:[["Item No.","Description","Unit","Qty","Rate","Amount"],["C1","Concrete slab","m²",7.5,45000,337500],["C2","Floor screed","m²",7.5,7500,56250]]},{name:"Steel Schedule",rows:[["Description","Qty","Unit","Rate","Amount"],["75x75 SHS",6,"lengths",35000,210000]]},{name:"Procurement",rows:[["Description","Qty","Unit","Rate","Amount"],["75x75 SHS",6,"lengths",35000,210000]]},{name:"Commercial Summary",rows:[["Description","Amount"],["Sub-total",393750],["VAT",29531.25]]}],"Gate House.xlsx");assert.equal(result.itemCount,2);assert.deepEqual(result.recognizedSheets,["BOQ"]);assert.deepEqual(result.supportSheets,["Steel Schedule","Procurement","Commercial Summary"]);assert.ok(result.skippedSheets.includes("Steel Schedule"));});

test("support-only material review workbooks do not masquerade as primary BOQs",()=>{const result=parseBoqWorkbookSheets([{name:"Material Schedule",rows:[["Description","Qty","Unit","Rate","Amount"],["Cement",120,"bags",12000,1440000]]},{name:"Material Calculations",rows:[["Description","Qty","Unit","Rate","Amount"],["Sharp sand",18,"m3",15000,270000]]},{name:"Cost Review & Savings",rows:[["Description","Amount"],["Potential savings",100000]]}],"Review workbook.xlsx");assert.equal(result.itemCount,0);assert.equal(result.recognizedSheets.length,0);assert.deepEqual(result.supportSheets,["Material Schedule","Material Calculations","Cost Review & Savings"]);assert.ok(result.warnings.some(w=>/Only support\/summary schedules/i.test(w.message)));});

test("Marina-style duplicate rate columns use the rightmost working rate and preserve arithmetic",()=>{const result=parseBoqWorkbookSheets([{name:"Bill 2",rows:[["ITEM","DESCRIPTION","UNIT","QTY","RATE (₦)","RATE (₦)","AMOUNT (₦)"],["4.1","Blockwork to walls","m²",22500,1500,2250,50625000],["4.2","Another item","m²",100,1000,2000,200000]]}],"Marina Towers Contract Bill.xlsx");assert.equal(result.itemCount,2);assert.equal(result.boq.sections[0].items[0].rate,2250);assert.equal(result.boq.sections[0].items[0].amount,50625000);assert.equal(result.warnings.filter(w=>/does not equal Qty × Rate/i.test(w.message)).length,0);});

test("legacy headerless Preliminaries are recovered conservatively while Taking Off stays excluded",()=>{const result=parseBoqWorkbookSheets([{name:"Prelims",rows:[["BILL NR 1"],["PRELIMINARIES"],["Allow for the following general items"],["A","Foreman - in - charge and Quality Assurance/Control"],["","(14Ai,20B)","","","","",1800000],["B","Plant, Tools and temporary equipment"],["","Allow for duration of works","","","","",950000],["C","Health, safety and welfare provisions"],["","Provide PPE and signage","","","","",350000]]},{name:"TAKING OFF",rows:[["Item","DESCRIPTION","QTY(Nr)","L(m)","W(m)","D/H(m)","AREA(m2)","VOL(m3)"],[1,"Excavation",2,10,1,.5,20,10]]}],"Earl Raven.xlsx");assert.equal(result.itemCount,3);assert.deepEqual(result.legacySheets,["Prelims"]);assert.equal(result.boq.sections[0].title,"PRELIMINARIES");assert.equal(result.boq.sections[0].items[0].unit,"LS");assert.equal(result.boq.sections[0].items[0].quantity,1);assert.equal(result.boq.sections[0].items[0].amount,1800000);assert.ok(result.boq.sections[0].items[0].description.includes("Quality Assurance"));assert.ok(result.skippedSheets.includes("TAKING OFF"));assert.ok(result.warnings.some(w=>/Legacy headerless bill layout/i.test(w.message)));});
