import test from "node:test";
import assert from "node:assert/strict";
import { buildMobileEstimateSummary, buildMobileProjectPreview, buildMobileEstimateHtml, buildMobileEstimateSpreadsheetXml, serializeMobileProjectPreview, ZERO_MOBILE_COMMERCIAL_SETTINGS } from "../mobile/lib/estimate-summary.ts";

const session={schemaVersion:1,savedAt:"2026-09-02T00:00:00Z",companyName:"Test Contractor",boq:{id:"b1",name:"House",currency:"NGN",sections:[{id:"s1",title:"Blockwork",items:[{id:"i1",itemNo:"4.1",description:"225mm blockwork",unit:"m2",quantity:100,rate:10000,amount:1000000},{id:"i2",itemNo:"4.2",description:"Extra blockwork",unit:"m2",quantity:20,rate:null,amount:null}]}]},decisions:{i1:{costCode:"04",recipeFamily:"blockwork_225",supplyResponsibility:"contractor",confirmed:true},i2:{costCode:"04",recipeFamily:"blockwork_225",supplyResponsibility:"contractor",confirmed:true}},rates:{i1:"10000",i2:"5000"},rateSources:{i1:"imported",i2:"manual"}};

test("mobile summary defaults every commercial adjustment to zero",()=>{const summary=buildMobileEstimateSummary(session,ZERO_MOBILE_COMMERCIAL_SETTINGS);assert.equal(summary.directCost,1100000);assert.equal(summary.sourcePricedTotal,1000000);assert.equal(summary.grandTotal,1100000);assert.equal(summary.tax,0);assert.equal(summary.arithmeticMismatchItems,0);assert.ok(summary.materials.some(row=>row.material.includes("blocks")));});

test("mobile summary follows the documented commercial order",()=>{const summary=buildMobileEstimateSummary(session,{contingencyPercent:5,overheadPercent:10,profitPercent:20,discountPercent:2,taxPercent:7.5});assert.equal(summary.directCost,1100000);assert.equal(summary.contingency,55000);assert.equal(summary.overhead,115500);assert.equal(summary.profit,254100);assert.equal(summary.discount,30492);assert.equal(summary.grandTotal,1606166.1);});

test("Android keeps imported source Amount visible and blocks unresolved Qty × Rate mismatch",()=>{const mismatch={...session,boq:{...session.boq,sections:[{...session.boq.sections[0],items:[{...session.boq.sections[0].items[0],quantity:16,rate:19000,amount:152000}]}]},rates:{i1:"19000"},rateSources:{i1:"imported"},decisions:{i1:session.decisions.i1}};const summary=buildMobileEstimateSummary(mismatch,ZERO_MOBILE_COMMERCIAL_SETTINGS);assert.equal(summary.directCost,304000);assert.equal(summary.sourcePricedTotal,152000);assert.equal(summary.arithmeticMismatchItems,1);assert.equal(summary.arithmeticMismatchDifference,152000);assert.equal(summary.isCommercialTotalComplete,false);const preview=buildMobileProjectPreview({session:mismatch,summary,projectName:"House",internalBudgetBasis:"direct_cost",contractValueBasis:"none",explicitInternalBudget:null,explicitContractValue:null});assert.equal(preview.readyToStage,false);assert.match(preview.issues.join(" "),/source Amount.*Qty × imported Rate/i);const html=buildMobileEstimateHtml(mismatch,summary);const xml=buildMobileEstimateSpreadsheetXml(mismatch,summary);assert.match(html,/SOURCE MISMATCH/);assert.match(html,/Source Amount/);assert.match(xml,/Imported Line Amounts/);assert.match(xml,/SOURCE MISMATCH/);});

test("explicit mobile confirmation resolves arithmetic mismatch without deleting source Amount",()=>{const reviewed={...session,boq:{...session.boq,sections:[{...session.boq.sections[0],items:[{...session.boq.sections[0].items[0],quantity:16,rate:19000,amount:152000}]}]},rates:{i1:"19000"},rateSources:{i1:"manual"},decisions:{i1:session.decisions.i1}};const summary=buildMobileEstimateSummary(reviewed,ZERO_MOBILE_COMMERCIAL_SETTINGS);assert.equal(summary.directCost,304000);assert.equal(summary.lines[0].sourceAmount,152000);assert.equal(summary.arithmeticMismatchItems,0);assert.equal(summary.isCommercialTotalComplete,true);const preview=buildMobileProjectPreview({session:reviewed,summary,projectName:"House",internalBudgetBasis:"direct_cost",contractValueBasis:"none",explicitInternalBudget:null,explicitContractValue:null});assert.equal(preview.readyToStage,true);});

test("project stage requires explicit budget and contract mapping",()=>{const summary=buildMobileEstimateSummary(session,ZERO_MOBILE_COMMERCIAL_SETTINGS);const preview=buildMobileProjectPreview({session,summary,projectName:"House",internalBudgetBasis:null,contractValueBasis:null,explicitInternalBudget:null,explicitContractValue:null});assert.equal(preview.readyToStage,false);assert.match(preview.issues.join(" "),/internal project cost budget/);assert.match(preview.issues.join(" "),/contract-value basis/);});

test("project stage keeps contract value separate from internal budget",()=>{const summary=buildMobileEstimateSummary(session,{...ZERO_MOBILE_COMMERCIAL_SETTINGS,contingencyPercent:5});const preview=buildMobileProjectPreview({session,summary,projectName:"House",internalBudgetBasis:"direct_plus_contingency",contractValueBasis:"grand_total",explicitInternalBudget:null,explicitContractValue:null});assert.equal(preview.project.internalCostBudget,1155000);assert.equal(preview.project.contractValue,1155000);assert.equal(preview.allowances[0].kind,"contingency");assert.equal(preview.readyToStage,true);assert.match(serializeMobileProjectPreview(preview),/charismak_app_mobile_estimate/);});
