import test from "node:test";
import assert from "node:assert/strict";
import { buildMobileEstimateSummary, buildMobileProjectPreview, serializeMobileProjectPreview, ZERO_MOBILE_COMMERCIAL_SETTINGS } from "../mobile/lib/estimate-summary.ts";

const session={schemaVersion:1,savedAt:"2026-09-02T00:00:00Z",companyName:"Test Contractor",boq:{id:"b1",name:"House",currency:"NGN",sections:[{id:"s1",title:"Blockwork",items:[{id:"i1",itemNo:"4.1",description:"225mm blockwork",unit:"m2",quantity:100,rate:10000},{id:"i2",itemNo:"4.2",description:"Extra blockwork",unit:"m2",quantity:20,rate:null}]}]},decisions:{i1:{costCode:"04",recipeFamily:"blockwork_225",supplyResponsibility:"contractor",confirmed:true},i2:{costCode:"04",recipeFamily:"blockwork_225",supplyResponsibility:"contractor",confirmed:true}},rates:{i1:"10000",i2:"5000"}};

test("mobile summary defaults every commercial adjustment to zero",()=>{const summary=buildMobileEstimateSummary(session,ZERO_MOBILE_COMMERCIAL_SETTINGS);assert.equal(summary.directCost,1100000);assert.equal(summary.grandTotal,1100000);assert.equal(summary.tax,0);assert.ok(summary.materials.some(row=>row.material.includes("blocks")));});

test("mobile summary follows the documented commercial order",()=>{const summary=buildMobileEstimateSummary(session,{contingencyPercent:5,overheadPercent:10,profitPercent:20,discountPercent:2,taxPercent:7.5});assert.equal(summary.directCost,1100000);assert.equal(summary.contingency,55000);assert.equal(summary.overhead,115500);assert.equal(summary.profit,254100);assert.equal(summary.discount,30492);assert.equal(summary.grandTotal,1606166.1);});

test("project stage requires explicit budget and contract mapping",()=>{const summary=buildMobileEstimateSummary(session,ZERO_MOBILE_COMMERCIAL_SETTINGS);const preview=buildMobileProjectPreview({session,summary,projectName:"House",internalBudgetBasis:null,contractValueBasis:null,explicitInternalBudget:null,explicitContractValue:null});assert.equal(preview.readyToStage,false);assert.match(preview.issues.join(" "),/internal project cost budget/);assert.match(preview.issues.join(" "),/contract-value basis/);});

test("project stage keeps contract value separate from internal budget",()=>{const summary=buildMobileEstimateSummary(session,{...ZERO_MOBILE_COMMERCIAL_SETTINGS,contingencyPercent:5});const preview=buildMobileProjectPreview({session,summary,projectName:"House",internalBudgetBasis:"direct_plus_contingency",contractValueBasis:"grand_total",explicitInternalBudget:null,explicitContractValue:null});assert.equal(preview.project.internalCostBudget,1155000);assert.equal(preview.project.contractValue,1155000);assert.equal(preview.allowances[0].kind,"contingency");assert.equal(preview.readyToStage,true);assert.match(serializeMobileProjectPreview(preview),/charismak_app_mobile_estimate/);});
