import assert from "node:assert/strict";
import test from "node:test";
import { buildProjectCostControl } from "../lib/project-cost/project-cost-control.ts";
import { buildProjectHealthSummary } from "../lib/project-cost/project-health.ts";

function control(overrides={}){return buildProjectCostControl({budgets:[{costCode:"04",amount:1_000_000},{costCode:"06",amount:500_000}],actuals:[{transactionId:"a",costCode:"04",amount:400_000},{transactionId:"b",costCode:"06",amount:100_000}],commitments:[],contractValue:2_000_000,forecastCostToComplete:900_000,...overrides});}

test("commercial health measures profit and margin drift from approved budget",()=>{const c=control();const result=buildProjectHealthSummary({control:c,contractValue:2_000_000,forecastLines:[{costCode:"04",amount:700_000},{costCode:"06",amount:200_000}]});assert.equal(c.position.internalCostBudget,1_500_000);assert.equal(c.forecastFinalCost,1_400_000);assert.equal(c.expectedProfitAtBudget,500_000);assert.equal(c.forecastProfit,600_000);assert.equal(result.forecastCostVariance,-100_000);assert.equal(result.profitDrift,100_000);assert.equal(result.expectedMarginPercent,25);assert.equal(result.forecastMarginPercent,30);assert.equal(result.marginDriftPoints,5);assert.equal(result.status,"on_target");});

test("profit erosion is explicit even while project remains profitable",()=>{const c=control({forecastCostToComplete:1_200_000});const result=buildProjectHealthSummary({control:c,contractValue:2_000_000,forecastLines:[{costCode:"04",amount:900_000},{costCode:"06",amount:300_000}]});assert.equal(c.forecastFinalCost,1_700_000);assert.equal(c.forecastProfit,300_000);assert.equal(result.profitDrift,-200_000);assert.equal(result.status,"profit_eroding");});

test("forecast loss is stronger than profit erosion",()=>{const c=control({contractValue:1_200_000,forecastCostToComplete:1_000_000});const result=buildProjectHealthSummary({control:c,contractValue:1_200_000,forecastLines:[{costCode:"04",amount:800_000},{costCode:"06",amount:200_000}]});assert.equal(c.forecastFinalCost,1_500_000);assert.equal(c.forecastProfit,-300_000);assert.equal(result.status,"forecast_loss");});

test("trade forecast risk uses actual plus reviewed future cost, not commitments twice",()=>{const c=buildProjectCostControl({budgets:[{costCode:"04",amount:1_000_000}],actuals:[{transactionId:"a",costCode:"04",amount:500_000}],commitments:[{commitmentId:"c",costCode:"04",committedAmount:700_000,paidAmount:200_000}],contractValue:1_500_000,forecastCostToComplete:650_000});const result=buildProjectHealthSummary({control:c,contractValue:1_500_000,forecastLines:[{costCode:"04",amount:650_000}]});const trade=result.tradeHealth.find(r=>r.costCode==="04");assert.equal(trade.forecastFinalCost,1_150_000);assert.equal(trade.varianceToBudget,150_000);assert.equal(trade.status,"over_budget");assert.equal(result.topRisks[0].costCode,"04");});

test("commercial decision remains not ready when contract or reviewed forecast is missing",()=>{const c=buildProjectCostControl({budgets:[{costCode:"04",amount:1_000_000}],actuals:[],commitments:null,contractValue:null});const result=buildProjectHealthSummary({control:c,contractValue:null,forecastLines:null});assert.equal(result.status,"not_ready");assert.equal(result.readyForCommercialDecision,false);assert.match(result.dataIssues.join(" "),/Contract value/);assert.match(result.dataIssues.join(" "),/Cost-to-Complete/);assert.match(result.dataIssues.join(" "),/Commitments/);});
