import test from "node:test";
import assert from "node:assert/strict";
import { buildStagedProjectWorkspace, parseStagedProjectWorkspace, serializeStagedProjectWorkspace } from "../lib/estimate/staged-project-workspace.ts";

const preview={sourceEstimateId:"boq-77",project:{name:"House",currency:"NGN",internalCostBudget:1150000,contractValue:1500000},commercialSnapshot:{directCost:1200000,contingency:60000,overhead:0,profit:0,discount:0,subtotalBeforeTax:1260000,tax:0,grandTotal:1260000},internalDirectCost:1100000,internalContingencyAllowance:55000,clientSuppliedExcludedValue:100000,budgetLines:[{sourceLineId:"i1",description:"Blockwork",unit:"m2",quantity:100,rate:10000,amount:1000000,costCode:"04",supplyResponsibility:"contractor"},{sourceLineId:"i2",description:"Painting",unit:"m2",quantity:100,rate:1000,amount:100000,costCode:"13",supplyResponsibility:"contractor"}],budgetAllowances:[{sourceAllowanceId:"a1",kind:"other",description:"Reviewed project cost reserve",amount:50000}],materials:[{key:"cement::50kg bag",material:"Cement",unit:"50kg bag",quantity:50,sources:[]}],forecastProfit:350000,issues:[],readyToStage:true};

test("staged workspace groups budget by stable cost code and keeps Money unlinked",()=>{const draft=buildStagedProjectWorkspace(preview,"2026-09-02T20:00:00.000Z");assert.equal(draft.workspaceId,"estimate:boq-77");assert.deepEqual(draft.costGroups.map(x=>x.costCode),["04","13"]);assert.equal(draft.budgetBaseline.lineTotal,1100000);assert.equal(draft.budgetBaseline.allowanceTotal,50000);assert.equal(draft.budgetBaseline.reconciliationDifference,0);assert.equal(draft.moneyConnection.status,"not_linked");assert.equal(draft.moneyConnection.confirmedSpend,null);});

test("staged workspace remains versioned and parseable",()=>{const draft=buildStagedProjectWorkspace(preview);const parsed=parseStagedProjectWorkspace(serializeStagedProjectWorkspace(draft));assert.equal(parsed?.schemaVersion,1);assert.equal(parsed?.status,"reviewed_draft");assert.equal(parsed?.project.name,"House");});
