import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { createClient } from "../../../../lib/supabase/server";

const money=(v:any)=>v==null?"—":new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:0}).format(Number(v));
const label=(v:any)=>String(v??"").replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());

export default async function SimpleProjectOverview({params}:{params:Promise<{id:string}>}){
  const {id}=await params;const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");
  const [{data:project},{data:commercial},{data:commitments},{data:docs},{data:transactions},{data:variations}]=await Promise.all([
    supabase.from("projects").select("id,project_code,name,location,status,progress_percent,project_image_path,client:clients(name),summary:project_financial_summaries(funding_received,company_funding,other_financing,confirmed_expenditure,cash_balance,outstanding_commitments,forecast_cost_to_complete,forecast_final_cost,forecast_profit,invoiced_amount,paid_revenue,retention_held)").eq("id",id).maybeSingle(),
    supabase.from("project_commercial_positions").select("base_scope,additional_scope,variations,identified_commercial_value,documented_client_invoices,approved_commercial_value,documents_needing_review").eq("project_id",id).maybeSingle(),
    supabase.from("project_commitments").select("id,description,outstanding_amount,status").eq("project_id",id).gt("outstanding_amount",0).order("created_at").limit(8),
    supabase.from("source_documents").select("id,file_name,document_type,uploaded_at").eq("project_id",id).order("uploaded_at",{ascending:false}).limit(6),
    supabase.from("canonical_transactions").select("id,transaction_date,narration,counterparty,signed_amount,classification,category_name").eq("project_id",id).order("transaction_date",{ascending:false}).limit(8),
    supabase.from("project_variations").select("id,variation_code,title,amount,status").eq("project_id",id).order("created_at",{ascending:false}).limit(8),
  ]);
  if(!project)notFound();
  const summary:any=Array.isArray((project as any).summary)?(project as any).summary[0]:(project as any).summary;const client:any=Array.isArray((project as any).client)?(project as any).client[0]:(project as any).client;
  const currentCommercial=Number(commercial?.identified_commercial_value??0);const base=Number(commercial?.base_scope??0);const additions=Number(commercial?.additional_scope??0);const vars=Number(commercial?.variations??0);const funding=Number(summary?.funding_received??0);const spent=Number(summary?.confirmed_expenditure??0);const committed=Number(summary?.outstanding_commitments??0);const position=funding-spent-committed;
  return <main className="simple-shell"><div className="simple-wrap">
    <div className="simple-top"><Link href="/projects">← Projects</Link><div style={{display:"flex",gap:10,flexWrap:"wrap"}}><Link href={`/projects/${id}/documents`}>Documents</Link><Link href={`/add?projectId=${id}`}>+ Add</Link></div></div>
    <header className="document-page-head"><span>{project.project_code}</span><h1>{project.name}</h1><p>{client?.name||"No client"} · {project.location||"Location not set"} · {label(project.status)} · {Number(project.progress_percent||0).toFixed(0)}% progress</p></header>

    <section className="commercial-tree-card"><div><small>Current identified commercial value</small><strong>{money(currentCommercial)}</strong><p>What the confirmed project documents currently say this project is worth.</p></div><div className="commercial-tree-grid"><span><b>{money(base)}</b><small>Original / base scope</small></span><span><b>{money(additions)}</b><small>Additional / new scope</small></span><span><b>{money(vars)}</b><small>Variations</small></span><span><b>{money(commercial?.documented_client_invoices)}</b><small>Client invoices found</small></span></div></section>

    <section className="project-summary-strip"><div><small>Money received for project</small><b>{money(funding)}</b><span>{Number(summary?.company_funding||0)>0?`+ ${money(summary.company_funding)} company funding`:"Client/project funding"}</span></div><div><small>Confirmed spend</small><b>{money(spent)}</b><span>Recorded project cost</span></div><div><small>Still agreed / to pay</small><b>{money(committed)}</b><span>{(commitments??[]).length} open commitment(s)</span></div><div><small>Funding position</small><b className={position<0?"negative":""}>{money(position)}</b><span>Funding − spend − commitments</span></div><div><small>Forecast profit</small><b className={Number(summary?.forecast_profit||0)<0?"negative":""}>{money(summary?.forecast_profit)}</b><span>Where forecast information is available</span></div></section>

    {Number(commercial?.documents_needing_review||0)>0&&<section className="smart-warning"><b>{commercial?.documents_needing_review} project document(s) need your decision.</b> <Link href={`/projects/${id}/documents`}>Review documents →</Link></section>}

    <section className="project-two-col"><article className="data-card"><div className="section-title"><small>Commercial breakdown</small><h2>What makes up the project value</h2></div><DataRow label="Original / base scope" value={money(base)}/><DataRow label="Additional / new scope" value={money(additions)}/><DataRow label="Variations" value={money(vars)}/><DataRow label="Current identified value" value={money(currentCommercial)}/><DataRow label="Approved commercial value" value={money(commercial?.approved_commercial_value)}/><DataRow label="Client invoices found" value={money(commercial?.documented_client_invoices)}/></article><article className="data-card"><div className="section-title"><small>Money position</small><h2>Where the project stands</h2></div><DataRow label="Client/project funding" value={money(summary?.funding_received)}/><DataRow label="Company funding / loan" value={money(summary?.company_funding)}/><DataRow label="Other financing" value={money(summary?.other_financing)}/><DataRow label="Confirmed spend" value={money(summary?.confirmed_expenditure)}/><DataRow label="Outstanding commitments" value={money(summary?.outstanding_commitments)}/><DataRow label="Cash/funding position" value={money(summary?.cash_balance)}/></article></section>

    <section className="project-two-col"><article className="data-card"><div className="section-title"><small>What is still owed</small><h2>Open commitments</h2></div>{(commitments??[]).length?(commitments??[]).map((r:any)=><DataRow key={r.id} label={r.description} value={money(r.outstanding_amount)} note={label(r.status)}/>):<Empty text="No open commitments recorded."/>}</article><article className="data-card"><div className="section-title"><small>Recent changes</small><h2>Additional work / variations</h2></div>{(variations??[]).length?(variations??[]).map((r:any)=><DataRow key={r.id} label={`${r.variation_code||"Variation"} · ${r.title}`} value={money(r.amount)} note={label(r.status)}/>):<Empty text="No formal variation records yet."/>}</article></section>

    <section className="project-two-col"><article className="data-card"><div className="section-title"><small>Evidence</small><h2>Recent project documents</h2></div>{(docs??[]).length?(docs??[]).map((d:any)=><DataRow key={d.id} label={d.file_name} value={label(d.document_type)} note={new Date(d.uploaded_at).toLocaleDateString("en-NG")}/>):<Empty text="No project documents uploaded yet."/>}<div className="inline-links"><Link href={`/projects/${id}/documents`}>Open all documents →</Link><Link href={`/add?projectId=${id}`}>Add records →</Link></div></article><article className="data-card"><div className="section-title"><small>Recent money activity</small><h2>Latest confirmed movements</h2></div>{(transactions??[]).length?(transactions??[]).map((t:any)=><DataRow key={t.id} label={t.narration||t.counterparty||"Transaction"} value={money(t.signed_amount)} note={`${t.transaction_date}${t.category_name?` · ${t.category_name}`:""}`}/>):<Empty text="No confirmed project transactions yet."/>}</article></section>

    <section className="add-card" style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:16,flexWrap:"wrap"}}><div><h2 style={{margin:"0 0 4px"}}>Need the detailed controls?</h2><p style={{margin:0,color:"#738493"}}>Budget rows, cost-to-complete, team access and the full accounting detail remain available without cluttering this overview.</p></div><Link href={`/projects/${id}`}>Open advanced project controls →</Link></section>
  </div></main>;
}

function DataRow({label,value,note}:{label:string;value:string;note?:string}){return <div className="data-row"><div><b>{label}</b>{note&&<span>{note}</span>}</div><strong>{value}</strong></div>}
function Empty({text}:{text:string}){return <div style={{padding:"10px 0",color:"#7c8b98",fontSize:12}}>{text}</div>}
