import { useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import * as DocumentPicker from "expo-document-picker";
import { SafeAreaView } from "react-native-safe-area-context";
import { supabase } from "../../lib/supabase";
import { loadWorkspace } from "../../lib/workspace";
import { Card, ScreenTitle, baseStyles as b } from "../../components/ui";

type Picked=DocumentPicker.DocumentPickerAsset;
type Result={name:string;state:"done"|"review"|"failed"|"duplicate"|"processing";message:string;type?:string};
function pseudoHash(bytes:Uint8Array){let h=2166136261;for(const x of bytes){h^=x;h=Math.imul(h,16777619)}return `fnv1a-${bytes.length}-${(h>>>0).toString(16).padStart(8,"0")}`}
const safe=(n:string)=>n.replace(/[^a-zA-Z0-9._-]/g,"_");

export default function Add(){
  const [files,setFiles]=useState<Picked[]>([]);const [results,setResults]=useState<Result[]>([]);const [busy,setBusy]=useState(false);const [summary,setSummary]=useState("");
  async function choose(){const r=await DocumentPicker.getDocumentAsync({multiple:true,copyToCacheDirectory:true,type:["application/pdf","text/csv","application/vnd.ms-excel","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","application/vnd.openxmlformats-officedocument.wordprocessingml.document","image/*"]});if(!r.canceled)setFiles(r.assets)}
  function update(i:number,p:Partial<Result>){setResults(x=>x.map((r,n)=>n===i?{...r,...p}:r))}
  async function process(){if(!files.length||busy)return;setBusy(true);setResults(files.map(f=>({name:f.name,state:"processing",message:"Waiting…"})));setSummary("");try{const w=await loadWorkspace();const {data:batch,error:be}=await supabase.from("intake_batches").insert({company_id:w.membership.company_id,created_by:w.user.id,total_files:files.length}).select("id").single();if(be||!batch)throw new Error(be?.message||"Could not start upload");let done=0,review=0,failed=0,dupes=0;for(let i=0;i<files.length;i++){const f=files[i];try{update(i,{message:"Reading file…"});const response=await fetch(f.uri);const ab=await response.arrayBuffer();const bytes=new Uint8Array(ab);if(bytes.length>20*1024*1024)throw new Error("File is over 20 MB");const hash=pseudoHash(bytes);const {data:dupe}=await supabase.from("source_documents").select("id").eq("company_id",w.membership.company_id).eq("file_hash",hash).limit(1).maybeSingle();if(dupe){dupes++;update(i,{state:"duplicate",message:"Already uploaded. Nothing counted twice."});continue}const ext=(f.name.split(".").pop()||"").toLowerCase();const path=`${w.membership.company_id}/intake/mobile/${Date.now()}-${safe(f.name)}`;update(i,{message:"Uploading securely…"});const {error:se}=await supabase.storage.from("universal-intake").upload(path,ab,{contentType:f.mimeType||undefined,upsert:false});if(se)throw se;const {data:doc,error:de}=await supabase.from("source_documents").insert({company_id:w.membership.company_id,document_type:"other",file_name:f.name,storage_path:path,file_hash:hash,metadata:{bucket:"universal-intake",extension:ext,mime_type:f.mimeType||null,original_size:bytes.length,upload_method:"native_mobile"},uploaded_by:w.user.id}).select("id").single();if(de||!doc)throw new Error(de?.message||"Could not register file");const {error:ie}=await supabase.from("intake_items").insert({batch_id:batch.id,company_id:w.membership.company_id,document_id:doc.id});if(ie)throw ie;update(i,{message:"Understanding document…"});const {data:a,error:ae}=await supabase.functions.invoke("analyse-intake-document",{body:{documentId:doc.id,batchId:batch.id}});if(ae)throw ae;const needs=a?.status==="needs_review";if(needs)review++;else done++;update(i,{state:needs?"review":"done",type:String(a?.type||"document").replaceAll("_"," "),message:a?.message||(needs?"Needs one confirmation.":"Processed automatically.")})}catch(e){failed++;update(i,{state:"failed",message:e instanceof Error?e.message:"Upload failed"})}}await supabase.from("intake_batches").update({processed_files:done+review+dupes,needs_review_count:review,status:failed===files.length?"failed":review?"needs_review":"completed",summary:{processed:done,needs_review:review,duplicates:dupes,failed}}).eq("id",batch.id);setSummary(`${done} organised · ${review} need your help · ${dupes} already known · ${failed} failed`)}catch(e){Alert.alert("Could not process files",e instanceof Error?e.message:"Please try again")}finally{setBusy(false)}}
  return <SafeAreaView style={b.screen} edges={["top"]}><ScrollView contentContainerStyle={b.content}><ScreenTitle eyebrow="ADD" title="Give Charismak your records" subtitle="Statements, invoices, BOQs, receipts and project documents can be selected together. You do not need to decide what they are first."/><Pressable style={s.drop} onPress={choose}><Text style={s.plus}>＋</Text><Text style={s.dropTitle}>{files.length?`${files.length} file${files.length===1?"":"s"} selected`:"Choose files"}</Text><Text style={s.dropCopy}>PDF · Excel · CSV · Word · images</Text></Pressable>{files.map(f=><View key={f.uri} style={s.file}><Text numberOfLines={1} style={s.fileName}>{f.name}</Text><Text style={s.fileSize}>{((f.size||0)/1024/1024).toFixed(2)} MB</Text></View>)}<Pressable disabled={!files.length||busy} onPress={process} style={[b.button,(!files.length||busy)&&{opacity:.45}]}><Text style={b.buttonText}>{busy?"Understanding your files…":"Add & organise"}</Text></Pressable>{!!summary&&<Text style={s.summary}>{summary}</Text>}{results.map((r,i)=><Card key={`${r.name}-${i}`} style={s.result}><View style={[s.icon,r.state==="done"&&s.good,r.state==="review"&&s.warn,r.state==="failed"&&s.bad]}><Text>{r.state==="done"?"✓":r.state==="review"?"?":r.state==="duplicate"?"↺":r.state==="failed"?"!":"…"}</Text></View><View style={{flex:1}}><Text numberOfLines={1} style={s.resultName}>{r.name}</Text>{r.type&&<Text style={s.type}>{r.type.toUpperCase()}</Text>}<Text style={s.message}>{r.message}</Text></View></Card>)}</ScrollView></SafeAreaView>
}
const s=StyleSheet.create({drop:{minHeight:155,borderWidth:1.5,borderStyle:"dashed",borderColor:"#a9c0d1",borderRadius:20,backgroundColor:"#f8fbfd",alignItems:"center",justifyContent:"center",padding:20},plus:{fontSize:36,color:"#0b5e8d"},dropTitle:{fontSize:18,fontWeight:"900",color:"#123a58",marginTop:3},dropCopy:{fontSize:10,color:"#7c8c99",marginTop:4},file:{flexDirection:"row",justifyContent:"space-between",gap:10,backgroundColor:"white",borderRadius:12,padding:11,borderWidth:1,borderColor:"#e0e7ec"},fileName:{flex:1,fontSize:11,fontWeight:"700",color:"#29475c"},fileSize:{fontSize:9,color:"#82909b"},summary:{fontSize:11,color:"#5a7080",fontWeight:"700"},result:{flexDirection:"row",alignItems:"center",gap:11},icon:{width:38,height:38,borderRadius:12,backgroundColor:"#eef3f6",alignItems:"center",justifyContent:"center"},good:{backgroundColor:"#e4f5ed"},warn:{backgroundColor:"#fff0c9"},bad:{backgroundColor:"#ffe7e5"},resultName:{fontSize:12,fontWeight:"850",color:"#17384f"},type:{fontSize:8,fontWeight:"900",color:"#0a8a63",marginTop:3},message:{fontSize:10,color:"#6e8190",marginTop:3,lineHeight:14}});
