import { useCallback, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useFocusEffect } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import { supabase } from "../../lib/supabase";
import { loadWorkspace } from "../../lib/workspace";
import { Card, money, ScreenTitle, SectionHead, baseStyles as b } from "../../components/ui";

export default function Approvals(){
  const [requests,setRequests]=useState<any[]>([]);const [projects,setProjects]=useState<any[]>([]);const [showNew,setShowNew]=useState(false);const [desc,setDesc]=useState("");const [amount,setAmount]=useState("");const [projectId,setProjectId]=useState<string|null>(null);const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{const [{data:r},{data:p}]=await Promise.all([supabase.from("approval_requests").select("id,project_id,request_type,description,amount,approved_amount,status,urgency,requested_at,requested_by").order("requested_at",{ascending:false}).limit(80),supabase.from("projects").select("id,project_code,name").neq("status","archived").order("name")]);setRequests(r??[]);setProjects(p??[]);if(!projectId&&p?.length)setProjectId(p[0].id)},[projectId]);useFocusEffect(useCallback(()=>{load()},[load]));
  async function create(){if(!desc.trim()||!Number(amount))return Alert.alert("Add a description and amount");setBusy(true);try{const w=await loadWorkspace();const {error}=await supabase.from("approval_requests").insert({company_id:w.membership.company_id,project_id:projectId,requested_by:w.user.id,request_type:"purchase",description:desc.trim(),amount:Number(amount),urgency:"normal",status:"pending"});if(error)throw error;setDesc("");setAmount("");setShowNew(false);await load()}catch(e){Alert.alert("Request failed",e instanceof Error?e.message:"Try again")}finally{setBusy(false)}}
  async function decide(row:any,action:"approve"|"reject"|"return"){setBusy(true);try{const w=await loadWorkspace();const status=action==="approve"?"approved":action==="reject"?"rejected":"returned";const approved=action==="approve"?Number(row.amount||0):0;const {error}=await supabase.from("approval_requests").update({status,approved_amount:approved,decided_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",row.id);if(error)throw error;const {error:ae}=await supabase.from("approval_actions").insert({request_id:row.id,actor_user_id:w.user.id,action,amount:approved||null,acting_interface:w.activeRole});if(ae)throw ae;await load()}catch(e){Alert.alert("Decision failed",e instanceof Error?e.message:"Try again")}finally{setBusy(false)}}
  const pending=requests.filter(r=>r.status==="pending"||r.status==="emergency_retrospective");return <SafeAreaView style={b.screen} edges={["top"]}><ScrollView contentContainerStyle={b.content}><ScreenTitle eyebrow="APPROVALS" title="Requests & decisions" subtitle="Site requests become finance decisions without WhatsApp chains or lost messages." right={<Pressable onPress={()=>setShowNew(v=>!v)} style={b.button}><Text style={b.buttonText}>＋ Request</Text></Pressable>}/>{showNew&&<Card><Text style={s.label}>What do you need?</Text><TextInput style={s.input} placeholder="e.g. Waterproofing balance" value={desc} onChangeText={setDesc}/><Text style={s.label}>Amount</Text><TextInput style={s.input} placeholder="0" keyboardType="numeric" value={amount} onChangeText={setAmount}/><Text style={s.label}>Project</Text><View style={s.projectChoices}>{projects.slice(0,8).map(p=><Pressable key={p.id} onPress={()=>setProjectId(p.id)} style={[s.choice,projectId===p.id&&s.choiceActive]}><Text style={[s.choiceText,projectId===p.id&&s.choiceTextActive]}>{p.project_code}</Text></Pressable>)}</View><Pressable disabled={busy} onPress={create} style={b.button}><Text style={b.buttonText}>{busy?"Saving…":"Submit request"}</Text></Pressable></Card>}<SectionHead title={`Needs decision (${pending.length})`}/>{pending.length?pending.map(r=>{const p=projects.find(x=>x.id===r.project_id);return <Card key={r.id}><View style={b.row}><Text style={s.code}>{p?.project_code||"COMPANY"}</Text><Text style={s.amount}>{money(r.amount)}</Text></View><Text style={s.desc}>{r.description}</Text><Text style={s.meta}>{String(r.request_type).replaceAll("_"," ")} · {r.urgency}</Text><View style={s.actions}><Pressable disabled={busy} onPress={()=>decide(r,"approve")} style={[s.action,s.approve]}><Text style={s.approveText}>Approve</Text></Pressable><Pressable disabled={busy} onPress={()=>decide(r,"return")} style={s.action}><Text style={s.actionText}>Return</Text></Pressable><Pressable disabled={busy} onPress={()=>decide(r,"reject")} style={s.action}><Text style={s.rejectText}>Reject</Text></Pressable></View></Card>}):<Card><Text style={b.muted}>No approval is waiting for you right now.</Text></Card>}<SectionHead title="Recent decisions"/>{requests.filter(r=>!pending.includes(r)).slice(0,12).map(r=><View key={r.id} style={s.history}><Text numberOfLines={1} style={s.historyText}>{r.description}</Text><Text style={s.historyStatus}>{String(r.status).replaceAll("_"," ")}</Text><Text style={s.historyAmount}>{money(r.amount)}</Text></View>)}</ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({label:{fontSize:10,fontWeight:"800",color:"#536b7d",marginTop:5},input:{height:44,borderWidth:1,borderColor:"#d5e0e8",borderRadius:12,paddingHorizontal:12,marginTop:4,marginBottom:7},projectChoices:{flexDirection:"row",flexWrap:"wrap",gap:6,marginVertical:7},choice:{borderWidth:1,borderColor:"#d8e2e9",borderRadius:10,paddingVertical:7,paddingHorizontal:10},choiceActive:{backgroundColor:"#073f65",borderColor:"#073f65"},choiceText:{fontSize:9,fontWeight:"800",color:"#506b7e"},choiceTextActive:{color:"white"},code:{fontSize:9,fontWeight:"900",color:"#1872ab"},amount:{fontSize:14,fontWeight:"900",color:"#0d3854"},desc:{fontSize:14,fontWeight:"800",color:"#16384f",marginTop:7},meta:{fontSize:9,color:"#81909c",marginTop:4},actions:{flexDirection:"row",gap:7,marginTop:12},action:{flex:1,minHeight:39,borderRadius:11,borderWidth:1,borderColor:"#d5e0e8",alignItems:"center",justifyContent:"center"},approve:{backgroundColor:"#e4f6ed",borderColor:"#b7e1cc"},approveText:{fontSize:10,fontWeight:"900",color:"#08734f"},actionText:{fontSize:10,fontWeight:"900",color:"#38566b"},rejectText:{fontSize:10,fontWeight:"900",color:"#aa433a"},history:{flexDirection:"row",gap:8,alignItems:"center",paddingVertical:10,borderBottomWidth:1,borderBottomColor:"#e5ebef"},historyText:{flex:1,fontSize:10,color:"#36556b"},historyStatus:{fontSize:8,textTransform:"uppercase",color:"#718394"},historyAmount:{fontSize:9,fontWeight:"800",color:"#183c56"}});
