import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";

export default function EstimateTab(){
  const router=useRouter();
  return <SafeAreaView style={s.safe} edges={["top"]}><ScrollView contentContainerStyle={s.page}>
    <View style={s.hero}><Text style={s.eye}>CHARISMAK APP · ESTIMATE</Text><Text style={s.title}>Start with what you already have</Text><Text style={s.sub}>For this test build, BOQ import is the active estimating route. Other routes will be opened only after they have complete workflows.</Text></View>
    <Pressable style={s.primary} onPress={()=>router.push("/upload-boq")}><Text style={s.badge}>ACTIVE</Text><Text style={s.cardTitle}>Upload BOQ</Text><Text style={s.cardText}>XLSX, XLS or CSV → detect primary work items → accept clear suggestions together → review only exceptions → materials → estimate summary.</Text><Text style={s.cta}>Upload BOQ ›</Text></Pressable>
    <Pressable style={s.secondary} onPress={()=>router.push("/boq-studio")}><Text style={s.badgeBlue}>WORKSPACE</Text><Text style={s.cardTitle}>BOQ Studio</Text><Text style={s.cardText}>Open the most recently reviewed BOQ and trace quantities into materials.</Text><Text style={s.ctaBlue}>Open BOQ Studio ›</Text></Pressable>
    <View style={s.later}><Text style={s.laterEye}>COMING AFTER CORE ACCEPTANCE</Text><Text style={s.laterTitle}>Quick Estimate · Guided Build · Drawing Upload · Enter Quantities</Text><Text style={s.laterCopy}>These are no longer shown as selectable workflows until each one is actually complete.</Text></View>
  </ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#f4f7fa"},page:{padding:16,paddingBottom:90,gap:14},hero:{backgroundColor:"#082945",borderRadius:20,padding:20,gap:7},eye:{fontSize:10,fontWeight:"900",letterSpacing:1.3,color:"#9ec5df",fontFamily:"sans-serif"},title:{fontSize:26,fontWeight:"900",color:"#fff",fontFamily:"sans-serif"},sub:{fontSize:13,lineHeight:19,color:"#d7e5ef",fontFamily:"sans-serif"},primary:{backgroundColor:"#fff",borderWidth:2,borderColor:"#0b668f",borderRadius:18,padding:17},secondary:{backgroundColor:"#fff",borderWidth:1,borderColor:"#dbe5ec",borderRadius:18,padding:17},badge:{alignSelf:"flex-start",fontSize:9,fontWeight:"900",color:"#087450",backgroundColor:"#e3f5ed",paddingHorizontal:8,paddingVertical:4,borderRadius:999,fontFamily:"sans-serif"},badgeBlue:{alignSelf:"flex-start",fontSize:9,fontWeight:"900",color:"#0b5f8f",backgroundColor:"#e8f3f9",paddingHorizontal:8,paddingVertical:4,borderRadius:999,fontFamily:"sans-serif"},cardTitle:{fontSize:19,fontWeight:"900",color:"#14354d",marginTop:9,fontFamily:"sans-serif"},cardText:{fontSize:12,lineHeight:18,color:"#617687",marginTop:6,fontFamily:"sans-serif"},cta:{fontSize:12,fontWeight:"900",color:"#087450",marginTop:13,fontFamily:"sans-serif"},ctaBlue:{fontSize:12,fontWeight:"900",color:"#0b5f8f",marginTop:13,fontFamily:"sans-serif"},later:{backgroundColor:"#fff8e8",borderWidth:1,borderColor:"#ecd9a7",borderRadius:16,padding:15},laterEye:{fontSize:9,fontWeight:"900",letterSpacing:1,color:"#866416",fontFamily:"sans-serif"},laterTitle:{fontSize:14,fontWeight:"900",color:"#55451d",marginTop:5,fontFamily:"sans-serif"},laterCopy:{fontSize:11,lineHeight:16,color:"#74694f",marginTop:5,fontFamily:"sans-serif"}});
