import { useCallback,useState } from "react";
import { ActivityIndicator,Pressable,RefreshControl,ScrollView,StyleSheet,Text,View } from "react-native";
import { router,useFocusEffect } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import { supabase } from "../../lib/supabase";
import { loadWorkspace } from "../../lib/workspace";
import { Card,money,ScreenTitle,SectionHead,Stat,baseStyles as b,palette } from "../../components/ui";
import { readableError } from "../../lib/mobile-error";

export default function Home(){
  const[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState("");
  const[balances,setBalances]=useState<any[]>([]),[projects,setProjects]=useState<any[]>([]),[tx,setTx]=useState<any[]>([]);
  const load=useCallback(async()=>{setError("");const w=await loadWorkspace();const start=new Date();start.setDate(1);const iso=start.toISOString().slice(0,10);const[bRes,pRes,tRes]=await Promise.all([
    supabase.from("account_recorded_balances").select("account_id,name,account_type,currency_code,recorded_balance").eq("company_id",w.membership.company_id),
    supabase.from("projects").select("id,name,status").eq("company_id",w.membership.company_id).neq("status","closed"),
    supabase.from("transactions").select("id,transaction_date,title,amount,kind,project:projects(name)").eq("company_id",w.membership.company_id).eq("status","posted").gte("transaction_date",iso).order("transaction_date",{ascending:false}).limit(40)
  ]);const err=bRes.error||pRes.error||tRes.error;if(err)throw err;setBalances(bRes.data??[]);setProjects(pRes.data??[]);setTx(tRes.data??[]);setLoading(false);setRefreshing(false)},[]);
  useFocusEffect(useCallback(()=>{load().catch(e=>{setError(readableError(e,"Could not load your accounting summary."));setLoading(false);setRefreshing(false)})},[load]));
  if(loading)return <SafeAreaView style={b.screen}><View style={s.center}><ActivityIndicator size="large" color={palette.navy}/></View></SafeAreaView>;
  const total=balances.reduce((a,r)=>a+Number(r.recorded_balance||0),0),moneyIn=tx.filter(x=>x.kind==="income").reduce((a,x)=>a+Number(x.amount||0),0),moneyOut=tx.filter(x=>x.kind==="expense").reduce((a,x)=>a+Number(x.amount||0),0);
  return <SafeAreaView style={b.screen} edges={["top"]}><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);load().catch(e=>{setError(readableError(e));setRefreshing(false)})}}/>} contentContainerStyle={b.content}>
    <ScreenTitle eyebrow="CHARISMAK ACCOUNTING" title="Know where the money went" subtitle="Construction accounting first: accounts, project funding, job spending and clear reports. Estimating is out of this version."/>
    {!!error&&<Card style={s.error}><Text style={s.errorTitle}>Accounting data needs attention</Text><Text style={s.errorCopy}>{error}</Text></Card>}
    <View style={b.grid}><View style={b.half}><Stat label="Recorded balance" value={money(total)} note={`${balances.length} account${balances.length===1?"":"s"}`}/></View><View style={b.half}><Stat label="Active projects" value={String(projects.length)}/></View><View style={b.half}><Stat label="Money in this month" value={money(moneyIn)} tone="green"/></View><View style={b.half}><Stat label="Money out this month" value={money(moneyOut)} tone="red"/></View></View>
    <View style={s.actions}><Pressable style={s.in} onPress={()=>router.push({pathname:"/new-transaction",params:{kind:"income"}})}><Text style={s.actionTitle}>＋ Money in</Text><Text style={s.actionCopy}>Funding or receipt</Text></Pressable><Pressable style={s.out} onPress={()=>router.push({pathname:"/new-transaction",params:{kind:"expense"}})}><Text style={s.actionTitleDark}>− Money out</Text><Text style={s.actionCopyDark}>Project spending</Text></Pressable></View>
    {!balances.length&&<Card><Text style={s.emptyTitle}>Start with an account</Text><Text style={s.emptyCopy}>Add the bank account, wallet or cash account you actually use.</Text><Pressable style={s.linkButton} onPress={()=>router.push("/new-account")}><Text style={s.linkText}>Add account</Text></Pressable></Card>}
    {!projects.length&&<Card><Text style={s.emptyTitle}>No project yet</Text><Text style={s.emptyCopy}>Create the job before recording project funding or direct project expenditure.</Text><Pressable style={s.linkButton} onPress={()=>router.push("/new-project")}><Text style={s.linkText}>Create project</Text></Pressable></Card>}
    <SectionHead title="Recent activity" action="See Money" onPress={()=>router.push("/(tabs)/money")}/>
    {tx.slice(0,8).length?tx.slice(0,8).map((r:any)=>{const incoming=r.kind==="income";const project=Array.isArray(r.project)?r.project[0]?.name:r.project?.name;return <View key={r.id} style={s.row}><View style={{flex:1}}><Text style={s.rowTitle}>{r.title||"Transaction"}</Text><Text style={s.rowMeta}>{r.transaction_date}{project?` · ${project}`:""}</Text></View><Text style={[s.amount,{color:incoming?palette.green:palette.red}]}>{incoming?"+":"−"}{money(Number(r.amount||0))}</Text></View>}):<Card><Text style={s.emptyCopy}>No recorded activity this month.</Text></Card>}
  </ScrollView></SafeAreaView>}
const s=StyleSheet.create({center:{flex:1,alignItems:"center",justifyContent:"center"},error:{backgroundColor:"#fff7f7",borderColor:"#e8bcbc"},errorTitle:{fontSize:15,fontWeight:"900",color:"#7f2929",fontFamily:"sans-serif"},errorCopy:{fontSize:14,lineHeight:21,color:"#815858",marginTop:4,fontFamily:"sans-serif"},actions:{flexDirection:"row",gap:10},in:{flex:1,minHeight:92,borderRadius:16,backgroundColor:palette.navy,padding:15,justifyContent:"center"},out:{flex:1,minHeight:92,borderRadius:16,backgroundColor:"#fff",borderWidth:1,borderColor:palette.line,padding:15,justifyContent:"center"},actionTitle:{fontSize:17,fontWeight:"900",color:"#fff",fontFamily:"sans-serif"},actionCopy:{fontSize:13,color:"#c9dce8",marginTop:3,fontFamily:"sans-serif"},actionTitleDark:{fontSize:17,fontWeight:"900",color:palette.ink,fontFamily:"sans-serif"},actionCopyDark:{fontSize:13,color:palette.muted,marginTop:3,fontFamily:"sans-serif"},emptyTitle:{fontSize:17,fontWeight:"900",color:palette.ink,fontFamily:"sans-serif"},emptyCopy:{fontSize:14,lineHeight:21,color:palette.muted,marginTop:5,fontFamily:"sans-serif"},linkButton:{alignSelf:"flex-start",marginTop:12,paddingVertical:10,paddingHorizontal:14,borderRadius:10,backgroundColor:"#eaf3f8"},linkText:{fontSize:14,fontWeight:"900",color:palette.navy,fontFamily:"sans-serif"},row:{flexDirection:"row",alignItems:"center",gap:10,paddingVertical:13,borderBottomWidth:1,borderBottomColor:"#e2e9ee"},rowTitle:{fontSize:15,fontWeight:"800",color:palette.ink,fontFamily:"sans-serif"},rowMeta:{fontSize:13,color:palette.muted,marginTop:3,fontFamily:"sans-serif"},amount:{fontSize:15,fontWeight:"900",fontFamily:"sans-serif"}});