import { useCallback, useState } from "react";
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from "react-native";
import { router, useFocusEffect } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import { supabase } from "../../lib/supabase";
import { loadWorkspace, type RoleFamily } from "../../lib/workspace";
import { baseStyles as b, Card, MiniLine, money, ProgressBar, ScreenTitle, SectionHead, Stat } from "../../components/ui";

type Project={id:string;project_code:string|null;name:string;reported_progress:number|null;contract_value:number|null;finance?:any};
export default function Home(){
  const [loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false);const [role,setRole]=useState<RoleFamily>("md_owner");const [company,setCompany]=useState("Company");const [projects,setProjects]=useState<Project[]>([]);const [accounts,setAccounts]=useState<any[]>([]);const [needsReview,setNeedsReview]=useState(0);const [series,setSeries]=useState<{in:number[];out:number[];labels:string[]}>({in:[],out:[],labels:[]});const [error,setError]=useState("");
  const load=useCallback(async()=>{setError("");const w=await loadWorkspace();setRole(w.activeRole);setCompany(w.companyName);const [{data:projectRows,error:projectError},{data:positions,error:positionError},{data:acct,error:accountError},{data:reviewRows,error:reviewError},{data:tx,error:txError}]=await Promise.all([
    supabase.from("projects").select("id,project_code,name,reported_progress,status,contract_value").neq("status","closed").order("name"),
    supabase.from("project_financial_positions").select("project_id,received,spent,funding_position"),
    supabase.from("account_recorded_balances").select("account_id,name,account_type,currency_code,recorded_balance"),
    supabase.from("import_rows").select("id,status").eq("status","needs_review").limit(500),
    supabase.from("transactions").select("transaction_date,amount,kind,status").eq("status","posted").order("transaction_date").limit(5000),
  ]);const firstError=projectError||positionError||accountError||reviewError||txError;if(firstError)throw firstError;const finance=new Map((positions??[]).map((row:any)=>[row.project_id,row]));setProjects((projectRows??[]).map((p:any)=>({...p,finance:finance.get(p.id)})));setAccounts(acct??[]);setNeedsReview((reviewRows??[]).length);const months=new Map<string,{i:number;o:number}>();for(const r of tx??[]){if(r.kind==="transfer")continue;const key=String(r.transaction_date||"").slice(0,7);if(!key)continue;const m=months.get(key)||{i:0,o:0};const a=Math.abs(Number(r.amount||0));if(r.kind==="income")m.i+=a;else if(r.kind==="expense")m.o+=a;months.set(key,m);}const keys=[...months.keys()].sort().slice(-8);setSeries({labels:keys,in:keys.map(k=>months.get(k)?.i||0),out:keys.map(k=>months.get(k)?.o||0)});setLoading(false);setRefreshing(false);},[]);
  useFocusEffect(useCallback(()=>{load().catch((e:any)=>{setError(e?.message||"Could not load company data");setLoading(false);setRefreshing(false);});},[load]));
  if(loading)return <SafeAreaView style={b.screen}><View style={s.center}><ActivityIndicator size="large" color="#073f65"/></View></SafeAreaView>;
  const funding=projects.reduce((a,p)=>a+Number(p.finance?.received||0),0),spent=projects.reduce((a,p)=>a+Number(p.finance?.spent||0),0),fundingPosition=projects.reduce((a,p)=>a+Number(p.finance?.funding_position||0),0),contractValue=projects.reduce((a,p)=>a+Number(p.contract_value||0),0),cash=accounts.reduce((a,r)=>a+Number(r.recorded_balance||0),0);const roleTitle=role==="accountant_cfo"?"Finance today":role==="project_manager"?"My projects":"Company today";const roleSub=role==="accountant_cfo"?"Recorded cash, imports and project spending.":role==="project_manager"?"Site money, project records and reported progress.":"A clean view of the current Accounting position.";
  return <SafeAreaView style={b.screen} edges={["top"]}><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);load().catch((e:any)=>{setError(e?.message||"Could not refresh company data");setRefreshing(false);})}}/>} contentContainerStyle={b.content}>
    <ScreenTitle eyebrow={company.toUpperCase()} title={roleTitle} subtitle={roleSub}/>{!!error&&<Card style={s.errorCard}><Text style={s.errorTitle}>Some live data could not load</Text><Text style={s.errorCopy}>{error}</Text></Card>}
    <View style={b.grid}>{role==="accountant_cfo"?<><View style={b.half}><Stat label="Recorded account cash" value={money(cash)} note={`${accounts.length} account${accounts.length===1?"":"s"}`}/></View><View style={b.half}><Stat label="Needs review" value={String(needsReview)} note="Imported rows" tone={needsReview?"orange":"green"}/></View><View style={b.half}><Stat label="Project received" value={money(funding)} note={`${projects.length} live projects`}/></View><View style={b.half}><Stat label="Project spend" value={money(spent)} note="Posted Accounting records"/></View></>:<><View style={b.half}><Stat label="Project received" value={money(funding)} note={`${projects.length} live projects`}/></View><View style={b.half}><Stat label="Project spend" value={money(spent)} note="Posted Accounting records"/></View><View style={b.half}><Stat label="Contract value recorded" value={money(contractValue)} note="Only signed/entered values"/></View><View style={b.half}><Stat label="Funding position" value={money(fundingPosition)} note="Received less recorded spend" tone={fundingPosition<0?"orange":"navy"}/></View></>}</View>
    <SectionHead title="Money in vs money out"/><Card><MiniLine values={series.in.length?series.in:[0,0]} comparison={series.out.length?series.out:[0,0]}/><View style={b.row}><Text style={b.muted}>{series.labels[0]||"No posted monthly data yet"}</Text><Text style={b.muted}>{series.labels.at(-1)||""}</Text></View></Card>
    <SectionHead title={role==="project_manager"?"Projects I can work on":"Projects"} action="See all" onPress={()=>router.push("/(tabs)/projects")}/>{!projects.length?<Card><Text style={s.emptyTitle}>Fresh workspace ready.</Text><Text style={s.emptyCopy}>Create your first project, then upload its BOQ from the project screen.</Text><Pressable style={s.create} onPress={()=>router.push("/new-project")}><Text style={s.createText}>Create first project</Text></Pressable></Card>:projects.slice(0,6).map(p=>{const f=p.finance||{},received=Number(f.received||0),spent0=Number(f.spent||0),contract=Number(p.contract_value||0),basis=contract||received,used=basis?Math.min(100,spent0/basis*100):0;return <Pressable key={p.id} onPress={()=>router.push({pathname:"/project/[id]",params:{id:p.id}})}><Card style={s.project}><View style={b.row}><View style={{flex:1}}><Text style={s.projectCode}>{p.project_code||"PROJECT"}</Text><Text style={s.projectName}>{p.name}</Text></View><View style={s.valueWrap}><Text style={s.valueLabel}>CONTRACT</Text><Text style={s.projectValue}>{contract?money(contract):"Not set"}</Text></View></View><ProgressBar value={used}/><View style={s.projectFoot}><Text style={s.projectMeta}>Received {money(received)}</Text><Text style={s.projectMeta}>Spent {money(spent0)}</Text><Text style={s.projectMeta}>{Math.round(Number(p.reported_progress||0))}% reported</Text></View></Card></Pressable>})}
  </ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({center:{flex:1,alignItems:"center",justifyContent:"center"},project:{gap:11},projectCode:{fontSize:10,color:"#1771ab",fontWeight:"900",fontFamily:"sans-serif"},projectName:{fontSize:16,fontWeight:"900",color:"#16374f",marginTop:2,fontFamily:"sans-serif"},valueWrap:{alignItems:"flex-end"},valueLabel:{fontSize:8,fontWeight:"900",color:"#8595a0",fontFamily:"sans-serif"},projectValue:{fontSize:13,fontWeight:"900",color:"#0a4265",marginTop:2,fontFamily:"sans-serif"},projectFoot:{flexDirection:"row",justifyContent:"space-between",gap:7,flexWrap:"wrap"},projectMeta:{fontSize:10,color:"#526c7e",fontFamily:"sans-serif"},emptyTitle:{fontSize:16,fontWeight:"900",color:"#173a53",fontFamily:"sans-serif"},emptyCopy:{fontSize:12,lineHeight:18,color:"#718692",marginTop:5,fontFamily:"sans-serif"},create:{backgroundColor:"#073f65",borderRadius:12,paddingVertical:12,alignItems:"center",marginTop:12},createText:{fontSize:13,fontWeight:"900",color:"#fff",fontFamily:"sans-serif"},errorCard:{borderColor:"#e4b9b9",backgroundColor:"#fff8f8"},errorTitle:{fontSize:13,fontWeight:"900",color:"#7f2929",fontFamily:"sans-serif"},errorCopy:{fontSize:11,lineHeight:16,color:"#815858",marginTop:4,fontFamily:"sans-serif"}});
