import { useCallback,useState } from "react";
import { ActivityIndicator,Pressable,RefreshControl,ScrollView,StyleSheet,Text,View } from "react-native";
import { router,useFocusEffect } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import { supabase } from "../../lib/supabase";
import { loadWorkspace } from "../../lib/workspace";
import { Card,money,ScreenTitle,SectionHead,Stat,baseStyles as b,palette } from "../../components/ui";
import { readableError } from "../../lib/mobile-error";

export default function MoneyTab(){
  const[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[accounts,setAccounts]=useState<any[]>([]),[projects,setProjects]=useState<any[]>([]),[transactions,setTransactions]=useState<any[]>([]),[error,setError]=useState("");
  const load=useCallback(async()=>{setError("");const w=await loadWorkspace();const[a,p,t]=await Promise.all([
    supabase.from("account_recorded_balances").select("account_id,name,account_type,currency_code,recorded_balance").eq("company_id",w.membership.company_id),
    supabase.from("project_financial_positions").select("project_id,name,received,spent,funding_position,status").eq("company_id",w.membership.company_id),
    supabase.from("transactions").select("id,transaction_date,title,description,amount,kind,project_id").eq("company_id",w.membership.company_id).eq("status","posted").order("transaction_date",{ascending:false}).limit(25)
  ]);const err=a.error||p.error||t.error;if(err)throw err;setAccounts(a.data??[]);setProjects(p.data??[]);setTransactions(t.data??[]);setLoading(false);setRefreshing(false)},[]);
  useFocusEffect(useCallback(()=>{load().catch(e=>{setError(readableError(e,"Could not load Money."));setLoading(false);setRefreshing(false)})},[load]));
  if(loading)return <SafeAreaView style={b.screen}><View style={s.center}><ActivityIndicator size="large" color={palette.navy}/></View></SafeAreaView>;
  const recordedCash=accounts.reduce((sum,row)=>sum+Number(row.recorded_balance||0),0),received=projects.reduce((sum,row)=>sum+Number(row.received||0),0),spent=projects.reduce((sum,row)=>sum+Number(row.spent||0),0),position=projects.reduce((sum,row)=>sum+Number(row.funding_position||0),0);
  return <SafeAreaView style={b.screen} edges={["top"]}><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);load().catch(e=>{setError(readableError(e));setRefreshing(false)})}}/>} contentContainerStyle={b.content}>
    <ScreenTitle eyebrow="MONEY" title="Record it once" subtitle="Where money moved, which project it belongs to, and why it moved. The ledger updates behind the scenes."/>
    {!!error&&<Card style={s.error}><Text style={s.errorTitle}>Could not load all accounting data</Text><Text style={s.errorCopy}>{error}</Text></Card>}
    <View style={b.grid}><View style={b.half}><Stat label="Recorded account cash" value={money(recordedCash)} note={`${accounts.length} account${accounts.length===1?"":"s"}`}/></View><View style={b.half}><Stat label="Project received" value={money(received)} note={`${projects.length} project${projects.length===1?"":"s"}`}/></View><View style={b.half}><Stat label="Project spend" value={money(spent)} tone="red" note="Posted project expenses"/></View><View style={b.half}><Stat label="Project cash position" value={money(position)} tone={position<0?"red":"navy"} note="Received less recorded spend"/></View></View>
    <View style={s.actions}><Pressable style={s.primary} onPress={()=>router.push({pathname:"/new-transaction",params:{kind:"income"}})}><Text style={s.primaryTitle}>＋ Money in</Text><Text style={s.primaryCopy}>Funding and receipts</Text></Pressable><Pressable style={s.secondary} onPress={()=>router.push({pathname:"/new-transaction",params:{kind:"expense"}})}><Text style={s.secondaryTitle}>− Money out</Text><Text style={s.secondaryCopy}>Project and company costs</Text></Pressable></View>
    <Pressable style={s.accountButton} onPress={()=>router.push("/new-account")}><Text style={s.accountButtonText}>＋ Add bank / wallet / cash account</Text></Pressable>
    <SectionHead title="Accounts"/>{accounts.length?accounts.map(a=><Card key={a.account_id}><View style={b.row}><View style={{flex:1}}><Text style={s.accountName}>{a.name}</Text><Text style={s.accountMeta}>{String(a.account_type||"account").replaceAll("_"," ")} · {a.currency_code||"NGN"}</Text></View><Text style={s.accountAmount}>{money(a.recorded_balance)}</Text></View></Card>):<Card><Text style={b.muted}>No financial accounts yet. Add the account where your project money actually moves.</Text></Card>}
    <SectionHead title="Recent posted activity"/>{transactions.length?transactions.map(t=>{const signed=t.kind==="income"?Number(t.amount||0):t.kind==="expense"?-Number(t.amount||0):0;return <View key={t.id} style={s.tx}><View style={{flex:1}}><Text numberOfLines={2} style={s.txTitle}>{t.title||t.description||"Transaction"}</Text><Text style={s.txMeta}>{t.transaction_date} · {String(t.kind||"movement").replaceAll("_"," ")}</Text></View><Text style={[s.txAmount,{color:signed<0?palette.red:palette.green}]}>{t.kind==="transfer"?"Transfer":money(signed)}</Text></View>}):<Card><Text style={b.muted}>No posted transactions yet.</Text></Card>}
    <Card style={s.truth}><Text style={s.truthTitle}>Construction-accounting rule</Text><Text style={s.truthCopy}>A cash balance is not profit. Project funding, company financing, advances and transfers are kept distinct from earned income and project expense.</Text></Card>
  </ScrollView></SafeAreaView>}
const s=StyleSheet.create({center:{flex:1,alignItems:"center",justifyContent:"center"},actions:{flexDirection:"row",gap:10},primary:{flex:1,minHeight:82,backgroundColor:palette.navy,borderRadius:15,padding:14,justifyContent:"center"},primaryTitle:{fontSize:17,fontWeight:"900",color:"#fff",fontFamily:"sans-serif"},primaryCopy:{fontSize:13,color:"#c8dce9",marginTop:4,fontFamily:"sans-serif"},secondary:{flex:1,minHeight:82,backgroundColor:"#fff",borderWidth:1,borderColor:palette.line,borderRadius:15,padding:14,justifyContent:"center"},secondaryTitle:{fontSize:17,fontWeight:"900",color:palette.ink,fontFamily:"sans-serif"},secondaryCopy:{fontSize:13,color:palette.muted,marginTop:4,fontFamily:"sans-serif"},accountButton:{minHeight:50,borderRadius:13,borderWidth:1,borderColor:"#bad0dd",alignItems:"center",justifyContent:"center",backgroundColor:"#fff"},accountButtonText:{fontSize:14,fontWeight:"900",color:palette.navy,fontFamily:"sans-serif"},accountName:{fontSize:15,fontWeight:"900",color:palette.ink,fontFamily:"sans-serif"},accountMeta:{fontSize:12,color:palette.muted,marginTop:3,textTransform:"capitalize",fontFamily:"sans-serif"},accountAmount:{fontSize:16,fontWeight:"900",color:palette.navy,fontFamily:"sans-serif"},tx:{flexDirection:"row",alignItems:"center",gap:10,paddingVertical:13,borderBottomWidth:1,borderBottomColor:"#e2e8ec"},txTitle:{fontSize:14,fontWeight:"800",color:"#29475c",fontFamily:"sans-serif"},txMeta:{fontSize:12,color:palette.muted,marginTop:3,fontFamily:"sans-serif"},txAmount:{fontSize:14,fontWeight:"900",fontFamily:"sans-serif"},truth:{backgroundColor:"#eef6fa",borderColor:"#c9dde8"},truthTitle:{fontSize:15,fontWeight:"900",color:palette.ink,fontFamily:"sans-serif"},truthCopy:{fontSize:13,lineHeight:20,color:palette.muted,marginTop:4,fontFamily:"sans-serif"},error:{borderColor:"#e4b9b9",backgroundColor:"#fff8f8"},errorTitle:{fontSize:15,fontWeight:"900",color:"#7f2929",fontFamily:"sans-serif"},errorCopy:{fontSize:13,lineHeight:19,color:"#815858",marginTop:4,fontFamily:"sans-serif"}});