import { useCallback, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router, useFocusEffect } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import { supabase } from "../../lib/supabase";
import { loadWorkspace, switchRole, type RoleFamily } from "../../lib/workspace";
import { Card, ScreenTitle, baseStyles as b } from "../../components/ui";

const meta:Record<RoleFamily,{label:string;note:string}>={md_owner:{label:"MD / Owner",note:"Company-wide control"},accountant_cfo:{label:"Accountant / CFO",note:"Finance operations"},project_director:{label:"Project Director",note:"Portfolio & cost control"},project_manager:{label:"Project / Construction Manager",note:"Site & project control"}};

export default function More(){
  const [workspace,setWorkspace]=useState<any>(null);const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>setWorkspace(await loadWorkspace()),[]);useFocusEffect(useCallback(()=>{load()},[load]));
  async function role(role:RoleFamily){if(!workspace||role===workspace.activeRole||busy)return;setBusy(true);try{await switchRole(workspace.membership.company_id,role);await load();Alert.alert("Workspace changed",`You are now viewing ${meta[role].label}. Actions remain recorded under your signed-in identity.`)}catch(e){Alert.alert("Could not switch role",e instanceof Error?e.message:"Try again")}finally{setBusy(false)}}
  async function signOut(){await supabase.auth.signOut();router.replace("/login")}
  return <SafeAreaView style={b.screen} edges={["top"]}><ScrollView contentContainerStyle={b.content}><ScreenTitle eyebrow="MORE" title="Your workspace" subtitle="Advanced tools stay here so everyday construction work remains simple."/>{workspace&&<Card><Text style={s.company}>{workspace.companyName}</Text><Text style={s.email}>{workspace.user.email}</Text><View style={s.identity}><Text style={s.identityLabel}>Acting as</Text><Text style={s.identityRole}>{meta[workspace.activeRole as RoleFamily]?.label}</Text></View></Card>}{workspace?.roles?.length>1&&<><Text style={s.group}>CHANGE WORKSPACE</Text>{workspace.roles.map((r:RoleFamily)=><Pressable key={r} disabled={busy} onPress={()=>role(r)} style={[s.role,workspace.activeRole===r&&s.roleActive]}><View><Text style={[s.roleName,workspace.activeRole===r&&s.roleNameActive]}>{meta[r].label}</Text><Text style={[s.roleNote,workspace.activeRole===r&&s.roleNoteActive]}>{meta[r].note}</Text></View><Text style={[s.chev,workspace.activeRole===r&&s.roleNameActive]}>{workspace.activeRole===r?"✓":"›"}</Text></Pressable>)}</>}
    <Text style={s.group}>APP MODULES</Text>
    <Tool title="Market" note="Materials, suppliers, artisans, professionals and local rates" onPress={()=>Alert.alert("Market","This is the next sourcing module. It will use location-aware rates and verified suppliers without mixing marketplace data into accounting truth.")}/>
    <Tool title="Ask Charismak" note="Ask questions across authorised project, BOQ and money data" onPress={()=>Alert.alert("Ask Charismak","This conversational layer will sit on top of structured project data after the shared Estimate → Project → Money core is stable.")}/>
    <Text style={s.group}>TOOLS</Text>
    <Tool title="Needs your decision" note="Only records Charismak could not resolve confidently" onPress={()=>router.push("/review")}/>
    <Tool title="Add records" note="Statements, invoices, BOQs, receipts and other documents" onPress={()=>router.push("/(tabs)/add")}/>
    <Tool title="Notifications" note="Approvals and actions needing attention" onPress={()=>router.push("/notifications")}/>
    {workspace?.membership?.is_owner&&<><Tool title="Company Branding" note="Logo, letterhead, company details and report colours" onPress={()=>router.push("/company-branding")}/><Tool title="People & Access" note="Role emails, positions and project access" onPress={()=>router.push("/people-access")}/><Tool title="Audit trail" note="Who changed what and through which acting role" onPress={()=>router.push("/audit")}/></>}
    <Pressable style={s.signout} onPress={signOut}><Text style={s.signoutText}>Sign out</Text></Pressable>
  </ScrollView></SafeAreaView>;
}
function Tool({title,note,onPress}:{title:string;note:string;onPress:()=>void}){return <Pressable onPress={onPress} style={s.tool}><View style={{flex:1,paddingRight:8}}><Text style={s.toolTitle}>{title}</Text><Text style={s.toolNote}>{note}</Text></View><Text style={s.chev}>›</Text></Pressable>}
const s=StyleSheet.create({company:{fontSize:17,fontWeight:"900",color:"#14364f"},email:{fontSize:10,color:"#7e8d99",marginTop:3},identity:{marginTop:13,borderRadius:13,backgroundColor:"#edf4f8",padding:11},identityLabel:{fontSize:8,color:"#768997",textTransform:"uppercase",letterSpacing:1},identityRole:{fontSize:13,fontWeight:"900",color:"#0a456c",marginTop:3},group:{fontSize:8,fontWeight:"900",letterSpacing:1.3,color:"#738696",marginTop:9,marginBottom:-4},role:{minHeight:61,borderRadius:15,borderWidth:1,borderColor:"#dce5ec",backgroundColor:"white",padding:12,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},roleActive:{backgroundColor:"#073f65",borderColor:"#073f65"},roleName:{fontSize:12,fontWeight:"900",color:"#183b55"},roleNameActive:{color:"white"},roleNote:{fontSize:9,color:"#7c8c98",marginTop:3},roleNoteActive:{color:"#bdd3e1"},chev:{fontSize:22,color:"#7890a0"},tool:{minHeight:60,borderBottomWidth:1,borderBottomColor:"#e2e8ec",paddingVertical:10,paddingHorizontal:3,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},toolTitle:{fontSize:12,fontWeight:"800",color:"#183b54"},toolNote:{fontSize:9,color:"#7c8d99",marginTop:3},signout:{height:46,borderRadius:13,borderWidth:1,borderColor:"#e7caca",alignItems:"center",justifyContent:"center",marginTop:14,backgroundColor:"#fff"},signoutText:{fontSize:11,fontWeight:"900",color:"#a43d3d"}});
