import { useCallback, useState } from "react";
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from "react-native";
import { router, useFocusEffect } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import { supabase } from "../../lib/supabase";
import { loadMobileStagedProjectWorkspaces } from "../../lib/staged-project-storage";
import type { MobileStagedProjectWorkspace } from "../../lib/estimate-summary";
import { Card, money, ProgressBar, ScreenTitle, SectionHead, baseStyles as b } from "../../components/ui";

const draftMoney=(value:number|null,currency:string)=>value==null?"—":new Intl.NumberFormat("en-NG",{style:"currency",currency,maximumFractionDigits:0}).format(value);
export default function Projects(){
  const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [projects,setProjects]=useState<any[]>([]);const [drafts,setDrafts]=useState<MobileStagedProjectWorkspace[]>([]);
  const load=useCallback(async()=>{const [{data:p},{data:c},localDrafts]=await Promise.all([supabase.from("projects").select("id,project_code,name,location,status,progress_percent,summary:project_financial_summaries(funding_received,confirmed_expenditure,cash_balance,outstanding_commitments,forecast_profit)").neq("status","archived").order("name"),supabase.from("project_commercial_positions").select("project_id,identified_commercial_value,base_scope,additional_scope,variations,documented_client_invoices"),loadMobileStagedProjectWorkspaces()]);const map=new Map((c??[]).map((x:any)=>[x.project_id,x]));setProjects((p??[]).map((x:any)=>({...x,summary:Array.isArray(x.summary)?x.summary[0]:x.summary,commercial:map.get(x.id)})));setDrafts(localDrafts);setLoading(false);setRefreshing(false)},[]);
  useFocusEffect(useCallback(()=>{load()},[load]));if(loading)return <SafeAreaView style={b.screen}><View style={s.center}><ActivityIndicator size="large" color="#073f65"/></View></SafeAreaView>;
  const total=projects.reduce((a,p)=>a+Number(p.commercial?.identified_commercial_value||0),0);const funding=projects.reduce((a,p)=>a+Number(p.summary?.funding_received||0),0);const spend=projects.reduce((a,p)=>a+Number(p.summary?.confirmed_expenditure||0),0);
  return <SafeAreaView style={b.screen} edges={["top"]}><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);load()}}/>} contentContainerStyle={b.content}>
    <ScreenTitle eyebrow="PROJECTS" title="Your project portfolio" subtitle="Reviewed Estimate drafts can sit here before approval. Live projects remain the source for actual money, documents and commitments."/>
    <View style={s.topActions}><Pressable onPress={()=>router.push("/new-project")} style={s.newProject}><Text style={s.newProjectText}>＋ New project</Text></Pressable><Pressable onPress={()=>router.push("/(tabs)/add")} style={s.addRecords}><Text style={s.addRecordsText}>Add records</Text></Pressable></View>
    {!!drafts.length&&<><SectionHead title={`From Estimate · ${drafts.length} draft${drafts.length===1?"":"s"}`}/>{drafts.map(d=><Pressable key={d.workspaceId} onPress={()=>router.push({pathname:"/project-draft/[id]",params:{id:d.workspaceId}})}><Card style={s.draftCard}><View style={b.row}><View style={{flex:1}}><Text style={s.draftStatus}>REVIEWED DRAFT · MONEY NOT LINKED</Text><Text style={s.name}>{d.project.name}</Text><Text style={s.meta}>{d.costGroups.length} cost groups · {d.materials.length} material totals</Text></View><Text style={s.value}>{draftMoney(d.project.internalCostBudget,d.project.currency)}</Text></View><View style={s.draftMetrics}><Text>Contract {draftMoney(d.project.contractValue,d.project.currency)}</Text><Text>Forecast {draftMoney(d.forecastProfit,d.project.currency)}</Text><Text>Actual —</Text></View></Card></Pressable>)}</>}
    {!!projects.length&&<View style={s.summary}><View><Text style={s.summaryLabel}>Live commercial value</Text><Text style={s.summaryValue}>{money(total)}</Text></View><View><Text style={s.summaryLabel}>Funding</Text><Text style={s.summaryValue}>{money(funding)}</Text></View><View><Text style={s.summaryLabel}>Spent</Text><Text style={s.summaryValue}>{money(spend)}</Text></View></View>}
    <SectionHead title={`${projects.length} live project${projects.length===1?"":"s"}`}/>
    {!projects.length&&<Card><Text style={s.emptyTitle}>No live projects yet.</Text><Text style={s.emptyCopy}>Create a project, stage one from Estimate, or use Add records and let Charismak discover projects from existing statements and documents.</Text></Card>}
    {projects.map(p=>{const q=p.summary||{},commercial=Number(p.commercial?.identified_commercial_value||0);const basis=commercial||Number(q.funding_received||0);const spendPct=basis?Math.min(100,Number(q.confirmed_expenditure||0)/basis*100):0;return <Pressable key={p.id} onPress={()=>router.push({pathname:"/project/[id]",params:{id:p.id}})}><Card style={s.card}><View style={b.row}><View style={{flex:1}}><Text style={s.code}>{p.project_code}</Text><Text style={s.name}>{p.name}</Text><Text style={s.meta}>{p.location||"Location not set"} · {String(p.status).replaceAll("_"," ")}</Text></View><Text style={s.value}>{money(commercial||q.funding_received)}</Text></View><ProgressBar value={spendPct}/><View style={s.metrics}><Text>Funding {money(q.funding_received)}</Text><Text>Spent {money(q.confirmed_expenditure)}</Text><Text>Committed {money(q.outstanding_commitments)}</Text></View></Card></Pressable>})}
  </ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({center:{flex:1,alignItems:"center",justifyContent:"center"},topActions:{flexDirection:"row",gap:8},newProject:{flex:1,height:44,borderRadius:13,backgroundColor:"#073f65",alignItems:"center",justifyContent:"center"},newProjectText:{fontSize:11,fontWeight:"900",color:"#fff"},addRecords:{flex:1,height:44,borderRadius:13,borderWidth:1,borderColor:"#cbdbe5",backgroundColor:"#fff",alignItems:"center",justifyContent:"center"},addRecordsText:{fontSize:11,fontWeight:"900",color:"#0a4c74"},summary:{flexDirection:"row",gap:7},summaryLabel:{fontSize:8,color:"#768897"},summaryValue:{fontSize:12,fontWeight:"900",color:"#133b57",marginTop:2},card:{gap:10},draftCard:{gap:10,borderColor:"#9fc3d7",backgroundColor:"#f8fbfd"},draftStatus:{fontSize:7,fontWeight:"900",color:"#16825c",letterSpacing:.4},code:{fontSize:9,fontWeight:"900",color:"#1771ab"},name:{fontSize:16,fontWeight:"900",color:"#14364f",marginTop:2},meta:{fontSize:9,color:"#81909d",marginTop:3},value:{fontSize:13,fontWeight:"900",color:"#0a476c"},metrics:{flexDirection:"row",justifyContent:"space-between",gap:6},draftMetrics:{flexDirection:"row",justifyContent:"space-between",gap:6,paddingTop:7,borderTopWidth:1,borderTopColor:"#dce6ec"},emptyTitle:{fontSize:14,fontWeight:"900",color:"#173a53"},emptyCopy:{fontSize:10,lineHeight:15,color:"#718692",marginTop:5}});
