import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
import * as XLSX from "npm:xlsx@0.18.5";

const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const out=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{...H,"content-type":"application/json"}});
const norm=(s:unknown)=>String(s??"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
const safe=(s:string)=>s.replace(/[^a-zA-Z0-9._-]/g,"_").slice(0,120);
function institution(text:string){const t=text.toLowerCase();for(const [k,n] of [["opay","OPay"],["access bank","Access Bank"],["united bank for africa","UBA"],[" uba ","UBA"],["carbon","Carbon"],["gtbank","GTBank"],["guaranty trust","GTBank"],["zenith","Zenith Bank"],["stanbic","Stanbic IBTC"],["first bank","First Bank"],["fcmb","FCMB"],["fidelity","Fidelity Bank"]] as const){if(t.includes(k))return n}return null;}
function accountNumber(text:string){for(const re of [/(?:account\s*(?:number|no\.?|#))\s*[:\-]?\s*([0-9*Xx-]{6,20})/i,/\b([0-9]{10})\b/]){const m=text.match(re);if(m)return m[1].replace(/\s/g,"")}return null;}
function looksStatement(text:string,headers:string[]=[]){const t=text.toLowerCase();const header=norm(headers.join(" "));let s=0;if(/statement of account|account statement|transaction history|bank statement/.test(t))s+=4;if(/opening balance|closing balance|running balance/.test(t))s+=2;if(/debit/.test(t)&&/credit/.test(t)&&/balance/.test(t))s+=3;if(/transaction date|value date|reference/.test(t))s+=2;if(header.includes("date")&&(header.includes("debit")||header.includes("credit")||header.includes("amount"))&&(header.includes("balance")||header.includes("description")||header.includes("narration")))s+=5;return s>=5;}
function sheetKind(name:string){const n=norm(name);if(/saving|owealth|wealth|interest/.test(n))return "savings";if(/wallet|current|main account/.test(n))return "wallet";return "account";}
function accountLabel(bank:string,sheet:string){const k=sheetKind(sheet);return k==="savings"?`${bank} Savings`:k==="wallet"?`${bank} Wallet`:`${bank} ${sheet.replace(/transactions?/ig,"").trim()||"Account"}`;}
async function sha256(bytes:Uint8Array){const d=await crypto.subtle.digest("SHA-256",bytes);return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,"0")).join("");}
function previewRows(ws:any,maxRows=220){const ref=ws?.["!ref"];if(!ref)return [] as unknown[][];const r=XLSX.utils.decode_range(ref);const range={s:{r:0,c:0},e:{r:Math.min(r.e.r,maxRows-1),c:Math.min(r.e.c,20)}};return XLSX.utils.sheet_to_json(ws,{header:1,defval:"",raw:false,blankrows:false,range}) as unknown[][];}
function readOneSheet(bytes:Uint8Array,name:string){const wb=XLSX.read(bytes,{type:"array",sheets:[name],raw:false,cellDates:true,dense:true,cellStyles:false,cellNF:false,cellHTML:false});return wb.Sheets[name];}

Deno.serve(async(req:Request)=>{
  if(req.method==="OPTIONS")return new Response("ok",{headers:H});
  if(req.method!=="POST")return out({error:"POST required"},405);
  const auth=req.headers.get("Authorization")??"";const anon=Deno.env.get("SUPABASE_ANON_KEY")!;const url=Deno.env.get("SUPABASE_URL")!;const sb=createClient(url,anon,{global:{headers:{Authorization:auth}}});
  const {data:{user}}=await sb.auth.getUser();if(!user)return out({error:"Sign in again."},401);
  const body=await req.json().catch(()=>({}));const documentId=String(body?.documentId??"");const batchId=String(body?.batchId??"");if(!documentId||!batchId)return out({error:"documentId and batchId are required"},400);
  const {data:doc,error:de}=await sb.from("source_documents").select("id,company_id,project_id,file_name,storage_path,metadata").eq("id",documentId).single();if(de||!doc)return out({error:de?.message||"Document not found"},404);
  const {data:item}=await sb.from("intake_items").select("id").eq("document_id",documentId).eq("batch_id",batchId).maybeSingle();if(!item)return out({error:"Intake item not found"},404);
  try{
    const ext=String((doc.metadata as any)?.extension??doc.file_name.split(".").pop()??"").toLowerCase();
    if(!["xlsx","xls"].includes(ext)){const proxied=await fetch(`${url}/functions/v1/analyse-intake-document`,{method:"POST",headers:{Authorization:auth,apikey:anon,"content-type":"application/json"},body:JSON.stringify({documentId,batchId})});const payload=await proxied.json().catch(()=>({error:"Analysis returned an unreadable response."}));return out(payload,proxied.status);}
    const bucket=String((doc.metadata as any)?.bucket||"universal-intake");const {data:blob,error:be}=await sb.storage.from(bucket).download(doc.storage_path);if(be||!blob)throw new Error(be?.message||"Could not read uploaded workbook");
    const bytes=new Uint8Array(await blob.arrayBuffer());
    console.log("intake-v3: workbook downloaded",{bytes:bytes.byteLength,file:doc.file_name});
    const meta=XLSX.read(bytes,{type:"array",bookSheets:true});const sheetNames=meta.SheetNames;
    console.log("intake-v3: sheet names",sheetNames);
    const statementSheets:{name:string;text:string;headers:string[]}[]=[];
    for(const name of sheetNames){
      const ws=readOneSheet(bytes,name);const rows=previewRows(ws,220);let header:unknown[]=[];for(const row of rows.slice(0,50)){if(row.filter(Boolean).length>header.filter(Boolean).length)header=row;}
      const headers=header.map(String);const text=rows.map(r=>r.map(v=>String(v??"")).join(" | ")).join("\n");
      if(looksStatement(`${name}\n${text}`,headers))statementSheets.push({name,text,headers});
    }
    console.log("intake-v3: statement sheets",statementSheets.map(s=>s.name));
    if(statementSheets.length<=1){const proxied=await fetch(`${url}/functions/v1/analyse-intake-document`,{method:"POST",headers:{Authorization:auth,apikey:anon,"content-type":"application/json"},body:JSON.stringify({documentId,batchId})});const payload=await proxied.json().catch(()=>({error:"Analysis returned an unreadable response."}));return out(payload,proxied.status);}
    const {data:loadedAccounts}=await sb.from("financial_accounts").select("id,institution_name,institution_key,account_name,account_number_masked,account_type").eq("company_id",doc.company_id).eq("is_active",true);const accounts:any[]=[...(loadedAccounts??[])];const imports:any[]=[];let totalRows=0;let failed=0;
    for(let i=0;i<statementSheets.length;i++){
      const s=statementSheets[i];const bank=institution(`${doc.file_name}\n${s.name}\n${s.text}`)||"Bank / financial account";const acctNo=accountNumber(s.text);const kind=sheetKind(s.name);const label=accountLabel(bank,s.name);const bankNorm=norm(bank);const targetNo=String(acctNo??"").replace(/[^0-9]/g,"");const sameBank=accounts.filter((a:any)=>norm(a.institution_name)===bankNorm||norm(a.institution_key).startsWith(bankNorm.replace(/\s/g,"")));let account:any=null;
      if(kind==="savings")account=sameBank.find((a:any)=>/saving|owealth|wealth/.test(norm(a.account_name)))??null;else if(kind==="wallet")account=sameBank.find((a:any)=>/wallet/.test(norm(a.account_name)))??sameBank.find((a:any)=>norm(a.account_name)===bankNorm)??null;if(!account&&kind!=="savings"&&targetNo){const byNo=sameBank.filter((a:any)=>String(a.account_number_masked??"").replace(/[^0-9]/g,"")===targetNo);if(byNo.length===1)account=byNo[0];}
      if(!account){const {data:created,error:ce}=await sb.from("financial_accounts").insert({company_id:doc.company_id,account_type:/opay|carbon/i.test(bank)?"fintech_wallet":"bank",institution_name:bank,institution_key:`${bankNorm.replace(/\s/g,"")}_${kind}`,account_name:label,account_number_masked:acctNo,created_by:user.id}).select("id,institution_name,account_name,account_number_masked,account_type,institution_key").single();if(ce||!created)throw new Error(ce?.message||`Could not create ${label}`);account=created;accounts.push(created);}
      console.log("intake-v3: splitting sheet",{sheet:s.name,account:account.account_name});
      const ws=readOneSheet(bytes,s.name);const childWb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(childWb,ws,s.name.slice(0,31));const childBytes=new Uint8Array(XLSX.write(childWb,{type:"array",bookType:"xlsx",bookSST:false}));const childHash=await sha256(childBytes);const {data:existingChild}=await sb.from("source_documents").select("id,storage_path,metadata").eq("company_id",doc.company_id).eq("document_type","bank_statement").eq("file_hash",childHash).limit(1).maybeSingle();let child:any=existingChild;
      if(!child){const childPath=`${doc.company_id}/intake/split/${new Date().getUTCFullYear()}/${documentId}-${i+1}-${safe(s.name)}.xlsx`;const {error:ue}=await sb.storage.from("universal-intake").upload(childPath,childBytes,{contentType:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",upsert:true});if(ue)throw new Error(ue.message);const {data:createdDoc,error:cde}=await sb.from("source_documents").insert({company_id:doc.company_id,project_id:null,document_type:"bank_statement",file_name:`${doc.file_name.replace(/\.[^.]+$/,"")} - ${s.name}.xlsx`,storage_path:childPath,file_hash:childHash,source_name:bank,metadata:{bucket:"universal-intake",extension:"xlsx",parent_document_id:documentId,source_sheet:s.name,generated_from_multi_sheet:true,account_kind:kind},uploaded_by:user.id}).select("id,storage_path,metadata").single();if(cde||!createdDoc)throw new Error(cde?.message||"Could not register split statement");child=createdDoc;}
      let {data:imp}=await sb.from("statement_imports").select("id,status,rows_total").eq("document_id",child.id).maybeSingle();if(!imp){const {data:createdImp,error:ie}=await sb.from("statement_imports").insert({document_id:child.id,company_id:doc.company_id,financial_account_id:account.id,detected_institution_name:bank,detected_account_name:account.account_name,detected_account_number_masked:acctNo,status:"uploaded",detected_as_new_account:false,rows_total:0,rows_new:0,rows_already_known:0,rows_need_review:0}).select("id,status,rows_total").single();if(ie||!createdImp)throw new Error(ie?.message||"Could not create statement import");imp=createdImp;}
      const analysed=await fetch(`${url}/functions/v1/analyse-statement`,{method:"POST",headers:{Authorization:auth,apikey:anon,"content-type":"application/json"},body:JSON.stringify({importId:imp.id})});const result=await analysed.json().catch(()=>({}));if(!analysed.ok){failed++;imports.push({sheet:s.name,account:account.account_name,importId:imp.id,status:"needs_review",message:result?.error||"Statement needs review"});continue;}const rows=Number(result?.rows_total??result?.rows??result?.totalRows??0);totalRows+=rows;imports.push({sheet:s.name,account:account.account_name,importId:imp.id,status:"applied",rows});
    }
    const applied=imports.filter(x=>x.status==="applied");const first=imports[0]?.importId;const message=failed?`${applied.length} of ${imports.length} statement sheets were processed separately; ${failed} need review.`:`Processed ${imports.length} statement sheets separately (${imports.map(x=>x.account).join(" + ")}).`;
    await sb.from("source_documents").update({document_type:"bank_statement",project_id:null,source_name:imports.map(x=>x.account).join(" + "),metadata:{...(doc.metadata as any),bucket,universal_intake_type:"bank_statement_multi_sheet",split_statement_imports:imports}}).eq("id",documentId);
    await sb.from("intake_items").update({detected_type:"bank_statement",detected_project_id:null,confidence:99,status:failed?"needs_review":"applied",suggested_action:{action:"open_statement",statement_import_id:first,statement_import_ids:imports.map(x=>x.importId)},message}).eq("id",item.id);
    return out({ok:true,type:"bank_statement",status:failed?"needs_review":"applied",statementImportId:first,statementImportIds:imports.map(x=>x.importId),statementAccounts:imports.map(x=>x.account),rows:totalRows,message});
  }catch(e){const msg=e instanceof Error?e.message:"Intake analysis failed";console.error("intake-v3 failed",msg);await sb.from("intake_items").update({status:"failed",message:msg}).eq("id",item.id);return out({error:msg},500);}
});
