import { useCallback, useMemo, useState } from "react";
import { ActivityIndicator, Alert, Modal, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { router, useFocusEffect, useLocalSearchParams } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import { supabase } from "../../lib/supabase";
import { Card, ScreenTitle, baseStyles as b, money } from "../../components/ui";

type Row={id:string;transaction_date:string;narration:string|null;counterparty:string|null;signed_amount:number|null;reference:string|null;links:any[]};
type Project={id:string;project_code:string;name:string};
const choices=[
  ["project_expense","Project expense"],["project_funding","Project funding"],["company_expense","Company expense"],["company_income","Company income"],["personal_non_business","Personal / non-business"],["internal_transfer","Internal transfer"],["unknown","Keep for reconciliation"],
] as const;

export default function StatementReview(){
  const {id}=useLocalSearchParams<{id:string}>();const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [statement,setStatement]=useState<any>(null);const [rows,setRows]=useState<Row[]>([]);const [projects,setProjects]=useState<Project[]>([]);const [selected,setSelected]=useState<Row|null>(null);const [classification,setClassification]=useState("project_expense");const [projectId,setProjectId]=useState("");const [category,setCategory]=useState("");const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{if(!id)return;const [{data:s,error:se},{data:r,error:re},{data:p}]=await Promise.all([
    supabase.from("statement_imports").select("id,detected_institution_name,detected_account_name,period_start,period_end,rows_total,rows_auto_posted,rows_pending_review,rows_already_known,status").eq("id",id).single(),
    supabase.from("statement_rows").select("id,transaction_date,narration,counterparty,signed_amount,reference,links:statement_row_transaction_links(canonical_transaction_id,is_primary)").eq("import_id",id).order("transaction_date").limit(500),
    supabase.from("projects").select("id,project_code,name").neq("status","archived").order("name"),
  ]);if(se)throw se;if(re)throw re;setStatement(s);setRows(((r??[]) as any[]).filter(x=>!((x.links??[]) as any[]).some(l=>l.is_primary&&l.canonical_transaction_id)));setProjects((p??[]) as Project[]);setLoading(false);setRefreshing(false)},[id]);
  useFocusEffect(useCallback(()=>{load().catch(e=>{setLoading(false);Alert.alert("Could not load statement",e instanceof Error?e.message:"Try again")})},[load]));
  const projectNeeded=classification==="project_expense"||classification==="project_funding";
  const visible=useMemo(()=>rows.slice(0,100),[rows]);
  function open(row:Row){setSelected(row);setClassification((row.signed_amount??0)>=0?"project_funding":"project_expense");setProjectId("");setCategory("")}
  async function confirm(){if(!selected||!id||busy)return;if(projectNeeded&&!projectId){Alert.alert("Choose a project","Project funding and project expenses must belong to a project.");return}setBusy(true);try{const {data,error}=await supabase.functions.invoke("confirm-statement-row",{body:{statementRowId:selected.id,importId:id,classification,projectId:projectNeeded?projectId:null,categoryName:classification==="project_expense"?(category||"Uncategorised"):null}});if(error)throw error;if(data?.error)throw new Error(data.error);setSelected(null);await load()}catch(e){Alert.alert("Could not save decision",e instanceof Error?e.message:"Try again")}finally{setBusy(false)}}
  if(loading)return <SafeAreaView style={b.screen}><View style={s.center}><ActivityIndicator size="large" color="#073f65"/></View></SafeAreaView>;
  return <SafeAreaView style={b.screen} edges={["top"]}><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);load()}}/>} contentContainerStyle={b.content}><Pressable onPress={()=>router.back()}><Text style={s.back}>← Needs your decision</Text></Pressable><ScreenTitle eyebrow="MONEY ACTIVITY" title={statement?.detected_institution_name||"Statement"} subtitle={`${statement?.detected_account_name||"Account"}${statement?.period_start?` · ${statement.period_start} → ${statement.period_end||"—"}`:""}`}/><View style={b.grid}><View style={b.half}><Card><Text style={s.statLabel}>Automatically handled</Text><Text style={s.stat}>{statement?.rows_auto_posted||0}</Text></Card></View><View style={b.half}><Card><Text style={s.statLabel}>Needs your decision</Text><Text style={s.stat}>{rows.length}</Text></Card></View></View>{!rows.length?<Card><Text style={s.clear}>This statement is clear.</Text><Text style={s.note}>All extracted movements have either been handled automatically or already confirmed.</Text></Card>:<><Text style={s.help}>Only unresolved movements are shown. Tap one to tell Charismak what it means.</Text>{visible.map(r=><Pressable key={r.id} onPress={()=>open(r)}><Card style={s.row}><View style={{flex:1}}><Text style={s.date}>{r.transaction_date}</Text><Text style={s.narration} numberOfLines={2}>{r.narration||r.counterparty||"Bank movement"}</Text>{r.reference&&<Text style={s.ref}>{r.reference}</Text>}</View><View style={{alignItems:"flex-end",gap:5}}><Text style={[s.amount,(r.signed_amount||0)<0&&s.out]}>{money(r.signed_amount)}</Text><Text style={s.decide}>Decide ›</Text></View></Card></Pressable>)}{rows.length>visible.length&&<Text style={s.note}>Showing the first {visible.length} unresolved movements. Confirm some decisions and refresh to continue.</Text>}</>}

  <Modal visible={!!selected} transparent animationType="slide" onRequestClose={()=>setSelected(null)}><Pressable style={s.backdrop} onPress={()=>setSelected(null)}/><View style={s.sheet}><View style={s.sheetHead}><View style={{flex:1}}><Text style={s.sheetEyebrow}>WHERE DOES THIS BELONG?</Text><Text style={s.sheetTitle} numberOfLines={2}>{selected?.narration||selected?.counterparty||"Bank movement"}</Text><Text style={s.sheetAmount}>{money(selected?.signed_amount)}</Text></View><Pressable onPress={()=>setSelected(null)}><Text style={s.close}>×</Text></Pressable></View><ScrollView style={{maxHeight:470}} contentContainerStyle={{gap:8,paddingBottom:18}}><Text style={s.label}>What is this?</Text><View style={s.choiceWrap}>{choices.map(([value,label])=><Pressable key={value} onPress={()=>setClassification(value)} style={[s.choice,classification===value&&s.choiceActive]}><Text style={[s.choiceText,classification===value&&s.choiceTextActive]}>{label}</Text></Pressable>)}</View>{projectNeeded&&<><Text style={s.label}>Which project?</Text><View style={s.projects}>{projects.map(p=><Pressable key={p.id} onPress={()=>setProjectId(p.id)} style={[s.project,projectId===p.id&&s.projectActive]}><Text style={[s.projectCode,projectId===p.id&&s.projectActiveText]}>{p.project_code}</Text><Text style={[s.projectName,projectId===p.id&&s.projectActiveText]}>{p.name}</Text></Pressable>)}</View></>}{classification==="project_expense"&&<><Text style={s.label}>Work / cost category <Text style={s.optional}>(optional)</Text></Text><TextInput value={category} onChangeText={setCategory} placeholder="e.g. Masonry, Tiling, Plumbing" style={s.input}/></>}<Pressable disabled={busy} onPress={confirm} style={[b.button,busy&&{opacity:.5}]}><Text style={b.buttonText}>{busy?"Saving…":"Confirm decision"}</Text></Pressable></ScrollView></View></Modal>
  </ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({center:{flex:1,alignItems:"center",justifyContent:"center"},back:{fontSize:10,fontWeight:"800",color:"#0a527d"},statLabel:{fontSize:8,color:"#788b99"},stat:{fontSize:20,fontWeight:"900",color:"#173b55",marginTop:3},help:{fontSize:10,color:"#738693",lineHeight:14},clear:{fontSize:15,fontWeight:"900",color:"#0e7b58"},note:{fontSize:9,color:"#7b8b97",lineHeight:13},row:{flexDirection:"row",alignItems:"center",gap:12},date:{fontSize:8,color:"#7d8c98"},narration:{fontSize:11,fontWeight:"800",color:"#173a53",marginTop:2},ref:{fontSize:7,color:"#94a0aa",marginTop:2},amount:{fontSize:11,fontWeight:"900",color:"#087a58"},out:{color:"#c94e42"},decide:{fontSize:8,fontWeight:"900",color:"#0a5b88"},backdrop:{position:"absolute",inset:0,backgroundColor:"rgba(5,24,38,.4)"},sheet:{position:"absolute",left:0,right:0,bottom:0,backgroundColor:"#fff",borderTopLeftRadius:24,borderTopRightRadius:24,padding:18,paddingBottom:28},sheetHead:{flexDirection:"row",gap:12,marginBottom:13},sheetEyebrow:{fontSize:7,fontWeight:"900",letterSpacing:1.2,color:"#0c8561"},sheetTitle:{fontSize:14,fontWeight:"900",color:"#173a52",marginTop:3},sheetAmount:{fontSize:17,fontWeight:"900",color:"#0a527d",marginTop:4},close:{fontSize:30,color:"#6f8290"},label:{fontSize:9,fontWeight:"900",color:"#526c7e",marginTop:5},optional:{fontWeight:"500",color:"#94a1aa"},choiceWrap:{flexDirection:"row",flexWrap:"wrap",gap:7},choice:{borderWidth:1,borderColor:"#d8e2e9",borderRadius:12,paddingVertical:9,paddingHorizontal:10,backgroundColor:"#fff"},choiceActive:{backgroundColor:"#073f65",borderColor:"#073f65"},choiceText:{fontSize:9,fontWeight:"800",color:"#36556a"},choiceTextActive:{color:"#fff"},projects:{gap:6},project:{borderWidth:1,borderColor:"#dde5eb",borderRadius:12,padding:9,backgroundColor:"#fff"},projectActive:{backgroundColor:"#e8f4ef",borderColor:"#4aa986"},projectCode:{fontSize:7,fontWeight:"900",color:"#1976aa"},projectName:{fontSize:10,fontWeight:"800",color:"#26465b",marginTop:2},projectActiveText:{color:"#086247"},input:{height:44,borderWidth:1,borderColor:"#d7e1e8",borderRadius:12,paddingHorizontal:11,fontSize:11,color:"#183b54",backgroundColor:"#fff"}});
