"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createClient } from "../../lib/supabase/server";
import { PROJECT_STATUSES, assertDateOrder, boundedText, optionalIsoDate, optionalNonNegativeMoney, optionalProgressPercent, requireAllowed } from "../../lib/validation/finance";

async function getContext(){const supabase=await createClient();const {data:authData,error:authError}=await supabase.auth.getUser();const user=authData.user;if(authError||!user)redirect("/login");const {data:membership,error}=await supabase.from("company_memberships").select("id,company_id,is_owner").eq("user_id",user.id).eq("status","active").limit(1).single();if(error||!membership)redirect("/login?message=No+active+company+membership");return{supabase,userId:user.id,membership};}
const safeFileName=(name:string)=>name.replace(/[^a-zA-Z0-9._-]/g,"_");
const normalizedRelationshipName=(value:string)=>value.trim().toLowerCase().replace(/\s+/g," ");
const aliasesFrom=(value:FormDataEntryValue|null)=>{const aliases=String(value||"").split(",").map(v=>v.trim()).filter(Boolean);if(aliases.length>20)throw new Error("Use no more than 20 project aliases.");for(const alias of aliases)if(alias.length>80)throw new Error("Each project alias must be 80 characters or fewer.");return aliases;};
async function uploadProjectImage(supabase:Awaited<ReturnType<typeof createClient>>,companyId:string,projectId:string,image:FormDataEntryValue|null){if(!(image instanceof File)||image.size===0)return null;if(image.size>10*1024*1024)throw new Error("Project image must be 10 MB or smaller.");if(!["image/jpeg","image/png","image/webp"].includes(image.type))throw new Error("Project image must be JPG, PNG or WEBP.");const path=`${companyId}/${projectId}/${Date.now()}-${safeFileName(image.name)}`;const bytes=new Uint8Array(await image.arrayBuffer());const {error}=await supabase.storage.from("project-media").upload(path,bytes,{contentType:image.type,upsert:false});if(error)throw new Error(`Project image upload failed: ${error.message}`);return path;}
async function ensureClientFundingRelationship(supabase:Awaited<ReturnType<typeof createClient>>,companyId:string,projectId:string,clientName:string,userId:string){const clean=clientName.trim();if(!clean)return;const normalized=normalizedRelationshipName(clean);const terms=Array.from(new Set([clean,normalized].map(v=>v.trim().toLowerCase()).filter(Boolean)));const {error}=await supabase.from("project_relationships").upsert({company_id:companyId,project_id:projectId,relationship_type:"client",display_name:clean,normalized_name:normalized,match_terms:terms,required_terms:[],excluded_terms:[],direction_rule:"credit",default_classification:"project_funding",default_category:null,confidence:96,source:"project_client_profile",is_active:true,created_by:userId,updated_at:new Date().toISOString()},{onConflict:"project_id,relationship_type,normalized_name"});if(error)throw new Error(`Project was created, but client funding recognition could not be configured: ${error.message}`);}

export async function createProject(formData:FormData){
  const {supabase,userId,membership}=await getContext();
  const clientName=boundedText(formData.get("client_name"),"Client name",160,false); const candidateId=String(formData.get("candidate_id")||"").trim(); const importId=String(formData.get("import_id")||"").trim(); let clientId:string|null=null;
  if(clientName){const {data:client,error:clientError}=await supabase.from("clients").upsert({company_id:membership.company_id,name:clientName},{onConflict:"company_id,name"}).select("id").single();if(clientError)throw new Error(`Could not save client: ${clientError.message}`);clientId=client.id;}
  const projectCode=boundedText(formData.get("project_code"),"Project code",40,true).toUpperCase();
  const projectName=boundedText(formData.get("name"),"Project name",160,true);
  if(!/^[A-Z0-9][A-Z0-9._/-]*$/.test(projectCode))throw new Error("Project code may contain letters, numbers, dots, dashes, slashes and underscores only.");
  const status=requireAllowed(String(formData.get("status")||"active"),PROJECT_STATUSES,"Project status");
  const startDate=optionalIsoDate(formData.get("start_date"),"Start date"),endDate=optionalIsoDate(formData.get("end_date"),"End date");assertDateOrder(startDate,endDate);
  const internalBudget=optionalNonNegativeMoney(formData.get("internal_cost_budget"),"Internal cost budget"),contractValue=optionalNonNegativeMoney(formData.get("contract_value"),"Contract value");
  const progress=optionalProgressPercent(formData.get("progress_percent"),0);
  const {data:project,error}=await supabase.from("projects").insert({company_id:membership.company_id,client_id:clientId,project_code:projectCode,name:projectName,project_type:boundedText(formData.get("project_type"),"Project type",100,false)||null,location:boundedText(formData.get("location"),"Location",200,false)||null,site_address:boundedText(formData.get("site_address"),"Site address",500,false)||null,status,start_date:startDate,end_date:endDate,contract_value:contractValue,internal_cost_budget:internalBudget,progress_percent:progress,external_reference:boundedText(formData.get("external_reference"),"External reference",120,false)||null,description:boundedText(formData.get("description"),"Description",4000,false)||null,aliases:aliasesFrom(formData.get("aliases")),notes:boundedText(formData.get("notes"),"Notes",6000,false)||null,created_by:userId,updated_by:userId}).select("id").single();if(error)throw new Error(`Could not create project: ${error.message}`);

  if(clientName)await ensureClientFundingRelationship(supabase,membership.company_id,project.id,clientName,userId);

  let imagePath:string|null=null;try{imagePath=await uploadProjectImage(supabase,membership.company_id,project.id,formData.get("project_image"));if(imagePath){const {error:imageUpdateError}=await supabase.from("projects").update({project_image_path:imagePath,image_alt:boundedText(formData.get("image_alt")||projectName,"Image alt text",250,false)||projectName,updated_by:userId,updated_at:new Date().toISOString()}).eq("id",project.id);if(imageUpdateError)throw imageUpdateError;}}catch(imageError){if(imagePath)await supabase.storage.from("project-media").remove([imagePath]);throw imageError;}

  const expectedRevenue=optionalNonNegativeMoney(formData.get("expected_contract_revenue"),"Expected contract revenue")??contractValue??0,originalBudget=optionalNonNegativeMoney(formData.get("original_budget"),"Original budget")??internalBudget??0;
  const {error:summaryError}=await supabase.from("project_financial_summaries").insert({project_id:project.id,original_budget:originalBudget,revised_budget:originalBudget,expected_contract_revenue:expectedRevenue,forecast_final_cost:originalBudget,forecast_cost_to_complete:originalBudget,forecast_profit:expectedRevenue-originalBudget});if(summaryError)throw new Error(`Project created but financial summary failed: ${summaryError.message}`);

  let autoPosted=0;let reclassified=0;
  if(candidateId){const {data:linked,error:candidateError}=await supabase.rpc("link_statement_candidate",{candidate_id:candidateId,target_project:project.id});if(candidateError)throw new Error(`Project created, but statement candidate linking failed: ${candidateError.message}`);reclassified=Number((linked as any)?.reclassified_rows??0);if(importId){const {data:posting,error:postingError}=await supabase.rpc("auto_post_statement_matches",{target_import:importId,minimum_confidence:94});if(postingError)throw new Error(`Project created and rows linked, but automatic posting failed: ${postingError.message}`);autoPosted=Number((posting as any)?.autoPosted??0);}}

  revalidatePath("/projects");revalidatePath("/");if(importId){revalidatePath(`/statements/${importId}`);revalidatePath(`/statements/${importId}/projects`);}
  redirect(candidateId&&importId?`/statements/${importId}/projects?created=${encodeURIComponent(projectCode)}&reclassified=${reclassified}&autoposted=${autoPosted}${clientName?`&client=${encodeURIComponent(clientName)}`:""}`:`/projects/${project.id}`);
}

export async function updateProject(formData:FormData){
  const {supabase,userId,membership}=await getContext();const projectId=String(formData.get("project_id")||"");if(!projectId)throw new Error("Project ID is required.");
  const {data:ownedProject,error:ownedProjectError}=await supabase.from("projects").select("id,project_image_path").eq("id",projectId).eq("company_id",membership.company_id).single();if(ownedProjectError||!ownedProject)throw new Error("Project not found in your company workspace.");
  const projectName=boundedText(formData.get("name"),"Project name",160,true);
  const status=requireAllowed(String(formData.get("status")||"active"),PROJECT_STATUSES,"Project status");
  const startDate=optionalIsoDate(formData.get("start_date"),"Start date"),endDate=optionalIsoDate(formData.get("end_date"),"End date");assertDateOrder(startDate,endDate);
  const progress=optionalProgressPercent(formData.get("progress_percent"),0);
  const contractValue=optionalNonNegativeMoney(formData.get("contract_value"),"Contract value"),internalBudget=optionalNonNegativeMoney(formData.get("internal_cost_budget"),"Internal cost budget");
  const newImagePath=await uploadProjectImage(supabase,membership.company_id,projectId,formData.get("project_image"));
  const patch:Record<string,unknown>={name:projectName,project_type:boundedText(formData.get("project_type"),"Project type",100,false)||null,location:boundedText(formData.get("location"),"Location",200,false)||null,site_address:boundedText(formData.get("site_address"),"Site address",500,false)||null,status,start_date:startDate,end_date:endDate,progress_percent:progress,contract_value:contractValue,internal_cost_budget:internalBudget,external_reference:boundedText(formData.get("external_reference"),"External reference",120,false)||null,description:boundedText(formData.get("description"),"Description",4000,false)||null,aliases:aliasesFrom(formData.get("aliases")),notes:boundedText(formData.get("notes"),"Notes",6000,false)||null,updated_by:userId,updated_at:new Date().toISOString()};
  if(newImagePath){patch.project_image_path=newImagePath;patch.image_alt=boundedText(formData.get("image_alt")||projectName,"Image alt text",250,false)||projectName;}
  const {error:projectError}=await supabase.from("projects").update(patch).eq("id",projectId).eq("company_id",membership.company_id);if(projectError){if(newImagePath)await supabase.storage.from("project-media").remove([newImagePath]);throw new Error(`Could not update project: ${projectError.message}`);}if(newImagePath&&ownedProject.project_image_path&&ownedProject.project_image_path!==newImagePath)await supabase.storage.from("project-media").remove([ownedProject.project_image_path]);

  const {data:current}=await supabase.from("project_financial_summaries").select("funding_received,confirmed_expenditure,outstanding_commitments").eq("project_id",projectId).maybeSingle();
  const originalBudget=optionalNonNegativeMoney(formData.get("original_budget"),"Original budget")??internalBudget??0,revisedBudget=optionalNonNegativeMoney(formData.get("revised_budget"),"Revised budget")??originalBudget,actual=Number(current?.confirmed_expenditure??0),forecastCtc=optionalNonNegativeMoney(formData.get("forecast_cost_to_complete"),"Forecast cost to complete")??Math.max(revisedBudget-actual,0),forecastFinal=actual+forecastCtc,expectedRevenue=optionalNonNegativeMoney(formData.get("expected_contract_revenue"),"Expected contract revenue")??contractValue??0,overhead=optionalNonNegativeMoney(formData.get("overhead_allocated"),"Overhead allocated")??0;
  const {error:summaryError2}=await supabase.from("project_financial_summaries").upsert({project_id:projectId,original_budget:originalBudget,revised_budget:revisedBudget,forecast_cost_to_complete:forecastCtc,forecast_final_cost:forecastFinal,expected_contract_revenue:expectedRevenue,work_certified:optionalNonNegativeMoney(formData.get("work_certified"),"Work certified")??0,invoiced_amount:optionalNonNegativeMoney(formData.get("invoiced_amount"),"Invoiced amount")??0,paid_revenue:optionalNonNegativeMoney(formData.get("paid_revenue"),"Paid revenue")??0,retention_held:optionalNonNegativeMoney(formData.get("retention_held"),"Retention held")??0,overhead_allocated:overhead,forecast_profit:expectedRevenue-forecastFinal-overhead,updated_at:new Date().toISOString()});if(summaryError2)throw new Error(`Project details saved but commercial forecast failed: ${summaryError2.message}`);
  const {error:refreshError}=await supabase.rpc("refresh_project_financial_summary",{target_project:projectId});if(refreshError)throw new Error(`Project saved but ledger totals could not refresh: ${refreshError.message}`);
  revalidatePath(`/projects/${projectId}`);revalidatePath("/projects");revalidatePath("/");redirect(`/projects/${projectId}?saved=1`);
}