"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "../../lib/supabase/client";
import { validateUploadBatch } from "../../lib/accounting/guards";

type Project={id:string;project_code:string;name:string};
type Hint="auto"|"bank_statement"|"invoice"|"bill"|"quotation"|"receipt"|"boq"|"other";
type Action="analyse"|"analyse_keywords"|"store_only";
type Plan={file:File;hint:Hint;action:Action};
type ResultState="queued"|"working"|"done"|"review"|"duplicate"|"failed"|"removed";
type Result={name:string;state:ResultState;message:string;href?:string;type?:string;documentId?:string;statementImportId?:string;intakeItemId?:string};

const MAX=20*1024*1024;
const supported=["pdf","csv","xlsx","xls","docx","jpg","jpeg","png","webp"];
const mime:Record<string,string[]>={pdf:["application/pdf"],csv:["text/csv","application/csv","text/plain","application/vnd.ms-excel"],xlsx:["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","application/octet-stream"],xls:["application/vnd.ms-excel","application/octet-stream"],docx:["application/vnd.openxmlformats-officedocument.wordprocessingml.document","application/octet-stream"],jpg:["image/jpeg"],jpeg:["image/jpeg"],png:["image/png"],webp:["image/webp"]};
const safe=(s:string)=>s.replace(/[^a-zA-Z0-9._-]/g,"_");
const wordsFrom=(s:string)=>Array.from(new Set(s.split(/[\n,;]+/).map(v=>v.trim()).filter(v=>v.length>=2))).slice(0,40);
const label=(s:string)=>s.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const fieldLabel={display:"grid",gap:5,fontSize:10,fontWeight:800,color:"#536879"} as const;
const control={height:42,border:"1px solid #ccd9e2",borderRadius:10,padding:"0 10px",background:"white",font:"inherit"} as const;

async function hash(file:File){const bytes=await file.arrayBuffer();const d=await crypto.subtle.digest("SHA-256",bytes);return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,"0")).join("");}
async function readableFunctionError(error:any){try{const response=error?.context as Response|undefined;if(response){if(response.status===401)return "Your session needs to be refreshed. Sign in again and retry this file.";const payload=await response.clone().json().catch(()=>null);if(payload?.error)return payload.error;if(payload?.message)return payload.message;if(response.status>=500)return "Analysis could not finish for this file. The uploaded copy is safe and this file can be retried without affecting the others.";}}catch{}return error?.message||"This file could not be analysed.";}

export default function UniversalIntakeV3({companyId,projects,onboarding=false,defaultProjectId="",embedded=false}:{companyId:string;projects:Project[];onboarding?:boolean;defaultProjectId?:string;embedded?:boolean}){
  const supabase=useMemo(()=>createClient(),[]);const router=useRouter();
  const [plans,setPlans]=useState<Plan[]>([]);const [defaultHint,setDefaultHint]=useState<Hint>("auto");const [defaultAction,setDefaultAction]=useState<Action>("analyse");const [keywordText,setKeywordText]=useState("");const [projectId,setProjectId]=useState(defaultProjectId);const [results,setResults]=useState<Result[]>([]);const [summary,setSummary]=useState("");const [busy,setBusy]=useState(false);
  const update=(i:number,p:Partial<Result>)=>setResults(prev=>prev.map((r,x)=>x===i?{...r,...p}:r));
  const setPlan=(i:number,p:Partial<Pick<Plan,"hint"|"action">>)=>setPlans(prev=>prev.map((r,x)=>x===i?{...r,...p}:r));
  function choose(files:File[]){setPlans(files.map(file=>({file,hint:defaultHint,action:defaultAction})));setResults([]);setSummary("");}
  function applyDefaults(){setPlans(prev=>prev.map(p=>({...p,hint:defaultHint,action:defaultAction})));}

  async function projectSignals(analysed:any,terms:string[]){
    const ids:string[]=Array.isArray(analysed?.statementImportIds)&&analysed.statementImportIds.length?analysed.statementImportIds.map(String):analysed?.statementImportId?[String(analysed.statementImportId)]:[];
    let count=0;let first:string|null=null;
    for(const importId of ids){const {data,error}=terms.length?await supabase.rpc("discover_statement_projects_with_keywords",{target_import:importId,target_keywords:terms}):await supabase.rpc("discover_statement_projects",{target_import:importId});if(error)continue;const found=Number((data as any)?.candidate_count??0);count+=found;if(!first&&found>0)first=importId;}
    return{count,first,firstImport:ids[0]??null};
  }

  async function applyResult(i:number,documentId:string,intakeItemId:string,plan:Plan,analysed:any,terms:string[]){
    const importIds:string[]=Array.isArray(analysed?.statementImportIds)&&analysed.statementImportIds.length?analysed.statementImportIds.map(String):analysed?.statementImportId?[String(analysed.statementImportId)]:[];
    if(importIds.length){const signals=plan.action==="store_only"?{count:0,first:null,firstImport:importIds[0]}:await projectSignals(analysed,terms);const base=analysed?.message||"Financial statement imported.";update(i,{state:analysed?.status==="needs_review"?"review":"done",type:"Financial statement",message:`${base}${signals.count?` ${signals.count} project/site signal${signals.count===1?"":"s"} found.`:""}`,documentId,intakeItemId,statementImportId:signals.firstImport??undefined,href:signals.first?`/statements/${signals.first}/projects`:`/statements/${signals.firstImport}`});return;}
    if(analysed?.projectId&&analysed?.status==="ready"){const {data,error}=await supabase.functions.invoke("auto-apply-project-document",{body:{documentId,projectId:analysed.projectId}});if(!error&&data?.applied){update(i,{state:"done",type:label(analysed?.type||plan.hint),message:"Document analysed and applied to the project record.",documentId,intakeItemId,href:`/projects/${analysed.projectId}/documents`});return;}update(i,{state:"review",type:label(analysed?.type||plan.hint),message:"The document was understood. Confirm the interpretation before it changes the official project record.",documentId,intakeItemId,href:`/projects/${analysed.projectId}/documents`});return;}
    const review=analysed?.status==="needs_review";update(i,{state:review?"review":"done",type:label(String(analysed?.type||plan.hint||"document")),message:analysed?.message||(review?"One decision is needed before this affects accounting.":"Record analysed and organised."),documentId,intakeItemId,href:review?`/review/${intakeItemId}`:(analysed?.projectId?`/projects/${analysed.projectId}/documents`:"/documents")});
  }

  async function removeResult(i:number){const r=results[i];if(!r?.documentId||r.state==="removed")return;if(!window.confirm("Delete this uploaded record? It will be removed from active records, while the audit trail keeps the deletion history."))return;try{let data:any=null;if(r.statementImportId){const x=await supabase.rpc("delete_statement_import_with_audit",{target_import:r.statementImportId});if(x.error)throw x.error;data=x.data;}else{const x=await supabase.rpc("delete_source_document_with_audit",{target_document:r.documentId});if(x.error)throw x.error;data=x.data;}if(data?.storage_path&&!data?.virtual_sheet)await supabase.storage.from(data.bucket||"universal-intake").remove([data.storage_path]);update(i,{state:"removed",message:"Deleted from active records. The deletion remains in the audit trail.",href:undefined});router.refresh();}catch(e:any){update(i,{message:e?.message||"Could not delete this record."});}}

  async function run(){
    if(!plans.length||busy)return;const terms=wordsFrom(keywordText);if(plans.some(p=>p.action==="analyse_keywords")&&!terms.length){setSummary("At least one selected file is set to keyword analysis. Enter the project/site/client keywords to search for.");return;}try{validateUploadBatch(plans.length,plans.reduce((n,p)=>n+p.file.size,0));}catch(e:any){setSummary(e?.message||"The selected upload batch is not valid.");return;}
    setBusy(true);setSummary("");setResults(plans.map(p=>({name:p.file.name,state:"queued",message:"Waiting…"})));let done=0,review=0,duplicate=0,failed=0;
    try{const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Your session expired. Sign in again.");const {data:batch,error:batchError}=await supabase.from("intake_batches").insert({company_id:companyId,created_by:user.id,total_files:plans.length}).select("id").single();if(batchError||!batch)throw new Error(batchError?.message||"Could not create upload batch.");
      for(let i=0;i<plans.length;i++){
        const plan=plans[i],file=plan.file;let documentId:string|undefined;let intakeItemId:string|undefined;try{
          const ext=(file.name.split(".").pop()||"").toLowerCase();update(i,{state:"working",message:"Checking this file…"});if(file.size>MAX)throw new Error("File is over the 20 MB limit.");if(!supported.includes(ext))throw new Error("Unsupported file type.");if(file.type&&mime[ext]&&!mime[ext].includes(file.type))throw new Error("File contents/type do not match the file extension.");
          const fileHash=await hash(file);const {data:existing}=await supabase.from("source_documents").select("id,project_id,document_type").eq("company_id",companyId).eq("file_hash",fileHash).limit(1).maybeSingle();if(existing){duplicate++;update(i,{state:"duplicate",message:"This exact file already exists. Nothing was counted twice.",documentId:existing.id,href:existing.project_id?`/projects/${existing.project_id}/documents`:"/documents"});continue;}
          const path=`${companyId}/intake/${new Date().getUTCFullYear()}/${Date.now()}-${crypto.randomUUID().slice(0,8)}-${safe(file.name)}`;update(i,{message:"Uploading securely…"});const {error:storageError}=await supabase.storage.from("universal-intake").upload(path,file,{contentType:file.type||undefined,upsert:false});if(storageError)throw storageError;
          const selectedType=plan.hint==="auto"?"other":plan.hint;const {data:doc,error:docError}=await supabase.from("source_documents").insert({company_id:companyId,project_id:projectId||null,document_type:selectedType,file_name:file.name,storage_path:path,file_hash:fileHash,metadata:{bucket:"universal-intake",extension:ext,mime_type:file.type||null,original_size:file.size,intake_project_hint:projectId||null,intake_document_type_hint:plan.hint,intake_action:plan.action,intake_keywords:terms},uploaded_by:user.id}).select("id").single();if(docError||!doc){await supabase.storage.from("universal-intake").remove([path]);throw new Error(docError?.message||"Could not register the uploaded file.");}documentId=doc.id;
          const {data:item,error:itemError}=await supabase.from("intake_items").insert({batch_id:batch.id,company_id:companyId,document_id:doc.id,detected_project_id:projectId||null}).select("id").single();if(itemError||!item){await supabase.from("source_documents").delete().eq("id",doc.id);await supabase.storage.from("universal-intake").remove([path]);throw new Error(itemError?.message||"Could not create intake item.");}intakeItemId=item.id;
          if(plan.action==="store_only"){await supabase.from("intake_items").update({detected_type:selectedType,detected_project_id:projectId||null,confidence:100,status:"applied",suggested_action:{action:"stored_only"},message:"Stored as evidence without changing accounting."}).eq("id",item.id);done++;update(i,{state:"done",type:label(selectedType),message:"Stored safely as evidence. No accounting values were changed.",documentId:doc.id,intakeItemId:item.id,href:projectId?`/projects/${projectId}/documents`:"/documents"});continue;}
          update(i,{message:plan.action==="analyse_keywords"?"Analysing this file and searching your keywords…":"Analysing this file…"});const {data:analysed,error:analysisError}=await supabase.functions.invoke("analyse-intake-document-v3",{body:{documentId:doc.id,batchId:batch.id,documentTypeHint:plan.hint,action:plan.action,keywords:terms}});if(analysisError){const message=await readableFunctionError(analysisError);await supabase.from("intake_items").update({status:"needs_review",message}).eq("id",item.id);review++;update(i,{state:"review",message,documentId:doc.id,intakeItemId:item.id,href:`/review/${item.id}`});continue;}
          await applyResult(i,doc.id,item.id,plan,analysed,terms);if(analysed?.status==="needs_review")review++;else done++;
        }catch(e:any){failed++;update(i,{state:"failed",message:e?.message||"This file could not be processed.",documentId,intakeItemId,href:intakeItemId?`/review/${intakeItemId}`:undefined});}
      }
      await supabase.from("intake_batches").update({processed_files:done+review+duplicate,needs_review_count:review,status:failed===plans.length?"failed":review?"needs_review":"completed",summary:{processed:done,needs_review:review,duplicates:duplicate,failed}}).eq("id",batch.id);setSummary(`${done} organised · ${review} need a decision · ${duplicate} already known · ${failed} failed. Every file was handled independently.`);
    }catch(e:any){setSummary(e?.message||"The upload batch could not start.");}finally{setBusy(false);}
  }

  const showKeywords=plans.some(p=>p.action==="analyse_keywords"||p.hint==="bank_statement");
  return <div className="universal-add">
    {!embedded&&<section className="add-hero"><span>{onboarding?"ONBOARDING · START FROM YOUR RECORDS":"ADD TO CHARISMAK CONSTRUCTION ACCOUNTING"}</span><h1>Bring the records you already use.</h1><p>Upload statements, BOQs, quotations, invoices, bills, receipts and project records. Each file is processed independently, so one bad file never blocks the rest of the batch.</p></section>}
    {embedded&&<section className="smart-section-title"><span>ADD PROJECT RECORDS</span><h2>Upload and understand project documents</h2><p>The same document engine is used here and in the main Add screen. Your project is already selected.</p></section>}
    <section className="add-card">
      <label className="add-drop"><input type="file" multiple accept=".pdf,.csv,.xlsx,.xls,.docx,.jpg,.jpeg,.png,.webp" onChange={e=>choose(Array.from(e.target.files||[]))}/><strong>{plans.length?`${plans.length} file${plans.length===1?"":"s"} selected`:"Choose files"}</strong><span>Up to 20 files · 20 MB each · 100 MB combined</span></label>
      <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:10,marginTop:12}}><label style={fieldLabel}>Default type for selected files<select value={defaultHint} onChange={e=>setDefaultHint(e.target.value as Hint)} style={control}><option value="auto">Detect each file automatically</option><option value="bank_statement">Bank / financial statement</option><option value="invoice">Invoice</option><option value="bill">Supplier bill</option><option value="quotation">Quotation</option><option value="boq">BOQ</option><option value="receipt">Receipt / payment evidence</option><option value="other">Other document</option></select></label><label style={fieldLabel}>Default action<select value={defaultAction} onChange={e=>setDefaultAction(e.target.value as Action)} style={control}><option value="analyse">Analyse and organise</option><option value="analyse_keywords">Analyse + search my keywords</option><option value="store_only">Store as evidence only</option></select></label></div>
      {!!plans.length&&<div style={{display:"flex",justifyContent:"flex-end",marginTop:8}}><button type="button" className="secondary-button" onClick={applyDefaults}>Apply defaults to all selected files</button></div>}
      {!!plans.length&&<div style={{display:"grid",gap:8,marginTop:12}}>{plans.map((p,i)=><div key={`${p.file.name}-${p.file.size}-${i}`} style={{display:"grid",gridTemplateColumns:"minmax(0,1.4fr) minmax(150px,.8fr) minmax(150px,.8fr)",gap:8,alignItems:"end",padding:10,border:"1px solid #e0e8ee",borderRadius:12,background:"#fbfdfe"}}><div style={{minWidth:0}}><b style={{fontSize:11,color:"#183b55",display:"block",overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{p.file.name}</b><small style={{color:"#7b8b98"}}>{(p.file.size/1024).toFixed(0)} KB</small></div><label style={fieldLabel}>This file is<select value={p.hint} onChange={e=>setPlan(i,{hint:e.target.value as Hint})} style={{...control,height:36}}><option value="auto">Auto detect</option><option value="bank_statement">Statement</option><option value="invoice">Invoice</option><option value="bill">Bill</option><option value="quotation">Quotation</option><option value="boq">BOQ</option><option value="receipt">Receipt</option><option value="other">Other</option></select></label><label style={fieldLabel}>Do this<select value={p.action} onChange={e=>setPlan(i,{action:e.target.value as Action})} style={{...control,height:36}}><option value="analyse">Analyse</option><option value="analyse_keywords">Keywords</option><option value="store_only">Store only</option></select></label></div>)}</div>}
      {showKeywords&&<label style={{...fieldLabel,marginTop:10}}>Project/site/client keywords to search<textarea value={keywordText} onChange={e=>setKeywordText(e.target.value)} rows={3} placeholder="e.g. JAHI, COCO, Transcorp, Site A — comma or new line separated" style={{...control,height:"auto",padding:10}}/><small style={{fontWeight:600,color:"#758695"}}>Keywords create project signals for review; they do not silently create projects.</small></label>}
      <div className="add-hint-row"><label><span>Project <small>{embedded?"Selected":"Optional"}</small></span><select value={projectId} disabled={embedded} onChange={e=>setProjectId(e.target.value)}><option value="">No project yet / let Charismak suggest</option>{projects.map(p=><option key={p.id} value={p.id}>{p.project_code} · {p.name}</option>)}</select></label><button className="add-primary" disabled={!plans.length||busy} onClick={run}>{busy?"Processing each file…":"Upload & process"}</button></div>
    </section>
    {!!results.length&&<section className="intake-results"><div className="intake-summary"><h2>What Charismak did</h2><p>{summary||"Processing…"}</p></div>{results.map((r,i)=><article key={`${r.name}-${i}`} className={`intake-result ${r.state}`}><div className="intake-icon">{r.state==="done"?"✓":r.state==="review"?"?":r.state==="duplicate"?"↺":r.state==="failed"?"!":r.state==="removed"?"×":"…"}</div><div className="intake-copy"><strong>{r.name}</strong>{r.type&&<div className="intake-tags"><span>{r.type}</span></div>}<p>{r.message}</p></div><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}>{r.href&&r.state!=="removed"&&<Link href={r.href} className="intake-open">{r.state==="review"?"Decide →":"Open →"}</Link>}{r.documentId&&!["working","queued","removed","duplicate"].includes(r.state)&&<button type="button" className="secondary-button" style={{color:"#a33d3d",borderColor:"#e7caca"}} onClick={()=>removeResult(i)}>Delete</button>}</div></article>)}</section>}
    {onboarding&&<section style={{marginTop:14,padding:14,border:"1px solid #dbe6ec",borderRadius:14,background:"#fff",display:"flex",gap:10,alignItems:"center",justifyContent:"space-between",flexWrap:"wrap"}}><div><b style={{color:"#173a54"}}>You can continue setup after the batch finishes.</b><p style={{margin:"3px 0 0",fontSize:11,color:"#6d7f8e"}}>Next, invite your team and assign their roles/project access.</p></div><Link href="/onboarding/team" className="primary-link-button">Continue to team setup →</Link></section>}
  </div>;
}
