"use client";

import Link from "next/link";
import { useMemo, useState } from "react";

type RoleKey = "md" | "finance" | "director" | "manager";

const roles: Record<RoleKey, { label: string; short: string; accent: string; eyebrow: string; title: string; subtitle: string; nav: { label: string; href?: string }[] }> = {
  md: {
    label: "MD / Owner", short: "MD", accent: "blue", eyebrow: "Executive Overview", title: "Company Control Room",
    subtitle: "Financial position, portfolio risk, profitability and decisions that need your attention.",
    nav: [{label:"Executive"},{label:"Projects",href:"/projects"},{label:"Treasury",href:"/statements"},{label:"Approvals"},{label:"Reports"},{label:"Company"}],
  },
  finance: {
    label: "Accountant / CFO", short: "CFO", accent: "green", eyebrow: "Finance Operations", title: "Finance Operations Hub",
    subtitle: "Transactions, treasury, reconciliation, payments, evidence and financial control.",
    nav: [{label:"Finance Home"},{label:"Transaction Inbox",href:"/statements"},{label:"Banking",href:"/statements"},{label:"Reconciliation",href:"/statements"},{label:"Payments"},{label:"Imprest"},{label:"Reports"}],
  },
  director: {
    label: "Project Director", short: "PD", accent: "purple", eyebrow: "Project Portfolio", title: "Portfolio & Cost Control",
    subtitle: "Compare projects, forecast margins, commitments, funding gaps and delivery risk.",
    nav: [{label:"Portfolio"},{label:"Cost Control",href:"/projects"},{label:"Commitments"},{label:"Variations"},{label:"Approvals"},{label:"Reports"}],
  },
  manager: {
    label: "Project / Construction Manager", short: "PM", accent: "orange", eyebrow: "Site & Project Control", title: "Jahi Residential",
    subtitle: "Your site financial workspace for requests, spending, imprest, evidence and progress.",
    nav: [{label:"My Project",href:"/projects"},{label:"Site Activities"},{label:"Expenses",href:"/statements"},{label:"Requests"},{label:"Imprest"},{label:"Materials"},{label:"Reports"}],
  },
};

const kpi=(t:string,v:string,m:string)=><article className="kpi" key={t}><span>{t}</span><strong>{v}</strong><small>{m}</small></article>;
function LineChart({tone="blue"}:{tone?:string}){return <div className={`chart ${tone}`}><svg viewBox="0 0 700 220" preserveAspectRatio="none" aria-hidden="true"><path className="chart-main" d="M20 190 C80 180 100 140 160 150 S250 110 310 120 S400 78 465 90 S565 48 680 60"/><path className="chart-alt" d="M20 205 C90 195 120 170 175 178 S270 145 330 151 S425 123 485 132 S585 95 680 105"/></svg></div>}
function MDView(){return <><section className="kpi-grid five">{kpi("Total cash","₦245.6m","Portfolio placeholder")}{kpi("Project cash position","₦512.8m","Portfolio placeholder")}{kpi("Outstanding receivables","₦328.2m","Portfolio placeholder")}{kpi("Outstanding commitments","₦267.5m","Portfolio placeholder")}{kpi("Forecast profit","₦183.4m","Portfolio placeholder")}</section><section className="split wide"><article className="panel"><header><small>Company</small><h2>Cash Flow Overview</h2></header><LineChart/></article><article className="panel"><header><small>Portfolio</small><h2>Project Profitability</h2></header><div className="donut-wrap"><div className="donut blue"><div><strong>72%</strong><span>healthy margin</span></div></div></div></article></section><section className="split"><article className="panel"><header><small>Real test project</small><h2>Jahi Residential</h2></header><div className="list-row"><div><b>Funding received</b><span>Retirement baseline</span></div><strong>₦12.60m</strong></div><div className="list-row"><div><b>Confirmed expenditure</b><span>Retirement baseline</span></div><strong>₦12.36m</strong></div><div className="list-row"><div><b>Outstanding commitments</b><span>Retirement baseline</span></div><strong>₦950k</strong></div><Link href="/projects" style={{display:"inline-block",marginTop:12,fontWeight:800,color:"#0b3253"}}>Open real projects →</Link></article><article className="panel"><header><small>Portfolio</small><h2>Funding vs Expenditure</h2></header><LineChart/></article></section></>}
function FinanceView(){return <><section className="hero green"><div><small>Statement workflow</small><h2>Monthly transaction review</h2><p>Upload statements, detect duplicates and classify only new or unresolved movements.</p></div><div className="hero-actions"><Link href="/statements/upload" style={{color:"white",textDecoration:"none",fontWeight:800}}>Upload statement</Link><Link href="/statements" style={{color:"white",textDecoration:"none",fontWeight:800}}>Review imports</Link></div></section><section className="kpi-grid four finance-kpis">{kpi("Unclassified transactions","—","Uses live statement imports")}{kpi("Payments in queue","—","Not implemented yet")}{kpi("Receipts to record","—","Not implemented yet")}{kpi("Overdue imprest","—","Not implemented yet")}</section><section className="split wide"><article className="panel"><header><small>Transaction Inbox</small><h2>Use the live statement review</h2></header><p style={{color:"#718195"}}>Statement rows can now be classified as project expense, project funding, company expense/income, personal/non-business, internal transfer or left for further review.</p><Link href="/statements" style={{fontWeight:800,color:"#0b3253"}}>Open transaction inbox →</Link></article><article className="panel"><header><small>Jahi rule</small><h2>Baseline-safe posting</h2></header><p style={{color:"#718195"}}>Rows inside the existing Jahi retirement period are reconciled as historical evidence without changing the retirement totals. Later confirmed rows can update Jahi.</p></article></section></>}
function DirectorView(){return <><section className="kpi-grid four director-kpis">{kpi("Projects under supervision","1","Jahi is the current real test project")}{kpi("Budget used","—","Awaiting internal budget baseline")}{kpi("Forecast margin","—","Awaiting contract/internal budget")}{kpi("Pending requests","—","Approvals module next")}</section><article className="panel"><header><small>Portfolio</small><h2>Real project workspace</h2></header><p style={{color:"#718195"}}>Open Projects to see Jahi using the retirement baseline and any later confirmed bank-statement movements.</p><Link href="/projects" style={{fontWeight:800,color:"#0b3253"}}>Open Projects →</Link></article></>}
function ManagerView(){return <><section className="hero orange"><div><small className="tag">JAHI-01</small><h2>Jahi Residential</h2><p>Current real project test workspace.</p><span>Jahi, Abuja · retirement baseline through 07 Jul 2026</span></div><div className="imprest"><small>Funding position after commitments</small><strong>-₦707,117.40</strong><span>Based on retirement baseline</span></div></section><section className="quick-actions"><Link href="/projects" style={{textDecoration:"none",color:"inherit"}}><i>J</i><span><b>Open Jahi</b><small>Project financial workspace</small></span></Link><Link href="/statements/upload" style={{textDecoration:"none",color:"inherit"}}><i>+</i><span><b>Upload Statement</b><small>Add monthly bank data</small></span></Link><Link href="/statements" style={{textDecoration:"none",color:"inherit"}}><i>✓</i><span><b>Review Transactions</b><small>Confirm classifications</small></span></Link></section></>}

export default function Home(){const[current,setCurrent]=useState<RoleKey>("md");const role=roles[current];const content=useMemo(()=>current==="md"?<MDView/>:current==="finance"?<FinanceView/>:current==="director"?<DirectorView/>:<ManagerView/>,[current]);return <main className={`app role-${role.accent}`}><aside className="sidebar"><div className="app-mark" aria-label="Charismak Accounting"><div className="logo-circle"><img src="https://raw.githubusercontent.com/CharismakProject/charismak-website/main/public/branding/charismak-logo.png" alt="Charismak"/><b>A</b></div><span>Accounting</span></div><p className="section-label">Switch role</p><div className="role-list">{(Object.keys(roles) as RoleKey[]).map(key=><button key={key} className={`role-button ${key===current?"active":""}`} onClick={()=>setCurrent(key)}><span className="role-icon">{roles[key].short}</span><span><b>{roles[key].label}</b><small>{roles[key].eyebrow}</small></span></button>)}</div><nav>{role.nav.map((item,index)=>item.href?<Link className={index===0?"active":""} href={item.href} key={item.label}>{item.label}</Link>:<button className={index===0?"active":""} key={item.label}>{item.label}</button>)}</nav><div className="truth"><b>✓ Track the truth</b><span>Every movement. Every project.</span></div></aside><section className="content-shell"><header className="topbar"><div><small className="eyebrow">{role.eyebrow}</small><h1>{role.title}</h1><p>{role.subtitle}</p></div><div className="profile"><span>🔔</span><div>CA</div></div></header><div className="mobile-role-tabs">{(Object.keys(roles) as RoleKey[]).map(key=><button key={key} className={key===current?"active":""} onClick={()=>setCurrent(key)}>{roles[key].short}</button>)}</div><div className="dashboard">{content}</div></section></main>}
