import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
import * as XLSX from "npm:xlsx@0.18.5";
import { extractText, getDocumentProxy } from "npm:unpdf";
import { unzipSync } from "npm:fflate@0.8.2";

const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const out=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{...H,"content-type":"application/json"}});
const clean=(s:string)=>s.replace(/\u00a0/g," ").replace(/[ \t]+/g," ").replace(/\n{3,}/g,"\n\n").trim();
const stripXml=(s:string)=>clean(s.replace(/<w:tab[^>]*\/>/g,"\t").replace(/<\/w:p>/g,"\n").replace(/<w:br[^>]*\/>/g,"\n").replace(/<[^>]+>/g," ").replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&#39;/g,"'"));
const parseMoney=(v:string|null|undefined)=>{if(!v)return null;const n=Number(String(v).replace(/[₦N,$]/gi,"").replace(/\s/g,"").replace(/,/g,""));return Number.isFinite(n)?n:null};
const lastMoney=(line:string)=>{const ms=[...line.matchAll(/(?:₦|NGN|N)?\s*([\d,]+(?:\.\d{1,2})?)/gi)];return ms.length?parseMoney(ms[ms.length-1][1]):null};
const formatMoney=(v:number)=>new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:2}).format(v);
const dateFrom=(text:string)=>{const months:{[k:string]:number}={jan:1,january:1,feb:2,february:2,mar:3,march:3,apr:4,april:4,may:5,jun:6,june:6,jul:7,july:7,aug:8,august:8,sep:9,september:9,oct:10,october:10,nov:11,november:11,dec:12,december:12};let m=text.match(/\b(\d{1,2})(?:st|nd|rd|th)?\s+(January|February|March|April|May|June|July|August|September|October|November|December|Jan|Feb|Mar|Apr|Jun|Jul|Aug|Sep|Oct|Nov|Dec),?\s+(20\d{2})\b/i);if(m)return `${m[3]}-${String(months[m[2].toLowerCase()]).padStart(2,"0")}-${m[1].padStart(2,"0")}`;m=text.match(/\b(20\d{2})[-/](\d{1,2})[-/](\d{1,2})\b/);if(m)return `${m[1]}-${m[2].padStart(2,"0")}-${m[3].padStart(2,"0")}`;m=text.match(/\b(\d{1,2})[/-](\d{1,2})[/-](20\d{2})\b/);if(m)return `${m[3]}-${m[2].padStart(2,"0")}-${m[1].padStart(2,"0")}`;m=text.match(/\b(\d{1,2})[/-](\d{1,2})[/-](\d{2})\b/);if(m)return `20${m[3]}-${m[2].padStart(2,"0")}-${m[1].padStart(2,"0")}`;return null};
function amountByLabels(lines:string[],labels:RegExp[]){for(const re of labels){const matches=lines.filter(x=>re.test(x));for(let i=matches.length-1;i>=0;i--){const n=lastMoney(matches[i]);if(n!==null)return n}}return null}
function subtype(text:string){const t=text.toLowerCase();if(/statement of fund retirement|fund retirement/.test(t))return "fund_retirement";if(/request for (?:project )?fund|fund(?:ing)? request|request for payment/.test(t))return "fund_request";if(/\bpurchase order\b|\blpo\b/.test(t))return "purchase_order";if(/additional works|variation order|\bvariation\b|\bvo\d*/.test(t))return "variation";if(/bill of quantities|\bboq\b/.test(t))return "boq";if(/\binvoice\b/.test(t))return "invoice";if(/\bquotation\b|\bproposal\b/.test(t))return "quotation";if(/\breceipt\b/.test(t))return "receipt";if(/\bbill\b/.test(t))return "bill";return "other"}
function sourceType(kind:string){return ["invoice","boq","quotation","receipt","bill"].includes(kind)?kind:"other"}
function effect(kind:string){if(kind==="fund_retirement")return "funding_reconciliation_evidence";if(kind==="fund_request")return "funding_request_evidence";if(kind==="variation")return "variation_candidate";if(kind==="boq")return "contract_baseline_candidate";if(kind==="quotation")return "commercial_scope_candidate";if(kind==="invoice")return "invoice_direction_review";if(kind==="purchase_order")return "reference_only";if(kind==="receipt"||kind==="bill")return "supporting_evidence";return "reference_only"}
function extractReference(lines:string[],text:string,kind:string){for(const re of [/invoice\s*(?:ref(?:erence)?|no\.?|number)\s*[:#-]?\s*([A-Z0-9/._-]+)/i,/quotation\s*(?:ref(?:erence)?|no\.?)\s*[:#-]?\s*([A-Z0-9/._-]+)/i,/proposal\s*(?:ref(?:erence)?|no\.?)\s*[:#-]?\s*([A-Z0-9/._-]+)/i,/purchase order\s*(?:ref(?:erence)?|no\.?|number)?\s*[:#-]?\s*([A-Z0-9/._-]+)/i]){for(const l of lines){const m=l.match(re);if(m)return m[1].replace(/[).,;]+$/g,"")}}if(kind==="purchase_order"){const po=text.match(/\b([A-Z]{2,8}\/LPO\/[A-Z0-9._/-]+)\b/i);if(po)return po[1].replace(/[).,;]+$/g,"");}const m=text.match(/\b(PFI\/(?:INV\/)?CPNL\/[A-Z0-9._/-]+)\b/i);return m?.[1]??null}
function relatedReference(text:string){for(const re of [/(?:further to|in accordance with|quotation ref\.?|original invoice)\s*(?:invoice|quotation)?\s*[:#-]?\s*([A-Z0-9/._-]{6,})/i,/vendor invoice no\.?\s*\n?\s*([A-Z0-9/._-]{6,})/i,/your reference\s*\n?\s*([A-Z0-9/._-]{6,})/i]){const m=text.match(re);if(m)return m[1]?.replace(/[).,;]+$/g,"")??null}return null}
function allReferences(text:string){return Array.from(new Set([...text.matchAll(/\b(?:PFI\/INV\/CPNL\/[A-Z0-9._/-]+|PFI\/CPNL\/[A-Z0-9._/-]+|CPNL\/[A-Z0-9._/-]{5,}|[A-Z]{2,8}\/LPO\/[A-Z0-9._/-]+)\b/gi)].map(m=>m[0].replace(/[).,;]+$/g,"")))).slice(0,20)}
function clientName(lines:string[]){for(const l of lines){const m=l.match(/^\s*client\s*:\s*(.+)$/i);if(m)return m[1].trim().slice(0,200)}return null}
function projectName(lines:string[]){for(const l of lines){const m=l.match(/^\s*project\s*:\s*(.+)$/i);if(m)return m[1].trim().slice(0,250)}return lines.find(l=>/coco|jahi|project/i.test(l)&&l.length<220)??null}
function titleFor(lines:string[],kind:string){const pattern=kind==="fund_retirement"?"fund retirement":kind==="fund_request"?"fund|request":kind==="variation"?"additional works|variation":kind==="purchase_order"?"purchase order|lpo":kind;const priority=lines.find(l=>new RegExp(pattern,"i").test(l)&&l.length<260);return (priority??lines.find(l=>l.length>6&&l.length<220)??"Project document").slice(0,260)}
function pdfLineItems(lines:string[]){const items:any[]=[];let section:string|null=null;for(let i=0;i<lines.length;i++){const line=lines[i].trim();if(!line)continue;if(/^(section\s+[a-z0-9]+|[A-Z]\.?\s+[A-Z][A-Z &/,-]{5,})/i.test(line)&&!/(total|vat|discount)/i.test(line)){section=line.slice(0,180);continue}if(/subtotal|sub-total|grand total|total contract|total before|vat|discount|amount in words|company.?s details/i.test(line))continue;const amt=lastMoney(line);if(amt===null||amt<=0)continue;const startsItem=/^(?:[A-Z]?\d+[A-Z]?|[A-Z]\d+)\b/.test(line);const hasUnit=/\b(sqm|m2|m²|m3|m³|kg|nr|nrs|no\.?|sum|ls|cum|lm|m)\b/i.test(line);if(!startsItem&&!hasUnit)continue;const nums=[...line.matchAll(/(?:₦|NGN|N)?\s*([\d,]+(?:\.\d{1,2})?)/gi)].map(m=>parseMoney(m[1])).filter((n):n is number=>n!==null);const unit=(line.match(/\b(sqm|m2|m²|m3|m³|kg|nr|nrs|no\.?|sum|ls|cum|lm|m)\b/i)||[])[1]??null;items.push({section,item_code:(line.match(/^([A-Z]?\d+[A-Z]?|[A-Z]\d+)\b/)||[])[1]??null,description:line.slice(0,700),unit,quantity:nums.length>=3?nums[nums.length-3]:null,rate:nums.length>=2?nums[nums.length-2]:null,amount:amt,confidence:nums.length>=2?82:68,source_line:i+1});if(items.length>=120)break}return items}
function spreadsheet(bytes:Uint8Array){const wb=XLSX.read(bytes,{type:"array",cellDates:true,raw:false});let best:any[]=[];let sheet="";for(const sn of wb.SheetNames){const rows=XLSX.utils.sheet_to_json(wb.Sheets[sn],{header:1,defval:"",raw:false,blankrows:false}) as any[][];if(rows.length>best.length){best=rows;sheet=sn}}const lines=best.map(r=>r.map(v=>String(v??"").trim()).filter(Boolean).join(" | ")).filter(Boolean);const header=best.slice(0,30).findIndex(r=>r.some(v=>/description|item|work/i.test(String(v)))&&r.some(v=>/amount|rate|qty|quantity/i.test(String(v))));const items:any[]=[];if(header>=0){const h=best[header].map(v=>String(v).trim().toLowerCase().replace(/[^a-z0-9]/g,""));const ix=(...names:string[])=>h.findIndex(x=>names.includes(x));const dc=ix("description","descriptionofwork","itemdescription","workdescription"),uc=ix("unit"),qc=ix("qty","quantity"),rc=ix("rate","unitrate"),ac=ix("amount","total","totalamount"),cc=ix("item","itemno","sn","sno","code");for(let i=header+1;i<best.length;i++){const r=best[i];const desc=dc>=0?String(r[dc]??"").trim():"";const amount=ac>=0?parseMoney(String(r[ac]??"")):null;if(!desc||amount===null)continue;items.push({section:null,item_code:cc>=0?String(r[cc]??"").trim()||null:null,description:desc,unit:uc>=0?String(r[uc]??"").trim()||null:null,quantity:qc>=0?parseMoney(String(r[qc]??"")):null,rate:rc>=0?parseMoney(String(r[rc]??"")):null,amount,confidence:96,source_line:i+1});if(items.length>=200)break}}return{text:clean(lines.join("\n")),items,sheet}}
async function pdf(bytes:Uint8Array){const doc=await getDocumentProxy(bytes);const ex=await extractText(doc,{mergePages:true});const text=clean(String(ex.text||""));if(!text)throw new Error("No selectable text was found. The file may be scanned/image-only; keep it attached and use visual extraction when available.");return{text,items:pdfLineItems(text.split(/\r?\n/).map(clean).filter(Boolean)),sheet:null}}
function docx(bytes:Uint8Array){const files=unzipSync(bytes);const xml=files["word/document.xml"];if(!xml)throw new Error("Word document.xml was not found.");const text=stripXml(new TextDecoder().decode(xml));return{text,items:pdfLineItems(text.split(/\r?\n/).filter(Boolean)),sheet:null}}

Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H});if(req.method!=="POST")return out({error:"POST required"},405);const auth=req.headers.get("Authorization")??"";const sb=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_ANON_KEY")!,{global:{headers:{Authorization:auth}}});const {data:{user}}=await sb.auth.getUser();if(!user)return out({error:"Sign in again."},401);const body=await req.json().catch(()=>({}));const id=String(body?.documentId??"");if(!id)return out({error:"documentId is required"},400);const {data:doc,error:de}=await sb.from("source_documents").select("id,company_id,project_id,file_name,storage_path,metadata").eq("id",id).single();if(de||!doc||!doc.project_id)return out({error:de?.message||"Project document not found"},404);await sb.from("project_document_intelligence").upsert({company_id:doc.company_id,project_id:doc.project_id,document_id:id,analysis_status:"analysing",updated_at:new Date().toISOString()},{onConflict:"document_id"});
try{const bucket=String((doc.metadata as any)?.bucket||"project-documents");const {data:blob,error:se}=await sb.storage.from(bucket).download(doc.storage_path);if(se||!blob)throw new Error(se?.message||"Stored document could not be downloaded");const bytes=new Uint8Array(await blob.arrayBuffer());const ext=String((doc.metadata as any)?.extension??doc.file_name.split(".").pop()??"").toLowerCase();let parsed:{text:string;items:any[];sheet:string|null};if(ext==="pdf")parsed=await pdf(bytes);else if(["xlsx","xls","csv"].includes(ext))parsed=spreadsheet(bytes);else if(ext==="docx")parsed=docx(bytes);else throw new Error(`Automatic text extraction is not yet available for .${ext}. The file remains attached to the project.`);const text=parsed.text,lines=text.split(/\r?\n/).map(clean).filter(Boolean);const kind=subtype(`${doc.file_name}\n${text}`);const reference=extractReference(lines,text,kind);const related=relatedReference(text);const refs=allReferences(text);const subtotal=amountByLabels(lines,[/sub[- ]?total(?!.*section)/i,/total before (?:vat|contingency)/i]);const discount=amountByLabels(lines,[/discount/i]);const vat=amountByLabels(lines,[/\bvat\b/i]);const genericTotal=amountByLabels(lines,[/grand total/i,/total contract sum/i,/contract sum/i,/total amount/i,/total project funding received/i]);const variationDifference=kind==="variation"?amountByLabels(lines,[/\bdifference\b/i,/net variation/i,/variation amount/i]):null;const purchaseOrderTotal=kind==="purchase_order"?amountByLabels(lines,[/^total\b/i,/\btotal amount\b/i]):null;const total=variationDifference??purchaseOrderTotal??genericTotal;const suggested=effect(kind);const commercialReview=["invoice","boq","quotation","variation","purchase_order"].includes(kind);let confidence=70;if(reference)confidence+=8;if(total!==null)confidence+=8;if(kind!=="other")confidence+=8;if(parsed.items.length)confidence+=4;confidence=Math.min(confidence,98);const warnings:string[]=[];if(!parsed.items.length&&["invoice","boq","quotation","variation","bill","purchase_order"].includes(kind))warnings.push("The document total was read, but detailed line items were not confidently structured. Confirm the total and add/edit scope rows if needed.");if(kind==="variation"&&variationDifference!==null)warnings.push(`Variation amount detected from the document's explicit difference: ${formatMoney(variationDifference)}.`);if(kind==="purchase_order")warnings.push("Purchase order detected. It is kept as commercial evidence by default so it does not duplicate an invoice or variation already counted on the project.");
let overlaps:any[]=[];if(kind==="purchase_order"&&parsed.items.length){const {data:apps}=await sb.from("project_document_applications").select("document_id,amount").eq("project_id",doc.project_id).neq("document_id",id);const applied=(apps??[]).filter((a:any)=>Number(a.amount)>0);for(const item of parsed.items){const amount=Number(item.amount||0);if(amount<=0)continue;for(const app of applied){if(Math.abs(Number(app.amount)-amount)<=0.01){overlaps.push({line_item_amount:amount,existing_document_id:app.document_id});}}}overlaps=Array.from(new Map(overlaps.map(x=>[`${x.line_item_amount}:${x.existing_document_id}`,x])).values()).slice(0,10);if(overlaps.length)warnings.push(`Possible duplicate scope detected: ${overlaps.length} purchase-order line item match${overlaps.length===1?"es":""} amount(s) already applied on this project. Review before adding commercial value.`);}
if(commercialReview)warnings.push("Commercial/accounting direction requires confirmation. A supplier document must not be treated as a client invoice or contract baseline automatically.");const fields={sheet:parsed.sheet,reference,related_reference:related,all_references:refs,client_name:clientName(lines),project_name:projectName(lines),document_date:dateFrom(text),subtotal,discount_amount:discount,vat_amount:vat,grand_total:total,reported_total:genericTotal,purchase_order_total:purchaseOrderTotal,variation_difference:variationDifference,possible_duplicate_scope:overlaps,suggested_effect:suggested,commercial_review_required:commercialReview};const now=new Date().toISOString();const {error:ie}=await sb.from("project_document_intelligence").upsert({company_id:doc.company_id,project_id:doc.project_id,document_id:id,analysis_status:"ready",review_status:"pending",detected_subtype:kind,confidence,title:titleFor(lines,kind),document_reference:reference,related_reference:related,client_name:fields.client_name,project_name:fields.project_name,document_date:fields.document_date,subtotal,discount_amount:discount,vat_amount:vat,grand_total:total,suggested_effect:suggested,extracted_fields:fields,extracted_line_items:parsed.items,warnings,raw_text_preview:text.slice(0,5000),analysis_version:"project_document_rules_v3",analysed_at:now,updated_at:now},{onConflict:"document_id"});if(ie)throw new Error(ie.message);await sb.from("source_documents").update({document_type:sourceType(kind),amount:total,document_date:fields.document_date,source_name:fields.client_name,metadata:{...(doc.metadata as any),bucket,analysis_status:"ready",detected_subtype:kind,document_reference:reference,related_reference:related,all_references:refs,variation_difference:variationDifference,purchase_order_total:purchaseOrderTotal,possible_duplicate_scope:overlaps,commercial_review_required:commercialReview}}).eq("id",id);return out({ok:true,documentId:id,kind,confidence,reference,total,variationDifference,purchaseOrderTotal,suggestedEffect:suggested,lineItems:parsed.items.length,overlaps,warnings,requiresReview:commercialReview});}catch(e){const msg=e instanceof Error?e.message:"Document analysis failed";await sb.from("project_document_intelligence").upsert({company_id:doc.company_id,project_id:doc.project_id,document_id:id,analysis_status:"failed",review_status:"needs_attention",warnings:[msg],analysis_version:"project_document_rules_v3",updated_at:new Date().toISOString()},{onConflict:"document_id"});return out({error:msg},422)}});
