import { useCallback, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router, useFocusEffect, useLocalSearchParams } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import { getMobileStagedProjectWorkspace } from "../../lib/staged-project-storage";
import type { MobileStagedProjectWorkspace } from "../../lib/estimate-summary";
import { Card, ScreenTitle, SectionHead, baseStyles as b } from "../../components/ui";

const money=(value:number|null,currency:string)=>value==null?"—":new Intl.NumberFormat("en-NG",{style:"currency",currency,maximumFractionDigits:0}).format(value);const qty=(n:number)=>n.toLocaleString("en-NG",{maximumFractionDigits:3});
export default function ProjectDraft(){const {id}=useLocalSearchParams<{id:string}>();const [loading,setLoading]=useState(true);const [draft,setDraft]=useState<MobileStagedProjectWorkspace|null>(null);const load=useCallback(async()=>{if(!id)return;setDraft(await getMobileStagedProjectWorkspace(id));setLoading(false)},[id]);useFocusEffect(useCallback(()=>{load()},[load]));if(loading)return <SafeAreaView style={b.screen}><View style={s.center}><ActivityIndicator size="large" color="#073f65"/></View></SafeAreaView>;if(!draft)return <SafeAreaView style={b.screen}><View style={s.center}><Text>Draft workspace not available on this device.</Text></View></SafeAreaView>;const c=draft.project.currency;
return <SafeAreaView style={b.screen} edges={["top"]}><ScrollView contentContainerStyle={b.content}><View style={s.backRow}><Pressable onPress={()=>router.back()}><Text style={s.back}>← Projects</Text></Pressable><Text style={s.status}>REVIEWED DRAFT</Text></View><ScreenTitle eyebrow="PROJECT WORKSPACE" title={draft.project.name} subtitle="Estimate → reviewed Budget Baseline → Project. Money/Accounting is not linked yet."/><View style={s.hero}><Text style={s.heroLabel}>INTERNAL COST BUDGET</Text><Text style={s.heroValue}>{money(draft.project.internalCostBudget,c)}</Text><View style={s.heroGrid}><Mini label="Contract" value={money(draft.project.contractValue,c)}/><Mini label="Forecast Profit" value={money(draft.forecastProfit,c)}/><Mini label="Actual Spend" value="—"/></View></View><View style={s.grid}><Metric label="Contractor Direct" value={money(draft.internalDirectCost,c)}/><Metric label="Allowances" value={money(draft.budgetBaseline.allowanceTotal,c)}/><Metric label="Client supplied excluded" value={money(draft.clientSuppliedExcludedValue,c)}/><Metric label="Reconciliation" value={money(draft.budgetBaseline.reconciliationDifference,c)}/></View><SectionHead title="Budget baseline by cost group"/>{draft.costGroups.map(group=><Card key={group.costCode} style={s.row}><View style={{flex:1}}><Text style={s.rowTitle}>{group.costCode} · {group.name}</Text><Text style={s.rowNote}>{group.lineCount} BOQ line{group.lineCount===1?"":"s"}</Text></View><Text style={s.rowAmount}>{money(group.amount,c)}</Text></Card>)}{draft.allowances.map((a,i)=><Card key={`${a.kind}-${i}`} style={s.row}><View style={{flex:1}}><Text style={s.rowTitle}>Allowance · {a.description}</Text><Text style={s.rowNote}>Separate reviewed budget allowance</Text></View><Text style={s.rowAmount}>{money(a.amount,c)}</Text></Card>)}<SectionHead title={`Materials · ${draft.materials.length}`}/>{draft.materials.slice(0,35).map(item=><Card key={item.key} style={s.row}><View style={{flex:1}}><Text style={s.rowTitle}>{item.material}</Text><Text style={s.rowNote}>{item.sources.length} BOQ source item{item.sources.length===1?"":"s"}</Text></View><Text style={s.rowAmount}>{qty(item.quantity)} {item.unit}</Text></Card>)}{!draft.materials.length&&<Card><Text style={b.muted}>No contractor material totals were generated for this estimate.</Text></Card>}<View style={s.moneyBox}><Text style={s.moneyEye}>MONEY / ACCOUNTING</Text><Text style={s.moneyTitle}>Not linked yet</Text><Text style={s.moneyText}>{draft.moneyConnection.note} Confirmed spend and commitments therefore remain “—”, not zero.</Text></View></ScrollView></SafeAreaView>}
function Mini({label,value}:{label:string;value:string}){return <View style={s.mini}><Text style={s.miniLabel}>{label.toUpperCase()}</Text><Text style={s.miniValue}>{value}</Text></View>}function Metric({label,value}:{label:string;value:string}){return <View style={s.metric}><Text style={s.metricLabel}>{label.toUpperCase()}</Text><Text style={s.metricValue}>{value}</Text></View>}
const s=StyleSheet.create({center:{flex:1,alignItems:"center",justifyContent:"center",padding:22},backRow:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},back:{fontSize:11,fontWeight:"800",color:"#0b5c8b"},status:{fontSize:8,fontWeight:"900",color:"#16825c"},hero:{backgroundColor:"#073f65",borderRadius:20,padding:16},heroLabel:{fontSize:8,fontWeight:"900",letterSpacing:1,color:"#9cc2d9"},heroValue:{fontSize:27,fontWeight:"900",color:"#fff",marginVertical:7},heroGrid:{flexDirection:"row",gap:7},mini:{flex:1,borderWidth:1,borderColor:"rgba(255,255,255,.2)",borderRadius:9,padding:8},miniLabel:{fontSize:6,color:"#b9d4e5"},miniValue:{fontSize:9,fontWeight:"900",color:"#fff",marginTop:3},grid:{flexDirection:"row",flexWrap:"wrap",gap:7},metric:{minWidth:"47%",flexGrow:1,borderWidth:1,borderColor:"#dce6ec",borderRadius:11,padding:10,backgroundColor:"#fff"},metricLabel:{fontSize:7,fontWeight:"900",color:"#718391"},metricValue:{fontSize:12,fontWeight:"900",color:"#173f5a",marginTop:3},row:{flexDirection:"row",alignItems:"center",gap:9,paddingVertical:11},rowTitle:{fontSize:10,fontWeight:"900",color:"#29475c"},rowNote:{fontSize:8,color:"#84909a",marginTop:2},rowAmount:{fontSize:10,fontWeight:"900",color:"#0b5c8b"},moneyBox:{backgroundColor:"#fff4ce",borderRadius:13,padding:13},moneyEye:{fontSize:8,fontWeight:"900",letterSpacing:.8,color:"#775c18"},moneyTitle:{fontSize:15,fontWeight:"900",color:"#775c18",marginTop:4},moneyText:{fontSize:9,lineHeight:14,color:"#775c18",marginTop:4}});
