import { COST_CODE_GROUPS, getCostCodeGroup, isValidCostCode, type CostCode } from "./cost-codes.ts";

export type ProgressBudgetLineInput={budgetLineId:string;sourceLineId?:string|null;costCode:CostCode;description:string;unit?:string|null;quantity?:number|null;amount:number};
export type ProgressValuationLineInput={budgetLineId:string;progressPercent?:number|null;completedQuantity?:number|null};
export type ProgressActualInput={transactionId:string;costCode:string|null;amount:number};
export type ProgressLinePosition={budgetLineId:string;sourceLineId:string|null;costCode:CostCode;description:string;unit:string|null;budgetQuantity:number|null;completedQuantity:number|null;progressPercent:number;budgetAmount:number;earnedValue:number;outstandingWorkValue:number};
export type ProgressTradePosition={costCode:CostCode;name:string;budget:number;earnedValue:number;physicalProgressPercent:number|null;actual:number;spendProgressPercent:number|null;spendProgressGapPoints:number|null;costPositionVariance:number;status:"aligned"|"spend_ahead"|"progress_ahead"|"not_budgeted"};
export type ProgressValuationPosition={directBudget:number;earnedValue:number;outstandingWorkValue:number;physicalProgressPercent:number|null;actualCost:number;classifiedActual:number;unclassifiedActual:number;spendToDirectBudgetPercent:number|null;spendProgressGapPoints:number|null;costPositionVariance:number;costEfficiencyIndex:number|null;lines:ProgressLinePosition[];byCostCode:ProgressTradePosition[];unclassifiedTransactionIds:string[];warnings:string[]};

const round=(n:number)=>Math.round((n+Number.EPSILON)*100)/100;
const round4=(n:number)=>Math.round((n+Number.EPSILON)*10000)/10000;
const nonNegative=(n:number,label:string)=>{if(!Number.isFinite(n)||n<0)throw new Error(`${label} must be a non-negative finite number.`);return n;};
const percent=(n:number,label:string)=>{if(!Number.isFinite(n)||n<0||n>100)throw new Error(`${label} must be between 0 and 100.`);return round4(n);};
const ratioPct=(value:number,base:number)=>base<=0?null:Math.round((value/base)*1000)/10;

export function buildProgressValuationPosition(input:{budgetLines:ProgressBudgetLineInput[];valuationLines:ProgressValuationLineInput[];actuals:ProgressActualInput[]}):ProgressValuationPosition{
  const warnings:string[]=[];const budgets=new Map<string,ProgressBudgetLineInput>();
  for(const line of input.budgetLines){if(!line.budgetLineId)throw new Error("Budget line id is required.");if(budgets.has(line.budgetLineId))throw new Error(`Duplicate budget line ${line.budgetLineId}.`);if(!isValidCostCode(line.costCode))throw new Error(`Invalid cost code ${line.costCode}.`);nonNegative(line.amount,`Budget amount ${line.budgetLineId}`);if(line.quantity!=null)nonNegative(line.quantity,`Budget quantity ${line.budgetLineId}`);budgets.set(line.budgetLineId,line);}
  const submitted=new Map<string,ProgressValuationLineInput>();for(const line of input.valuationLines){if(submitted.has(line.budgetLineId))throw new Error(`Duplicate progress line ${line.budgetLineId}.`);if(!budgets.has(line.budgetLineId))throw new Error(`Unknown budget line ${line.budgetLineId}.`);submitted.set(line.budgetLineId,line);}
  const missing=[...budgets.keys()].filter(id=>!submitted.has(id));if(missing.length)warnings.push(`${missing.length} approved budget line(s) have no progress entry and are treated as 0% for this preview.`);
  const lines:ProgressLinePosition[]=[...budgets.values()].map(line=>{const v=submitted.get(line.budgetLineId);const qty=line.quantity==null?null:nonNegative(line.quantity,`Budget quantity ${line.budgetLineId}`);let completedQuantity:number|null=v?.completedQuantity==null?null:nonNegative(v.completedQuantity,`Completed quantity ${line.budgetLineId}`);let progressPercent:number;if(completedQuantity!=null){if(qty==null||qty<=0)throw new Error(`Completed quantity cannot be used for ${line.budgetLineId} because the approved quantity is unavailable or zero.`);if(completedQuantity>qty+0.000001)throw new Error(`Completed quantity exceeds approved quantity for ${line.budgetLineId}.`);progressPercent=percent((completedQuantity/qty)*100,`Progress ${line.budgetLineId}`);}else progressPercent=percent(v?.progressPercent??0,`Progress ${line.budgetLineId}`);const budgetAmount=round(nonNegative(line.amount,`Budget amount ${line.budgetLineId}`));const earnedValue=round(budgetAmount*progressPercent/100);return{budgetLineId:line.budgetLineId,sourceLineId:line.sourceLineId??null,costCode:line.costCode,description:line.description,unit:line.unit??null,budgetQuantity:qty,completedQuantity,progressPercent,budgetAmount,earnedValue,outstandingWorkValue:round(budgetAmount-earnedValue)};});
  const actualByCode=new Map<CostCode,number>();let unclassifiedActual=0;const unclassifiedTransactionIds:string[]=[];for(const row of input.actuals){const amount=round(nonNegative(row.amount,`Actual ${row.transactionId}`));if(!row.costCode||!isValidCostCode(row.costCode)){unclassifiedActual=round(unclassifiedActual+amount);unclassifiedTransactionIds.push(row.transactionId);continue;}actualByCode.set(row.costCode,round((actualByCode.get(row.costCode)??0)+amount));}
  const directBudget=round(lines.reduce((s,r)=>s+r.budgetAmount,0));const earnedValue=round(lines.reduce((s,r)=>s+r.earnedValue,0));const outstandingWorkValue=round(directBudget-earnedValue);const classifiedActual=round([...actualByCode.values()].reduce((s,v)=>s+v,0));const actualCost=round(classifiedActual+unclassifiedActual);const physicalProgressPercent=ratioPct(earnedValue,directBudget);const spendToDirectBudgetPercent=ratioPct(actualCost,directBudget);const spendProgressGapPoints=physicalProgressPercent==null||spendToDirectBudgetPercent==null?null:round(spendToDirectBudgetPercent-physicalProgressPercent);const costPositionVariance=round(earnedValue-actualCost);const costEfficiencyIndex=actualCost<=0?null:Math.round((earnedValue/actualCost)*1000)/1000;
  if(unclassifiedActual>0)warnings.push(`${unclassifiedActual} of posted project spend is unclassified; it is included in project Actual Cost but cannot be assigned to a trade progress row.`);warnings.push("Earned value is an internal cost-control value, not a client valuation, invoice or receivable.");warnings.push("Spend ahead of physical progress can be caused by advance procurement and is a review signal, not proof of waste.");
  const byCostCode= COST_CODE_GROUPS.map(group=>{const costCode=group.code as CostCode;const tradeLines=lines.filter(r=>r.costCode===costCode);const budget=round(tradeLines.reduce((s,r)=>s+r.budgetAmount,0));const tradeEarned=round(tradeLines.reduce((s,r)=>s+r.earnedValue,0));const actual=round(actualByCode.get(costCode)??0);const physical=ratioPct(tradeEarned,budget);const spend=ratioPct(actual,budget);const gap=physical==null||spend==null?null:round(spend-physical);const variance=round(tradeEarned-actual);let status:ProgressTradePosition["status"]="aligned";if(budget<=0&&actual>0.005)status="not_budgeted";else if(gap!=null&&gap>5)status="spend_ahead";else if(gap!=null&&gap< -5)status="progress_ahead";return{costCode,name:getCostCodeGroup(costCode)?.name??group.name,budget,earnedValue:tradeEarned,physicalProgressPercent:physical,actual,spendProgressPercent:spend,spendProgressGapPoints:gap,costPositionVariance:variance,status};}).filter(r=>r.budget>0||r.actual>0);
  return{directBudget,earnedValue,outstandingWorkValue,physicalProgressPercent,actualCost,classifiedActual,unclassifiedActual,spendToDirectBudgetPercent,spendProgressGapPoints,costPositionVariance,costEfficiencyIndex,lines,byCostCode,unclassifiedTransactionIds,warnings:[...new Set(warnings)]};
}
