import Link from "next/link";

const card={padding:18,border:"1px solid #dce7ee",borderRadius:16,background:"#fff",display:"grid",gap:8} as const;
export default function GuidePage(){
  return <main style={{minHeight:"100vh",background:"#f4f8fb",padding:"28px 18px 80px"}}><section style={{width:"min(860px,100%)",margin:"0 auto",display:"grid",gap:18}}>
    <div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><Link href="/welcome">← Welcome</Link><Link href="/onboarding/role" className="primary-link-button">Start onboarding →</Link></div>
    <header className="add-hero"><span>HOW CHARISMAK WORKS</span><h1>Start from the records you already have.</h1><p>Charismak Construction Accounting is built for contractors and construction teams. You can create projects manually, or allow existing statements, BOQs, quotations, invoices, bills and receipts to become the starting point for your accounting.</p></header>
    <section style={card}><b style={{fontSize:18,color:"#173b55"}}>1. Tell Charismak who you are</b><p style={{margin:0,color:"#667c8d",lineHeight:1.6}}>Choose MD/Owner if you are setting up a company workspace. Team members should join through an invitation so their permissions and project access are applied automatically.</p></section>
    <section style={card}><b style={{fontSize:18,color:"#173b55"}}>2. Start with a project or with documents</b><p style={{margin:0,color:"#667c8d",lineHeight:1.6}}>Create a project and attach its starting records, or upload records first and let Charismak suggest where they belong. You do not need to rebuild old accounting manually before using the app.</p></section>
    <section style={card}><b style={{fontSize:18,color:"#173b55"}}>3. Choose what each upload should do</b><p style={{margin:0,color:"#667c8d",lineHeight:1.6}}>For every selected file you can let Charismak detect the type, tell it the document type yourself, analyse it, search project/site/client keywords, or store it only as evidence. Mixed uploads are processed file by file.</p></section>
    <section style={card}><b style={{fontSize:18,color:"#173b55"}}>4. Confirm only what is uncertain</b><p style={{margin:0,color:"#667c8d",lineHeight:1.6}}>High-confidence records are organised automatically. Ambiguous project matches, financial accounts or document meanings go to Needs Your Decision. One unclear file must not stop other files in the batch.</p></section>
    <section style={card}><b style={{fontSize:18,color:"#173b55"}}>5. Run the project and company accounting</b><p style={{margin:0,color:"#667c8d",lineHeight:1.6}}>Use Requests and Approvals, Treasury, Accounting Control, Statements, Project Documents, Reports and the Control Room. Company overhead and company income remain separate from project costs and project funding.</p></section>
    <section style={{...card,background:"#12354f",color:"white"}}><b style={{fontSize:18}}>A useful rule</b><p style={{margin:0,lineHeight:1.6,color:"#d9e7ef"}}>If you already have a document, upload it before entering the same information manually. Charismak should use your existing records as evidence and reduce duplicate data entry.</p><Link href="/onboarding/role" className="primary-link-button">Start using Charismak →</Link></section>
  </section></main>;
}
