import { useMemo, useState } from "react";
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import type { MobileStagedProjectWorkspace } from "../lib/estimate-summary";
import { approveMobileStagedProject, validateMobileProjectApproval, type MobileProjectApprovalDetails } from "../lib/project-approval";

export function ProjectApprovalCard({draft,onApproved}:{draft:MobileStagedProjectWorkspace;onApproved?:(projectId:string)=>void}){const [location,setLocation]=useState("");const [projectCode,setProjectCode]=useState("");const [clientName,setClientName]=useState("");const [projectType,setProjectType]=useState("");const [startDate,setStartDate]=useState("");const [expectedEndDate,setExpectedEndDate]=useState("");const [description,setDescription]=useState("");const [busy,setBusy]=useState(false);const details=useMemo<MobileProjectApprovalDetails>(()=>({location,projectCode,clientName,projectType,startDate,expectedEndDate,description}),[location,projectCode,clientName,projectType,startDate,expectedEndDate,description]);const issues=useMemo(()=>validateMobileProjectApproval(draft,details),[draft,details]);async function approve(){if(issues.length||busy)return;setBusy(true);try{const result=await approveMobileStagedProject(draft,details);Alert.alert("Project approved","Live project and approved Budget Baseline were created. No Money transaction was created.");onApproved?.(result.project_id);}catch(error){Alert.alert("Live approval stopped",error instanceof Error?error.message:"Could not approve this project.");}finally{setBusy(false);}}
return <View style={s.card}><Text style={s.eye}>LIVE PROJECT APPROVAL</Text><Text style={s.title}>Approve this draft into Projects</Text><Text style={s.copy}>MD-only gate. Creates the project and approved Budget Baseline atomically; funding, expenses, commitments and Money transactions remain separate.</Text><View style={s.grid}><Field label="LOCATION *" value={location} onChange={setLocation} placeholder="Jahi, Abuja"/><Field label="PROJECT CODE" value={projectCode} onChange={setProjectCode} placeholder="Optional"/><Field label="CLIENT" value={clientName} onChange={setClientName} placeholder="Optional"/><Field label="PROJECT TYPE" value={projectType} onChange={setProjectType} placeholder="Optional"/><Field label="START DATE" value={startDate} onChange={setStartDate} placeholder="YYYY-MM-DD"/><Field label="EXPECTED END" value={expectedEndDate} onChange={setExpectedEndDate} placeholder="YYYY-MM-DD"/></View><Text style={s.label}>DESCRIPTION</Text><TextInput value={description} onChangeText={setDescription} placeholder="Optional project note" placeholderTextColor="#91a0aa" multiline style={[s.input,{minHeight:62,textAlignVertical:"top"}]}/>{issues.length?<View style={s.warn}><Text style={s.warnTitle}>Still needs review</Text>{issues.slice(0,6).map(issue=><Text key={issue} style={s.warnText}>• {issue}</Text>)}</View>:<View style={s.good}><Text style={s.goodText}>Approval package is internally consistent and ready for the guarded live bridge.</Text></View>}<Pressable disabled={busy||issues.length>0} onPress={approve} style={[s.button,(busy||issues.length>0)&&{opacity:.45}]}><Text style={s.buttonText}>{busy?"Checking approval…":"Approve live project"}</Text></Pressable><Text style={s.micro}>If this build does not have the project-cost bridge enabled, approval stops safely before any live write.</Text></View>}
function Field({label,value,onChange,placeholder}:{label:string;value:string;onChange:(v:string)=>void;placeholder:string}){return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={onChange} placeholder={placeholder} placeholderTextColor="#91a0aa" style={s.input}/></View>}
const s=StyleSheet.create({card:{backgroundColor:"#fff",borderWidth:1,borderColor:"#dce6ec",borderRadius:16,padding:14,gap:8},eye:{fontSize:8,fontWeight:"900",letterSpacing:1,color:"#16825c"},title:{fontSize:15,fontWeight:"900",color:"#173f5a"},copy:{fontSize:9,lineHeight:14,color:"#718391"},grid:{flexDirection:"row",flexWrap:"wrap",gap:7},field:{minWidth:"47%",flexGrow:1},label:{fontSize:7,fontWeight:"900",letterSpacing:.7,color:"#6b7e8c"},input:{borderWidth:1,borderColor:"#cad8e0",backgroundColor:"#fff",borderRadius:9,paddingHorizontal:9,paddingVertical:8,fontSize:10,color:"#173f5a",marginTop:4},warn:{backgroundColor:"#fff4ce",borderRadius:9,padding:9,gap:3},warnTitle:{fontSize:9,fontWeight:"900",color:"#775c18"},warnText:{fontSize:8,lineHeight:12,color:"#775c18"},good:{backgroundColor:"#e7f6ef",borderRadius:9,padding:9},goodText:{fontSize:8,lineHeight:12,color:"#176247",fontWeight:"700"},button:{backgroundColor:"#0b668f",borderRadius:10,paddingVertical:10,alignItems:"center"},buttonText:{fontSize:9,fontWeight:"900",color:"#fff"},micro:{fontSize:7,lineHeight:11,color:"#7c8b96"}});
