import React from "react";
import { Dimensions, Pressable, StyleSheet, Text, View } from "react-native";
import Svg,{Circle,Line,Polyline} from "react-native-svg";

export const money=(v:any,digits=0)=>new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:digits}).format(Number(v||0));
export function ScreenTitle({eyebrow,title,subtitle,right}:{eyebrow?:string;title:string;subtitle?:string;right?:React.ReactNode}){return <View style={s.titleRow}><View style={{flex:1}}>{eyebrow&&<Text style={s.eyebrow}>{eyebrow}</Text>}<Text style={s.title}>{title}</Text>{subtitle&&<Text style={s.subtitle}>{subtitle}</Text>}</View>{right}</View>}
export function Card({children,style}:{children:React.ReactNode;style?:any}){return <View style={[s.card,style]}>{children}</View>}
export function Stat({label,value,note,tone="navy"}:{label:string;value:string;note?:string;tone?:"navy"|"green"|"orange"|"red"}){return <Card style={s.stat}><Text style={s.statLabel}>{label}</Text><Text style={[s.statValue,{color:tone==="green"?"#0a805b":tone==="orange"?"#bd6100":tone==="red"?"#b33d36":"#0b3150"}]}>{value}</Text>{note&&<Text style={s.statNote}>{note}</Text>}</Card>}
export function SectionHead({title,action,onPress}:{title:string;action?:string;onPress?:()=>void}){return <View style={s.sectionHead}><Text style={s.sectionTitle}>{title}</Text>{action&&<Pressable onPress={onPress}><Text style={s.sectionAction}>{action}</Text></Pressable>}</View>}
export function ProgressBar({value,max=100,tone="blue"}:{value:number;max?:number;tone?:"blue"|"green"|"orange"}){const pct=Math.max(0,Math.min(100,max?value/max*100:0));return <View style={s.progress}><View style={[s.progressFill,{width:`${pct}%`,backgroundColor:tone==="green"?"#0a8a63":tone==="orange"?"#e57a08":"#176fe5"}]}/></View>}
export function MiniLine({values,comparison}:{values:number[];comparison?:number[]}){const width=Math.min(Dimensions.get("window").width-56,520),height=130,pad=12;const all=[...values,...(comparison||[])];const max=Math.max(...all,1),min=Math.min(...all,0),range=Math.max(max-min,1);const pts=(arr:number[])=>arr.map((v,i)=>`${pad+(width-pad*2)*(arr.length<=1?0:i/(arr.length-1))},${height-pad-(height-pad*2)*(v-min)/range}`).join(" ");return <Svg width={width} height={height}><Line x1={pad} y1={height-pad} x2={width-pad} y2={height-pad} stroke="#dfe8ef" strokeWidth="1"/>{comparison&&comparison.length>1&&<Polyline points={pts(comparison)} fill="none" stroke="#a4b6c4" strokeWidth="2" strokeDasharray="5 5"/>}{values.length>1&&<Polyline points={pts(values)} fill="none" stroke="#176fe5" strokeWidth="3" strokeLinejoin="round" strokeLinecap="round"/>}{values.map((v,i)=>{const [x,y]=pts(values).split(" ")[i].split(",").map(Number);return <Circle key={i} cx={x} cy={y} r="3" fill="#176fe5"/>})}</Svg>}
export const baseStyles=StyleSheet.create({screen:{flex:1,backgroundColor:"#f3f6fa"},content:{padding:16,paddingBottom:28,gap:12},grid:{flexDirection:"row",flexWrap:"wrap",gap:10},half:{width:"48.4%"},row:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:10},muted:{color:"#758696",fontSize:11},button:{backgroundColor:"#073f65",paddingVertical:11,paddingHorizontal:14,borderRadius:12},buttonText:{color:"white",fontWeight:"900",fontSize:12},outline:{borderWidth:1,borderColor:"#d7e2ea",paddingVertical:10,paddingHorizontal:13,borderRadius:12,backgroundColor:"white"}});
const s=StyleSheet.create({titleRow:{flexDirection:"row",alignItems:"flex-start",gap:10,marginBottom:2},eyebrow:{fontSize:9,letterSpacing:1.4,fontWeight:"900",color:"#0b8b64"},title:{fontSize:28,fontWeight:"900",color:"#0b2e49",marginTop:3},subtitle:{fontSize:12,color:"#748594",marginTop:5,lineHeight:17},card:{backgroundColor:"white",borderRadius:18,padding:14,borderWidth:1,borderColor:"#dfe7ed",shadowColor:"#153d57",shadowOpacity:.04,shadowRadius:12,elevation:1},stat:{minHeight:108,justifyContent:"space-between"},statLabel:{fontSize:10,color:"#738595",fontWeight:"700"},statValue:{fontSize:22,fontWeight:"900",marginVertical:4},statNote:{fontSize:9,color:"#8a98a5"},sectionHead:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginTop:6},sectionTitle:{fontSize:18,fontWeight:"900",color:"#15364f"},sectionAction:{fontSize:11,color:"#0b5f91",fontWeight:"800"},progress:{height:8,borderRadius:99,overflow:"hidden",backgroundColor:"#e9eff4"},progressFill:{height:"100%",borderRadius:99}});
