import React from "react";
import { Dimensions, Pressable, StyleSheet, Text, View } from "react-native";
import Svg,{Circle,Line,Polyline} from "react-native-svg";

export const palette={navy:"#073f65",ink:"#173a53",muted:"#657c8b",line:"#d9e4eb",surface:"#ffffff",bg:"#f4f7fa",green:"#087450",red:"#b3423a",orange:"#bd6100"};
export const money=(v:any,digits=0)=>new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:digits}).format(Number(v||0));
export function ScreenTitle({eyebrow,title,subtitle,right}:{eyebrow?:string;title:string;subtitle?:string;right?:React.ReactNode}){return <View style={s.titleRow}><View style={{flex:1}}>{eyebrow&&<Text style={s.eyebrow}>{eyebrow}</Text>}<Text style={s.title}>{title}</Text>{subtitle&&<Text style={s.subtitle}>{subtitle}</Text>}</View>{right}</View>}
export function Card({children,style}:{children:React.ReactNode;style?:any}){return <View style={[s.card,style]}>{children}</View>}
export function Stat({label,value,note,tone="navy"}:{label:string;value:string;note?:string;tone?:"navy"|"green"|"orange"|"red"}){return <Card style={s.stat}><Text style={s.statLabel}>{label}</Text><Text style={[s.statValue,{color:tone==="green"?palette.green:tone==="orange"?palette.orange:tone==="red"?palette.red:palette.navy}]}>{value}</Text>{note&&<Text style={s.statNote}>{note}</Text>}</Card>}
export function SectionHead({title,action,onPress}:{title:string;action?:string;onPress?:()=>void}){return <View style={s.sectionHead}><Text style={s.sectionTitle}>{title}</Text>{action&&onPress&&<Pressable onPress={onPress}><Text style={s.sectionAction}>{action}</Text></Pressable>}</View>}
export function ProgressBar({value,max=100,tone="blue"}:{value:number;max?:number;tone?:"blue"|"green"|"orange"}){const pct=Math.max(0,Math.min(100,max?value/max*100:0));return <View style={s.progress}><View style={[s.progressFill,{width:`${pct}%`,backgroundColor:tone==="green"?"#0a8a63":tone==="orange"?"#e57a08":"#176fe5"}]}/></View>}
export function ActionButton({label,onPress,variant="primary",disabled=false}:{label:string;onPress:()=>void;variant?:"primary"|"secondary";disabled?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={[s.action,variant==="secondary"&&s.actionSecondary,disabled&&{opacity:.45}]}><Text style={[s.actionText,variant==="secondary"&&s.actionSecondaryText]}>{label}</Text></Pressable>}
export function MiniLine({values,comparison}:{values:number[];comparison?:number[]}){const width=Math.min(Dimensions.get("window").width-56,520),height=130,pad=12;const all=[...values,...(comparison||[])];const max=Math.max(...all,1),min=Math.min(...all,0),range=Math.max(max-min,1);const pts=(arr:number[])=>arr.map((v,i)=>`${pad+(width-pad*2)*(arr.length<=1?0:i/(arr.length-1))},${height-pad-(height-pad*2)*(v-min)/range}`).join(" ");return <Svg width={width} height={height}><Line x1={pad} y1={height-pad} x2={width-pad} y2={height-pad} stroke="#dfe8ef" strokeWidth="1"/>{comparison&&comparison.length>1&&<Polyline points={pts(comparison)} fill="none" stroke="#a4b6c4" strokeWidth="2" strokeDasharray="5 5"/>}{values.length>1&&<Polyline points={pts(values)} fill="none" stroke="#176fe5" strokeWidth="3" strokeLinejoin="round" strokeLinecap="round"/>}{values.map((v,i)=>{const point=pts(values).split(" ")[i];if(!point)return null;const [x,y]=point.split(",").map(Number);return <Circle key={i} cx={x} cy={y} r="3" fill="#176fe5"/>})}</Svg>}
export const baseStyles=StyleSheet.create({screen:{flex:1,backgroundColor:palette.bg},content:{padding:16,paddingBottom:96,gap:16},grid:{flexDirection:"row",flexWrap:"wrap",gap:10},half:{width:"48.4%"},row:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:10},muted:{color:palette.muted,fontSize:14,lineHeight:21,fontFamily:"sans-serif"},button:{backgroundColor:palette.navy,paddingVertical:14,paddingHorizontal:16,borderRadius:13},buttonText:{color:"white",fontWeight:"900",fontSize:15,fontFamily:"sans-serif"},outline:{borderWidth:1,borderColor:palette.line,paddingVertical:13,paddingHorizontal:15,borderRadius:13,backgroundColor:"white"}});
const s=StyleSheet.create({titleRow:{flexDirection:"row",alignItems:"flex-start",gap:10,marginBottom:2},eyebrow:{fontSize:11,letterSpacing:1.3,fontWeight:"900",color:"#0b7d61",fontFamily:"sans-serif"},title:{fontSize:30,lineHeight:36,fontWeight:"900",color:"#0b2e49",marginTop:3,fontFamily:"sans-serif"},subtitle:{fontSize:15,color:palette.muted,marginTop:7,lineHeight:22,fontFamily:"sans-serif"},card:{backgroundColor:"white",borderRadius:18,padding:16,borderWidth:1,borderColor:"#dfe7ed",shadowColor:"#153d57",shadowOpacity:.04,shadowRadius:12,elevation:1},stat:{minHeight:118,justifyContent:"space-between"},statLabel:{fontSize:13,color:"#657b8b",fontWeight:"700",fontFamily:"sans-serif"},statValue:{fontSize:23,fontWeight:"900",marginVertical:6,fontFamily:"sans-serif"},statNote:{fontSize:12,lineHeight:18,color:"#7d8f9b",fontFamily:"sans-serif"},sectionHead:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginTop:7},sectionTitle:{fontSize:19,fontWeight:"900",color:"#15364f",fontFamily:"sans-serif"},sectionAction:{fontSize:14,color:"#0b5f91",fontWeight:"800",fontFamily:"sans-serif"},progress:{height:9,borderRadius:99,overflow:"hidden",backgroundColor:"#e9eff4"},progressFill:{height:"100%",borderRadius:99},action:{minHeight:54,borderRadius:14,backgroundColor:palette.navy,alignItems:"center",justifyContent:"center",paddingHorizontal:16},actionSecondary:{backgroundColor:"#fff",borderWidth:1,borderColor:"#bad0dd"},actionText:{fontSize:16,fontWeight:"900",color:"#fff",fontFamily:"sans-serif"},actionSecondaryText:{color:palette.navy}});