"use client";

import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { TRANSACTION_COST_CODE_OPTIONS, type CostCode, type TransactionCostReviewRow } from "../../../../../lib/project-cost/transaction-cost-review";
import { confirmTransactionCostClassificationsAction } from "./actions";

const money=(value:number,currency:string)=>new Intl.NumberFormat("en-NG",{style:"currency",currency,maximumFractionDigits:0}).format(value);
const badge=(confidence:string)=>confidence==="high"?{background:"#e7f6ef",color:"#176247"}:confidence==="medium"?{background:"#e7f1f8",color:"#0b668f"}:{background:"#fff4ce",color:"#775c18"};

export default function TransactionCostReviewClient({projectId,currency,rows}:{projectId:string;currency:string;rows:TransactionCostReviewRow[]}){
  const router=useRouter();const [selected,setSelected]=useState<Record<string,CostCode|"">>({});const [message,setMessage]=useState<string|null>(null);const [pending,startTransition]=useTransition();
  const chosen=useMemo(()=>rows.flatMap(row=>{const code=selected[row.transactionId];return code?[{transactionId:row.transactionId,costCode:code as CostCode,reason:`User confirmed project cost code ${code} in Actual Cost Classification Review.`}]:[];}),[rows,selected]);
  const highCount=rows.filter(row=>row.readyForBulkConfirm&&row.suggestedCostCode).length;
  function useHigh(){setSelected(current=>{const next={...current};for(const row of rows)if(row.readyForBulkConfirm&&row.suggestedCostCode)next[row.transactionId]=row.suggestedCostCode;return next;});}
  function save(){if(!chosen.length)return;setMessage(null);startTransition(async()=>{const result=await confirmTransactionCostClassificationsAction({projectId,selections:chosen});if(result.ok){setSelected({});setMessage(`${chosen.length} expense${chosen.length===1?"":"s"} classified. Budget vs Actual will refresh from confirmed Money data.`);router.refresh();}else setMessage(result.message);});}
  return <div style={{display:"grid",gap:12}}>
    <section className="compact-card" style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><div><small style={eye}>REVIEW CONTROLS</small><h2 style={title}>{rows.length} unclassified posted expense{rows.length===1?"":"s"}</h2><p style={copy}>Suggestions are not saved automatically. Only the cost codes you explicitly select below will be confirmed.</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button type="button" onClick={useHigh} disabled={highCount===0||pending} style={secondary}>Use {highCount} high-confidence suggestion{highCount===1?"":"s"}</button><button type="button" onClick={()=>setSelected({})} disabled={pending} style={secondary}>Clear</button><button type="button" onClick={save} disabled={!chosen.length||pending} style={{...primary,opacity:!chosen.length||pending?.45:1}}>{pending?"Confirming…":`Confirm selected (${chosen.length})`}</button></div></section>
    {message&&<section style={{background:message.includes("classified")?"#e7f6ef":"#fff4ce",color:message.includes("classified")?"#176247":"#775c18",borderRadius:10,padding:11,fontSize:10}}>{message}</section>}
    {rows.length===0&&<section className="compact-card"><b>All posted expenses are classified.</b><p style={copy}>There is nothing waiting for cost-code review on this project.</p></section>}
    {rows.map(row=><article key={row.transactionId} className="compact-card" style={{display:"grid",gap:9}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"flex-start"}}><div><small style={{fontSize:8,color:"#7b8d99"}}>{row.transactionDate}</small><h3 style={{fontSize:13,color:"#173f5a",margin:"3px 0"}}>{row.title}</h3>{row.description&&<p style={{...copy,maxWidth:760}}>{row.description}</p>}</div><strong style={{fontSize:13,color:"#173f5a",whiteSpace:"nowrap"}}>{money(row.amount,currency)}</strong></div><div style={{display:"grid",gridTemplateColumns:"minmax(220px,1fr) minmax(220px,1fr)",gap:9}}><div style={{border:"1px solid #e2e9ed",borderRadius:9,padding:9}}><div style={{display:"flex",gap:7,alignItems:"center",flexWrap:"wrap"}}><span style={{...badge(row.confidence),fontSize:7,fontWeight:900,borderRadius:999,padding:"4px 7px",textTransform:"uppercase"}}>{row.confidence} confidence</span>{row.suggestedCostCode?<b style={{fontSize:10,color:"#0b668f"}}>{row.suggestedCostCode} · {row.suggestedCostName}</b>:<b style={{fontSize:10,color:"#775c18"}}>No automatic trade suggestion</b>}</div><p style={{...copy,marginTop:6}}>{row.reasons.join(" ")}</p>{row.suggestedCostCode&&<button type="button" onClick={()=>setSelected(s=>({...s,[row.transactionId]:row.suggestedCostCode!}))} style={{...secondary,marginTop:7}}>Use suggestion</button>}</div><label style={{display:"grid",gap:5,border:"1px solid #e2e9ed",borderRadius:9,padding:9}}><span style={label}>CONFIRMED COST CODE</span><select value={selected[row.transactionId]??""} onChange={event=>setSelected(s=>({...s,[row.transactionId]:event.target.value as CostCode|""}))} style={input}><option value="">Not confirmed yet</option>{TRANSACTION_COST_CODE_OPTIONS.map(option=><option key={option.code} value={option.code}>{option.code} · {option.name}</option>)}</select><small style={copy}>Selecting a code here does not edit the transaction until you press Confirm selected.</small></label></div></article>)}
  </div>;
}

const eye:React.CSSProperties={fontSize:8,fontWeight:900,letterSpacing:".1em",color:"#0b668f"};const title:React.CSSProperties={fontSize:15,color:"#173f5a",margin:"5px 0 4px"};const copy:React.CSSProperties={fontSize:9,lineHeight:1.5,color:"#718391",margin:0};const label:React.CSSProperties={fontSize:7,fontWeight:900,letterSpacing:".08em",color:"#6c7f8d"};const input:React.CSSProperties={border:"1px solid #cbd8e0",borderRadius:9,padding:"9px 10px",fontSize:10,color:"#173f5a",background:"#fff"};const primary:React.CSSProperties={border:0,borderRadius:9,padding:"9px 11px",background:"#0b668f",color:"#fff",fontSize:9,fontWeight:900,cursor:"pointer"};const secondary:React.CSSProperties={border:"1px solid #9fc3d7",borderRadius:9,padding:"8px 10px",background:"#fff",color:"#0b668f",fontSize:9,fontWeight:900,cursor:"pointer"};
