-- QA hardening: default role templates should follow least privilege.
-- Owners can still delegate additional permissions with membership overrides.

with managed_positions as (
  select id from public.positions where is_system_template=true and code in (
    'MD_OWNER','CFO','FINANCE_MANAGER','SENIOR_ACCOUNTANT','ACCOUNTANT','ACCOUNTS_OFFICER','CASHIER',
    'PROJECT_DIRECTOR','SENIOR_PROJECT_COORDINATOR','PROJECT_COORDINATOR',
    'CONSTRUCTION_MANAGER','PROJECT_MANAGER','SITE_MANAGER','SITE_ENGINEER','SUPERVISOR','STOREKEEPER'
  )
)
delete from public.position_permissions pp using managed_positions mp where pp.position_id=mp.id;

with desired(position_code,permission_code,scope) as (
  values
  -- MD / Owner: full company control.
  ('MD_OWNER','accounts.manage','company_wide'),('MD_OWNER','approvals.manage','company_wide'),('MD_OWNER','approvals.request','company_wide'),('MD_OWNER','audit.view','company_wide'),('MD_OWNER','budgets.manage','company_wide'),('MD_OWNER','commitments.manage','company_wide'),('MD_OWNER','company.view','company_wide'),('MD_OWNER','documents.apply','company_wide'),('MD_OWNER','documents.confirm','company_wide'),('MD_OWNER','documents.upload','company_wide'),('MD_OWNER','imprest.manage','company_wide'),('MD_OWNER','payments.approve','company_wide'),('MD_OWNER','payments.pay','company_wide'),('MD_OWNER','profitability.view','company_wide'),('MD_OWNER','progress.update','company_wide'),('MD_OWNER','projects.manage','company_wide'),('MD_OWNER','projects.view','company_wide'),('MD_OWNER','reconciliation.manage','company_wide'),('MD_OWNER','reports.export','company_wide'),('MD_OWNER','reports.share_external','company_wide'),('MD_OWNER','reports.view','company_wide'),('MD_OWNER','settings.manage','company_wide'),('MD_OWNER','statements.upload','company_wide'),('MD_OWNER','transactions.confirm','company_wide'),('MD_OWNER','transactions.create','company_wide'),('MD_OWNER','transactions.post','company_wide'),('MD_OWNER','transactions.view','company_wide'),('MD_OWNER','treasury.view','company_wide'),('MD_OWNER','users.manage','company_wide'),('MD_OWNER','variations.manage','company_wide'),

  -- CFO: full finance control, but not company/user/project administration.
  ('CFO','accounts.manage','company_wide'),('CFO','approvals.manage','company_wide'),('CFO','approvals.request','company_wide'),('CFO','audit.view','company_wide'),('CFO','commitments.manage','company_wide'),('CFO','company.view','company_wide'),('CFO','documents.apply','company_wide'),('CFO','documents.confirm','company_wide'),('CFO','imprest.manage','company_wide'),('CFO','payments.approve','company_wide'),('CFO','payments.pay','company_wide'),('CFO','profitability.view','company_wide'),('CFO','projects.view','company_wide'),('CFO','reconciliation.manage','company_wide'),('CFO','reports.export','company_wide'),('CFO','reports.view','company_wide'),('CFO','statements.upload','company_wide'),('CFO','transactions.confirm','company_wide'),('CFO','transactions.create','company_wide'),('CFO','transactions.post','company_wide'),('CFO','transactions.view','company_wide'),('CFO','treasury.view','company_wide'),

  ('FINANCE_MANAGER','accounts.manage','company_wide'),('FINANCE_MANAGER','approvals.manage','company_wide'),('FINANCE_MANAGER','approvals.request','company_wide'),('FINANCE_MANAGER','commitments.manage','company_wide'),('FINANCE_MANAGER','company.view','company_wide'),('FINANCE_MANAGER','documents.apply','company_wide'),('FINANCE_MANAGER','documents.confirm','company_wide'),('FINANCE_MANAGER','imprest.manage','company_wide'),('FINANCE_MANAGER','payments.approve','company_wide'),('FINANCE_MANAGER','payments.pay','company_wide'),('FINANCE_MANAGER','profitability.view','company_wide'),('FINANCE_MANAGER','projects.view','company_wide'),('FINANCE_MANAGER','reconciliation.manage','company_wide'),('FINANCE_MANAGER','reports.export','company_wide'),('FINANCE_MANAGER','reports.view','company_wide'),('FINANCE_MANAGER','statements.upload','company_wide'),('FINANCE_MANAGER','transactions.confirm','company_wide'),('FINANCE_MANAGER','transactions.create','company_wide'),('FINANCE_MANAGER','transactions.post','company_wide'),('FINANCE_MANAGER','transactions.view','company_wide'),('FINANCE_MANAGER','treasury.view','company_wide'),

  ('SENIOR_ACCOUNTANT','accounts.manage','company_wide'),('SENIOR_ACCOUNTANT','approvals.manage','company_wide'),('SENIOR_ACCOUNTANT','approvals.request','company_wide'),('SENIOR_ACCOUNTANT','company.view','company_wide'),('SENIOR_ACCOUNTANT','documents.apply','company_wide'),('SENIOR_ACCOUNTANT','payments.approve','company_wide'),('SENIOR_ACCOUNTANT','projects.view','company_wide'),('SENIOR_ACCOUNTANT','reconciliation.manage','company_wide'),('SENIOR_ACCOUNTANT','reports.export','company_wide'),('SENIOR_ACCOUNTANT','reports.view','company_wide'),('SENIOR_ACCOUNTANT','statements.upload','company_wide'),('SENIOR_ACCOUNTANT','transactions.confirm','company_wide'),('SENIOR_ACCOUNTANT','transactions.create','company_wide'),('SENIOR_ACCOUNTANT','transactions.post','company_wide'),('SENIOR_ACCOUNTANT','transactions.view','company_wide'),('SENIOR_ACCOUNTANT','treasury.view','company_wide'),

  ('ACCOUNTANT','approvals.request','company_wide'),('ACCOUNTANT','company.view','company_wide'),('ACCOUNTANT','documents.apply','company_wide'),('ACCOUNTANT','projects.view','company_wide'),('ACCOUNTANT','reconciliation.manage','company_wide'),('ACCOUNTANT','reports.export','company_wide'),('ACCOUNTANT','reports.view','company_wide'),('ACCOUNTANT','statements.upload','company_wide'),('ACCOUNTANT','transactions.confirm','company_wide'),('ACCOUNTANT','transactions.create','company_wide'),('ACCOUNTANT','transactions.post','company_wide'),('ACCOUNTANT','transactions.view','company_wide'),('ACCOUNTANT','treasury.view','company_wide'),

  ('ACCOUNTS_OFFICER','approvals.request','company_wide'),('ACCOUNTS_OFFICER','company.view','company_wide'),('ACCOUNTS_OFFICER','projects.view','company_wide'),('ACCOUNTS_OFFICER','reports.view','company_wide'),('ACCOUNTS_OFFICER','statements.upload','company_wide'),('ACCOUNTS_OFFICER','transactions.create','company_wide'),('ACCOUNTS_OFFICER','transactions.view','company_wide'),('ACCOUNTS_OFFICER','treasury.view','company_wide'),

  -- Cashier can execute approved payments, but cannot approve, manage accounts or confirm statements.
  ('CASHIER','approvals.request','company_wide'),('CASHIER','company.view','company_wide'),('CASHIER','payments.pay','company_wide'),('CASHIER','projects.view','company_wide'),('CASHIER','transactions.create','company_wide'),('CASHIER','transactions.view','company_wide'),('CASHIER','treasury.view','company_wide'),

  -- Project leadership.
  ('PROJECT_DIRECTOR','approvals.manage','company_wide'),('PROJECT_DIRECTOR','approvals.request','company_wide'),('PROJECT_DIRECTOR','budgets.manage','company_wide'),('PROJECT_DIRECTOR','commitments.manage','company_wide'),('PROJECT_DIRECTOR','company.view','company_wide'),('PROJECT_DIRECTOR','documents.apply','company_wide'),('PROJECT_DIRECTOR','documents.confirm','company_wide'),('PROJECT_DIRECTOR','documents.upload','company_wide'),('PROJECT_DIRECTOR','payments.approve','company_wide'),('PROJECT_DIRECTOR','profitability.view','company_wide'),('PROJECT_DIRECTOR','progress.update','company_wide'),('PROJECT_DIRECTOR','projects.manage','company_wide'),('PROJECT_DIRECTOR','projects.view','company_wide'),('PROJECT_DIRECTOR','reports.export','company_wide'),('PROJECT_DIRECTOR','reports.view','company_wide'),('PROJECT_DIRECTOR','transactions.view','company_wide'),('PROJECT_DIRECTOR','variations.manage','company_wide'),

  ('SENIOR_PROJECT_COORDINATOR','approvals.manage','assigned_projects'),('SENIOR_PROJECT_COORDINATOR','approvals.request','assigned_projects'),('SENIOR_PROJECT_COORDINATOR','budgets.manage','assigned_projects'),('SENIOR_PROJECT_COORDINATOR','commitments.manage','assigned_projects'),('SENIOR_PROJECT_COORDINATOR','documents.apply','assigned_projects'),('SENIOR_PROJECT_COORDINATOR','documents.upload','assigned_projects'),('SENIOR_PROJECT_COORDINATOR','progress.update','assigned_projects'),('SENIOR_PROJECT_COORDINATOR','projects.view','assigned_projects'),('SENIOR_PROJECT_COORDINATOR','reports.export','assigned_projects'),('SENIOR_PROJECT_COORDINATOR','reports.view','assigned_projects'),('SENIOR_PROJECT_COORDINATOR','transactions.view','assigned_projects'),('SENIOR_PROJECT_COORDINATOR','variations.manage','assigned_projects'),

  ('PROJECT_COORDINATOR','approvals.request','assigned_projects'),('PROJECT_COORDINATOR','commitments.manage','assigned_projects'),('PROJECT_COORDINATOR','documents.upload','assigned_projects'),('PROJECT_COORDINATOR','progress.update','assigned_projects'),('PROJECT_COORDINATOR','projects.view','assigned_projects'),('PROJECT_COORDINATOR','reports.view','assigned_projects'),('PROJECT_COORDINATOR','transactions.view','assigned_projects'),

  -- Project/site family.
  ('CONSTRUCTION_MANAGER','approvals.request','assigned_projects'),('CONSTRUCTION_MANAGER','commitments.manage','assigned_projects'),('CONSTRUCTION_MANAGER','documents.upload','assigned_projects'),('CONSTRUCTION_MANAGER','imprest.manage','assigned_projects'),('CONSTRUCTION_MANAGER','progress.update','assigned_projects'),('CONSTRUCTION_MANAGER','projects.view','assigned_projects'),('CONSTRUCTION_MANAGER','reports.view','assigned_projects'),('CONSTRUCTION_MANAGER','transactions.create','assigned_projects'),('CONSTRUCTION_MANAGER','transactions.view','assigned_projects'),
  ('PROJECT_MANAGER','approvals.request','assigned_projects'),('PROJECT_MANAGER','commitments.manage','assigned_projects'),('PROJECT_MANAGER','documents.upload','assigned_projects'),('PROJECT_MANAGER','imprest.manage','assigned_projects'),('PROJECT_MANAGER','progress.update','assigned_projects'),('PROJECT_MANAGER','projects.view','assigned_projects'),('PROJECT_MANAGER','reports.view','assigned_projects'),('PROJECT_MANAGER','transactions.create','assigned_projects'),('PROJECT_MANAGER','transactions.view','assigned_projects'),
  ('SITE_MANAGER','approvals.request','assigned_projects'),('SITE_MANAGER','commitments.manage','assigned_projects'),('SITE_MANAGER','documents.upload','assigned_projects'),('SITE_MANAGER','imprest.manage','assigned_projects'),('SITE_MANAGER','progress.update','assigned_projects'),('SITE_MANAGER','projects.view','assigned_projects'),('SITE_MANAGER','reports.view','assigned_projects'),('SITE_MANAGER','transactions.create','assigned_projects'),('SITE_MANAGER','transactions.view','assigned_projects'),
  ('SITE_ENGINEER','approvals.request','assigned_projects'),('SITE_ENGINEER','documents.upload','assigned_projects'),('SITE_ENGINEER','progress.update','assigned_projects'),('SITE_ENGINEER','projects.view','assigned_projects'),('SITE_ENGINEER','reports.view','assigned_projects'),('SITE_ENGINEER','transactions.create','assigned_projects'),('SITE_ENGINEER','transactions.view','assigned_projects'),
  ('SUPERVISOR','approvals.request','assigned_projects'),('SUPERVISOR','documents.upload','assigned_projects'),('SUPERVISOR','progress.update','assigned_projects'),('SUPERVISOR','projects.view','assigned_projects'),('SUPERVISOR','transactions.create','assigned_projects'),('SUPERVISOR','transactions.view','assigned_projects'),
  ('STOREKEEPER','approvals.request','assigned_projects'),('STOREKEEPER','documents.upload','assigned_projects'),('STOREKEEPER','projects.view','assigned_projects'),('STOREKEEPER','transactions.create','assigned_projects'),('STOREKEEPER','transactions.view','assigned_projects')
), resolved as (
  select p.id position_id, perm.id permission_id, d.scope::public.permission_scope scope
  from desired d
  join public.positions p on p.code=d.position_code and p.is_system_template=true
  join public.permissions perm on perm.code=d.permission_code
)
insert into public.position_permissions(position_id,permission_id,scope)
select position_id,permission_id,scope from resolved
on conflict(position_id,permission_id) do update set scope=excluded.scope;
