export type MobileCostBudget={costCode:string;amount:number};
export type MobileCostActual={transactionId:string;costCode:string|null;amount:number};
export type MobileCostAllowance={kind:"contingency"|"other";amount:number};
export type MobileCostCommitment={commitmentId:string;costCode:string;committedAmount:number;paidAmount:number};
export type MobileCostRow={costCode:string;name:string;budget:number;actual:number;committed:number;unpaidCommitment:number;exposure:number;remaining:number;consumedPercent:number|null;status:"not_budgeted"|"within_budget"|"at_risk"|"over_budget"};
export type MobileProjectCostControl={directBudget:number;allowanceBudget:number;internalBudget:number;actual:number;classifiedActual:number;unclassifiedActual:number;committed:number;unpaidCommitment:number;remainingBudget:number;rows:MobileCostRow[];unclassifiedTransactionIds:string[];commitmentsStatus:"connected"|"not_connected";forecastCostToComplete:number|null;forecastFinalCost:number|null;forecastProfit:number|null;expectedProfitAtBudget:number|null;health:"no_budget"|"within_budget"|"at_risk"|"over_budget";warnings:string[]};
const NAMES:Record<string,string>={"01":"Preliminaries","02":"Substructure","03":"Concrete & Reinforcement","04":"Blockwork & Masonry","05":"Structural Steel","06":"Roofing","07":"Doors","08":"Windows & Glazing","09":"Plastering & Screeding","10":"Floor Finishes","11":"Wall Finishes","12":"Ceilings","13":"Painting & Decoration","14":"Joinery & Fixtures","15":"Plumbing & Sanitary","16":"Electrical","17":"Mechanical & HVAC","18":"External Works","19":"Plant, Equipment & Specialist Works","20":"Professional, Statutory & Other"};
const valid=(code:string|null)=>!!code&&/^(0[1-9]|1[0-9]|20)$/.test(code);const round=(n:number)=>Math.round((n+Number.EPSILON)*100)/100;const safe=(n:number,label:string)=>{if(!Number.isFinite(n)||n<0)throw new Error(`${label} must be non-negative.`);return round(n);};
export function buildMobileProjectCostControl(input:{budgets:MobileCostBudget[];allowances:MobileCostAllowance[];actuals:MobileCostActual[];commitments:MobileCostCommitment[]|null;contractValue:number|null;forecastCostToComplete:number|null}):MobileProjectCostControl{
  const b=new Map<string,number>();for(const row of input.budgets)b.set(row.costCode,round((b.get(row.costCode)??0)+safe(row.amount,`Budget ${row.costCode}`)));
  const a=new Map<string,number>();let unclassifiedActual=0;const unclassifiedTransactionIds:string[]=[];for(const row of input.actuals){const amount=safe(row.amount,`Actual ${row.transactionId}`);if(!valid(row.costCode)){unclassifiedActual=round(unclassifiedActual+amount);unclassifiedTransactionIds.push(row.transactionId);continue;}a.set(row.costCode!,round((a.get(row.costCode!)??0)+amount));}
  const cm=new Map<string,{committed:number;unpaid:number}>();for(const row of input.commitments??[]){const committed=safe(row.committedAmount,`Commitment ${row.commitmentId}`),paid=safe(row.paidAmount,`Paid commitment ${row.commitmentId}`);if(paid>committed+.005)throw new Error(`Paid amount exceeds commitment ${row.commitmentId}.`);const current=cm.get(row.costCode)??{committed:0,unpaid:0};current.committed=round(current.committed+committed);current.unpaid=round(current.unpaid+Math.max(committed-paid,0));cm.set(row.costCode,current);}
  const rows=Object.keys(NAMES).map(costCode=>{const budget=round(b.get(costCode)??0);const actual=round(a.get(costCode)??0);const commitment=cm.get(costCode)??{committed:0,unpaid:0};const exposure=round(actual+commitment.unpaid);const remaining=round(budget-exposure);const status:MobileCostRow["status"]=budget<=0?(exposure>0?"over_budget":"not_budgeted"):exposure>budget+.005?"over_budget":exposure/budget>=.9?"at_risk":"within_budget";return{costCode,name:NAMES[costCode],budget,actual,committed:commitment.committed,unpaidCommitment:commitment.unpaid,exposure,remaining,consumedPercent:budget>0?Math.round(exposure/budget*1000)/10:null,status};});
  const directBudget=round(rows.reduce((s,r)=>s+r.budget,0));const allowanceBudget=round(input.allowances.reduce((s,r)=>s+safe(r.amount,`${r.kind} allowance`),0));const internalBudget=round(directBudget+allowanceBudget);const classifiedActual=round(rows.reduce((s,r)=>s+r.actual,0));const actual=round(classifiedActual+unclassifiedActual);const committed=round(rows.reduce((s,r)=>s+r.committed,0));const unpaidCommitment=round(rows.reduce((s,r)=>s+r.unpaidCommitment,0));const totalExposure=round(actual+unpaidCommitment);const remainingBudget=round(internalBudget-totalExposure);const health=internalBudget<=0?(totalExposure>0?"over_budget":"no_budget"):totalExposure>internalBudget+.005?"over_budget":totalExposure/internalBudget>=.9?"at_risk":"within_budget";const expectedProfitAtBudget=input.contractValue==null?null:round(safe(input.contractValue,"Contract value")-internalBudget);const forecastCostToComplete=input.forecastCostToComplete==null?null:safe(input.forecastCostToComplete,"Forecast cost to complete");const warnings:string[]=[];if(input.commitments==null)warnings.push("Commitments are not connected yet. Exposure currently reflects confirmed actual spend only.");if(unclassifiedActual>0)warnings.push(`${unclassifiedActual} of actual project spend is not yet assigned to a construction cost code.`);if(forecastCostToComplete!=null&&input.commitments!=null&&forecastCostToComplete+.005<unpaidCommitment)warnings.push("Forecast Cost-to-Complete is below known unpaid commitments; review before relying on profit.");const forecastFinalCost=forecastCostToComplete==null?null:round(actual+forecastCostToComplete);const forecastProfit=input.contractValue==null||forecastFinalCost==null?null:round(input.contractValue-forecastFinalCost);
  return{directBudget,allowanceBudget,internalBudget,actual,classifiedActual,unclassifiedActual,committed,unpaidCommitment,remainingBudget,rows,unclassifiedTransactionIds,commitmentsStatus:input.commitments==null?"not_connected":"connected",forecastCostToComplete,forecastFinalCost,forecastProfit,expectedProfitAtBudget,health,warnings};
}
