import { useCallback,useMemo,useState } from "react";
import { ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,View } from "react-native";
import { router,useFocusEffect,useLocalSearchParams } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import { supabase } from "../../lib/supabase";
import { Card,money,ScreenTitle,SectionHead,baseStyles as b,palette } from "../../components/ui";
import { readableError } from "../../lib/mobile-error";

export default function Project(){
  const{id}=useLocalSearchParams<{id:string}>();
  const[loading,setLoading]=useState(true),[project,setProject]=useState<any>(null),[finance,setFinance]=useState<any>(null),[tx,setTx]=useState<any[]>([]),[error,setError]=useState("");
  const load=useCallback(async()=>{if(!id)return;setError("");const[p,f,t]=await Promise.all([
    supabase.from("projects").select("id,project_code,name,location,status,description,contract_value,client_name").eq("id",id).maybeSingle(),
    supabase.from("project_financial_positions").select("project_id,received,spent,funding_position").eq("project_id",id).maybeSingle(),
    supabase.from("transactions").select("id,transaction_date,title,description,amount,kind,category:categories(name)").eq("project_id",id).eq("status","posted").order("transaction_date",{ascending:false}).limit(80)
  ]);const err=p.error||f.error||t.error;if(err)throw err;setProject(p.data);setFinance(f.data);setTx(t.data??[]);setLoading(false)},[id]);
  useFocusEffect(useCallback(()=>{load().catch(e=>{setError(readableError(e,"Could not load this project."));setLoading(false)})},[load]));
  const categoryTotals=useMemo(()=>{const map=new Map<string,number>();tx.filter(r=>r.kind==="expense").forEach(r=>{const c=Array.isArray(r.category)?r.category[0]?.name:r.category?.name;const key=c||"Uncategorised";map.set(key,(map.get(key)||0)+Number(r.amount||0))});return Array.from(map.entries()).sort((a,b)=>b[1]-a[1])},[tx]);
  if(loading)return <SafeAreaView style={b.screen}><View style={s.center}><ActivityIndicator size="large" color={palette.navy}/></View></SafeAreaView>;
  if(!project)return <SafeAreaView style={b.screen}><View style={s.center}><Text style={b.muted}>Project not available.</Text></View></SafeAreaView>;
  const spent=Number(finance?.spent||0),received=Number(finance?.received||0),position=Number(finance?.funding_position||0),contract=Number(project.contract_value||0);
  return <SafeAreaView style={b.screen} edges={["top"]}><ScrollView contentContainerStyle={b.content}>
    <Pressable onPress={()=>router.back()}><Text style={s.back}>← Projects</Text></Pressable>
    <ScreenTitle eyebrow={project.project_code||"PROJECT"} title={project.name} subtitle={`${project.location||"Location not set"}${project.client_name?` · ${project.client_name}`:""}`}/>
    {!!error&&<Card style={s.error}><Text style={s.errorTitle}>Some project accounting could not load</Text><Text style={s.errorCopy}>{error}</Text></Card>}
    <View style={b.grid}><View style={b.half}><MiniCard label="Contract value" value={contract?money(contract):"Not set"}/></View><View style={b.half}><MiniCard label="Money received" value={money(received)}/></View><View style={b.half}><MiniCard label="Money spent" value={money(spent)} red/></View><View style={b.half}><MiniCard label="Cash position" value={money(position)} red={position<0}/></View></View>
    <Card style={s.truth}><Text style={s.truthTitle}>Cash position is not profit.</Text><Text style={s.truthCopy}>It is project money received less recorded project spending. Profit needs earned revenue, costs and the accounting ledger.</Text></Card>
    <View style={s.actions}><Pressable style={s.in} onPress={()=>router.push({pathname:"/new-transaction",params:{kind:"income",projectId:id}})}><Text style={s.inTitle}>＋ Money in</Text><Text style={s.inCopy}>Funding or receipt</Text></Pressable><Pressable style={s.out} onPress={()=>router.push({pathname:"/new-transaction",params:{kind:"expense",projectId:id}})}><Text style={s.outTitle}>− Money out</Text><Text style={s.outCopy}>Job cost or advance</Text></Pressable></View>
    <SectionHead title="Spend by category"/>{categoryTotals.length?categoryTotals.slice(0,8).map(([name,value])=><View key={name} style={s.categoryRow}><Text style={s.categoryName}>{name}</Text><Text style={s.categoryAmount}>{money(value)}</Text></View>):<Card><Text style={b.muted}>No posted project expenses yet.</Text></Card>}
    <SectionHead title="Recent project money"/>{tx.length?tx.slice(0,25).map(t=>{const incoming=t.kind==="income";const category=Array.isArray(t.category)?t.category[0]?.name:t.category?.name;return <View key={t.id} style={s.row}><View style={{flex:1}}><Text style={s.rowTitle}>{t.title||t.description||"Transaction"}</Text><Text style={s.rowMeta}>{t.transaction_date} · {String(t.kind||"movement").replaceAll("_"," ")}{category?` · ${category}`:""}</Text></View><Text style={[s.rowAmount,{color:incoming?palette.green:palette.red}]}>{incoming?"+":"−"}{money(t.amount)}</Text></View>}):<Card><Text style={b.muted}>No posted project money activity yet.</Text></Card>}
  </ScrollView></SafeAreaView>}
function MiniCard({label,value,red=false}:{label:string;value:string;red?:boolean}){return <Card style={s.miniCard}><Text style={s.miniLabel}>{label}</Text><Text style={[s.miniValue,red&&{color:palette.red}]}>{value}</Text></Card>}
const s=StyleSheet.create({center:{flex:1,alignItems:"center",justifyContent:"center"},back:{fontSize:15,fontWeight:"800",color:palette.navy,fontFamily:"sans-serif"},miniCard:{minHeight:105,justifyContent:"center"},miniLabel:{fontSize:13,color:palette.muted,fontFamily:"sans-serif"},miniValue:{fontSize:20,fontWeight:"900",color:palette.navy,marginTop:5,fontFamily:"sans-serif"},truth:{backgroundColor:"#eef6fa",borderColor:"#c9dde8"},truthTitle:{fontSize:15,fontWeight:"900",color:palette.ink,fontFamily:"sans-serif"},truthCopy:{fontSize:13,lineHeight:20,color:palette.muted,marginTop:4,fontFamily:"sans-serif"},actions:{flexDirection:"row",gap:10},in:{flex:1,minHeight:82,borderRadius:15,backgroundColor:palette.navy,padding:14,justifyContent:"center"},inTitle:{fontSize:17,fontWeight:"900",color:"#fff",fontFamily:"sans-serif"},inCopy:{fontSize:13,color:"#c9dce8",marginTop:3,fontFamily:"sans-serif"},out:{flex:1,minHeight:82,borderRadius:15,backgroundColor:"#fff",borderWidth:1,borderColor:palette.line,padding:14,justifyContent:"center"},outTitle:{fontSize:17,fontWeight:"900",color:palette.ink,fontFamily:"sans-serif"},outCopy:{fontSize:13,color:palette.muted,marginTop:3,fontFamily:"sans-serif"},categoryRow:{flexDirection:"row",justifyContent:"space-between",gap:10,paddingVertical:12,borderBottomWidth:1,borderBottomColor:"#e2e8ec"},categoryName:{fontSize:14,fontWeight:"800",color:palette.ink,fontFamily:"sans-serif"},categoryAmount:{fontSize:14,fontWeight:"900",color:palette.navy,fontFamily:"sans-serif"},row:{flexDirection:"row",gap:10,alignItems:"center",paddingVertical:13,borderBottomWidth:1,borderBottomColor:"#e2e8ec"},rowTitle:{fontSize:14,fontWeight:"800",color:palette.ink,fontFamily:"sans-serif"},rowMeta:{fontSize:12,color:palette.muted,marginTop:3,fontFamily:"sans-serif"},rowAmount:{fontSize:14,fontWeight:"900",fontFamily:"sans-serif"},error:{borderColor:"#e4b9b9",backgroundColor:"#fff8f8"},errorTitle:{fontSize:15,fontWeight:"900",color:"#7f2929",fontFamily:"sans-serif"},errorCopy:{fontSize:13,lineHeight:19,color:"#815858",marginTop:4,fontFamily:"sans-serif"}});