import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { createClient } from "../../../../lib/supabase/server";
import { buildProgressValuationPosition } from "../../../../lib/project-cost/progress-valuation";
import type { CostCode } from "../../../../lib/project-cost/cost-codes";
import ProgressValuationClient from "./progress-valuation-client";

const money=(v:number|null|undefined,currency="NGN")=>v==null?"—":new Intl.NumberFormat("en-NG",{style:"currency",currency,maximumFractionDigits:0}).format(v);const pct=(v:number|null)=>v==null?"—":`${v.toLocaleString("en-NG",{maximumFractionDigits:1})}%`;const pretty=(v:string)=>v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
export default async function ProjectProgressPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{saved?:string}>}){
  const {id}=await params;const query=await searchParams;const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");
  const {data:project,error:projectError}=await supabase.from("projects").select("id,name,location,status").eq("id",id).maybeSingle();if(projectError||!project)notFound();
  const bridgeEnabled=process.env.PROJECT_COST_BRIDGE_ENABLED==="true";const enabled=bridgeEnabled&&process.env.PROJECT_PROGRESS_VALUATION_ENABLED==="true";
  if(!enabled)return <Shell id={id} name={project.name}><section className="compact-card" style={{background:"#fff4ce",color:"#775c18"}}><small style={eye}>PROGRESS VALUATION</small><h2 style={title}>Reviewed physical valuation is not activated yet</h2><p style={copy}>The old progress screen depended on database objects that do not exist in the live Accounting schema. Progress Valuation V1 is now isolated behind its own feature flag and will not query or write those missing objects. Enable it only after the reviewed project-cost and progress-valuation migrations are explicitly applied.</p></section></Shell>;
  const {data:budget,error:budgetError}=await (supabase as any).from("project_cost_budgets").select("id,currency_code,direct_cost,allowance_total,internal_cost_budget").eq("project_id",id).eq("status","approved").maybeSingle();if(budgetError||!budget)return <Shell id={id} name={project.name}><Unavailable text="An approved Project Budget Baseline is required before physical progress can be valued."/></Shell>;
  const [{data:budgetLines,error:lineError},{data:transactions,error:txError},{data:latest,error:latestError},{data:history,error:historyError}]=await Promise.all([
    (supabase as any).from("project_cost_budget_lines").select("id,source_line_id,cost_code,description,unit,quantity,amount").eq("budget_id",budget.id).order("created_at"),
    supabase.from("transactions").select("id,amount,cost_code").eq("project_id",id).eq("kind","expense").eq("status","posted"),
    (supabase as any).from("project_progress_valuations").select("id,valuation_version,valuation_date,physical_progress_percent,earned_value,work_summary,approved_at").eq("project_id",id).eq("status","approved").maybeSingle(),
    (supabase as any).from("project_progress_valuations").select("id,valuation_version,valuation_date,physical_progress_percent,earned_value,status,approved_at").eq("project_id",id).order("valuation_version",{ascending:false}).limit(8),
  ]);if(lineError||txError||latestError||historyError)return <Shell id={id} name={project.name}><Unavailable text="Progress Valuation could not read the complete approved baseline, posted expense set and valuation history. No partial position is shown."/></Shell>;
  const latestLines=latest?.id?await (supabase as any).from("project_progress_valuation_lines").select("budget_line_id,progress_percent,completed_quantity").eq("valuation_id",latest.id):{data:[],error:null};if(latestLines.error)return <Shell id={id} name={project.name}><Unavailable text="The latest approved progress line measurements could not be read."/></Shell>;
  const b=(budgetLines??[]).map((r:any)=>({budgetLineId:r.id,sourceLineId:r.source_line_id,costCode:r.cost_code as CostCode,description:r.description,unit:r.unit??null,quantity:r.quantity==null?null:Number(r.quantity),amount:Number(r.amount)}));const a=(transactions??[]).map((r:any)=>({transactionId:r.id,costCode:r.cost_code??null,amount:Number(r.amount)}));const v=(latestLines.data??[]).map((r:any)=>({budgetLineId:r.budget_line_id,progressPercent:Number(r.progress_percent),completedQuantity:r.completed_quantity==null?null:Number(r.completed_quantity)}));const position=buildProgressValuationPosition({budgetLines:b,valuationLines:v,actuals:a});const currency=budget.currency_code||"NGN";
  return <Shell id={id} name={project.name}>
    {query.saved&&<div className="notice notice-green"><b>Progress valuation approved.</b> A new versioned physical-work snapshot has been recorded.</div>}
    <header style={{background:"#082945",borderRadius:18,padding:18,color:"#fff"}}><small style={{fontSize:8,fontWeight:900,letterSpacing:".12em",color:"#9ec5df"}}>PROGRESS VALUATION</small><h1 style={{margin:"6px 0 3px",fontSize:24}}>{project.name}</h1><p style={{margin:0,fontSize:10,color:"#d7e5ef"}}>{project.location||"Location not set"} · physical work is valued at approved internal BOQ/budget rates, not client selling rates.</p><div style={heroGrid}><Hero label="Physical Progress" value={pct(position.physicalProgressPercent)}/><Hero label="Earned Work Value" value={money(position.earnedValue,currency)}/><Hero label="Actual Spend" value={money(position.actualCost,currency)}/><Hero label="Work Outstanding" value={money(position.outstandingWorkValue,currency)}/></div></header>
    <section style={metricGrid}><Metric label="Approved Direct Work" value={money(position.directBudget,currency)}/><Metric label="Spend / Direct Budget" value={pct(position.spendToDirectBudgetPercent)}/><Metric label="Spend vs Progress Gap" value={position.spendProgressGapPoints==null?"—":`${position.spendProgressGapPoints>0?"+":""}${position.spendProgressGapPoints} pts`}/><Metric label="Cost-position Variance" value={money(position.costPositionVariance,currency)}/><Metric label="Unclassified Actual" value={money(position.unclassifiedActual,currency)}/><Metric label="Contingency / Reserve" value={money(Number(budget.allowance_total||0),currency)}/></section>
    <section className="compact-card"><small style={eye}>HOW TO READ THIS</small><h2 style={title}>{position.costPositionVariance<0?"Money is ahead of earned physical work":position.costPositionVariance>0?"Earned physical work is ahead of recorded spend":"Spend and earned work are aligned in value"}</h2><p style={copy}>Cost-position variance = Earned Work Value − posted Actual Spend. A negative figure can result from advance procurement or mobilisation and is a review signal, not proof of overspending. Work Outstanding is the uncompleted value of the approved direct works; it is <b>not</b> Cost-to-Complete.</p></section>
    {position.warnings.map(w=><div key={w} style={{background:"#fff4ce",borderRadius:10,padding:10,fontSize:9,color:"#775c18"}}>{w}</div>)}
    <section className="compact-card"><small style={eye}>TRADE POSITION</small><h2 style={title}>Physical progress compared with spend by construction cost code</h2><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:10}}><thead><tr><Th>Trade</Th><Th right>Budget</Th><Th right>Physical</Th><Th right>Earned</Th><Th right>Actual</Th><Th right>Spend %</Th><Th>Status</Th></tr></thead><tbody>{position.byCostCode.map(r=><tr key={r.costCode} style={{borderTop:"1px solid #e5ecef"}}><Td>{r.costCode} · {r.name}</Td><Td right>{money(r.budget,currency)}</Td><Td right>{pct(r.physicalProgressPercent)}</Td><Td right>{money(r.earnedValue,currency)}</Td><Td right>{money(r.actual,currency)}</Td><Td right>{pct(r.spendProgressPercent)}</Td><Td>{pretty(r.status)}</Td></tr>)}</tbody></table></div></section>
    <section className="compact-card"><small style={eye}>VALUATION HISTORY</small><h2 style={title}>Approved snapshots are versioned</h2>{(history??[]).length?(history??[]).map((h:any)=><div key={h.id} style={{display:"flex",justifyContent:"space-between",gap:10,padding:"8px 0",borderTop:"1px solid #edf2f5",fontSize:9}}><div><b>V{h.valuation_version} · {h.valuation_date}</b><small style={{display:"block",color:"#80909b",marginTop:2}}>{pretty(h.status)}</small></div><div style={{textAlign:"right"}}><b>{Number(h.physical_progress_percent).toFixed(1)}%</b><small style={{display:"block",color:"#80909b"}}>{money(Number(h.earned_value),currency)}</small></div></div>):<p style={copy}>No approved physical valuation exists yet.</p>}</section>
    <ProgressValuationClient projectId={id} currency={currency} budgetLines={b} actuals={a} initialLines={v}/>
  </Shell>;
}
function Shell({id,name,children}:{id:string;name:string;children:React.ReactNode}){return <main className="page-canvas"><div className="page-wrap" style={{display:"grid",gap:14,maxWidth:1050}}><div className="page-toolbar"><Link href={`/projects/${id}/overview`} className="back-link">← {name}</Link><div style={{display:"flex",gap:8}}><Link href={`/projects/${id}/cost-control`} className="secondary-link">Cost Control</Link><Link href="/projects" className="secondary-link">Projects</Link></div></div>{children}</div></main>}
function Unavailable({text}:{text:string}){return <section className="compact-card"><small style={eye}>PROGRESS VALUATION</small><h2 style={title}>Progress valuation unavailable</h2><p style={copy}>{text}</p></section>}
function Hero({label,value}:{label:string;value:string}){return <div style={{border:"1px solid rgba(255,255,255,.22)",borderRadius:10,padding:9}}><small style={{fontSize:7,color:"#b9d4e5"}}>{label.toUpperCase()}</small><b style={{display:"block",fontSize:14,marginTop:3}}>{value}</b></div>}
function Metric({label,value}:{label:string;value:string}){return <div style={{border:"1px solid #dce6ec",borderRadius:11,padding:11,background:"#fff"}}><small style={{fontSize:7,color:"#718391"}}>{label.toUpperCase()}</small><b style={{display:"block",fontSize:13,color:"#173f5a",marginTop:3}}>{value}</b></div>}
function Th({children,right=false}:{children:React.ReactNode;right?:boolean}){return <th style={{textAlign:right?"right":"left",padding:"7px 6px",color:"#6d7f8c",fontSize:8}}>{children}</th>}function Td({children,right=false}:{children:React.ReactNode;right?:boolean}){return <td style={{textAlign:right?"right":"left",padding:"9px 6px",color:"#35566b",whiteSpace:right?"nowrap":"normal"}}>{children}</td>}
const eye:React.CSSProperties={fontSize:8,fontWeight:900,letterSpacing:".1em",color:"#0b668f"};const title:React.CSSProperties={fontSize:15,color:"#173f5a",margin:"5px 0 8px"};const copy:React.CSSProperties={fontSize:10,lineHeight:1.55,color:"#718391",margin:0};const heroGrid:React.CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:8,marginTop:14};const metricGrid:React.CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(165px,1fr))",gap:8};
